// Generated by the Table Description Language compiler.  DO NOT EDIT!
// source: fashion_info.prot

#ifndef _TDL_FASHION_INFO_H_
#define _TDL_FASHION_INFO_H_

#include "table_utility.h"

class FashionInfo;
class FashionInfoManager;


// ===================================================================
#pragma pack( 1 )
class FashionInfo
{
public:
	// nested types ----------------------------------------------------
	typedef uint32	KeyType;
	
	static const uint32 Version = 514395866;
	
	uint32 Key() const;
	
	uint32 baseid() const;
	const char* name() const;
	uint16 type() const;
	uint8 mount_point() const;
	uint16 model_id_man() const;
	uint16 model_id_woman() const;
	
private:
	uint32 m_baseid;
	int    m_name;
	uint16 m_type;
	uint8  m_mount_point;
	uint16 m_model_id_man;
	uint16 m_model_id_woman;
};
#pragma pack()

// -------------------------------------------------------------------
// source: S 时装基础表.xls, sheet: Sheet1
class FashionInfoManager : public Table::Manager, public Singleton< FashionInfoManager >
{
public:
	int Size() const;
	const char* Source() const;
	bool Load( const char *path );
	bool Reload( const char *path );
	
	const FashionInfo& Get( int index ) const;
	const FashionInfo* Find( const uint32 key ) const;
	
private:
	friend class Singleton< FashionInfoManager >;
	typedef Table::RepeatField< FashionInfoManager, FashionInfo >	FashionInfoArray;
	
	FashionInfoManager();
	~FashionInfoManager();
	
private:
	const FashionInfoArray *m_array;
};


// ===================================================================
// inline methords of FashionInfo
inline uint32 FashionInfo::Key() const
{
	return Combiner< uint32 >::Combine( m_baseid );
}

inline uint32 FashionInfo::baseid() const
{
	return m_baseid;
}

inline const char* FashionInfo::name() const
{
	return FashionInfoManager::Instance().String( m_name );
}

inline uint16 FashionInfo::type() const
{
	return m_type;
}

inline uint8 FashionInfo::mount_point() const
{
	return m_mount_point;
}

inline uint16 FashionInfo::model_id_man() const
{
	return m_model_id_man;
}

inline uint16 FashionInfo::model_id_woman() const
{
	return m_model_id_woman;
}


// inline methords of FashionInfoManager
inline FashionInfoManager::FashionInfoManager()
	: m_array( NULL )
{
}

inline FashionInfoManager::~FashionInfoManager()
{
}

inline int FashionInfoManager::Size() const
{
	assert( m_array );
	return m_array->Size();
}

inline const char* FashionInfoManager::Source() const
{
	return "fashion_info.tbl";
}

inline bool FashionInfoManager::Load( const char *path )
{
	const char *data = Table::Manager::Load( path, Source() );
	if( !data )
		return false;
		
	m_array = (const FashionInfoArray *)data;
	return true;
}

inline bool FashionInfoManager::Reload( const char *path )
{
	const char *data = Table::Manager::Reload( path, Source() );
	if( !data )
		return false;
		
	m_array = (const FashionInfoArray *)data;
	return true;
}

inline const FashionInfo& FashionInfoManager::Get( int index ) const
{
	assert( m_array );
	return m_array->Get( index );
}

inline const FashionInfo* FashionInfoManager::Find( uint32 key ) const
{
	assert( m_array );
	return BinarySerach< FashionInfo >( Data( m_array->Offset() ), m_array->Size(), key );
}


#endif
