// Generated by the Table Description Language compiler.  DO NOT EDIT!
// source: family_title.prot

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


public class FmlTtlInfo : Table.Binary, Table.IKey
{
	UInt32       m_id;
	Table.String m_title;
	
	public const UInt32 Version = 493378320;
	
	public UInt64 Key()
	{
		return m_id;
	}
	
	public UInt32 id
	{
		get { return m_id; }
	}
	
	public string title
	{
		get { return m_title; }
	}
	
	public override int Load(byte[] buffer, int index)
	{
		Table.Loader loader = new Table.Loader(ref buffer, index);
		loader.Load(ref m_id).Load(ref m_title);
		return loader.Size;
	}
}

// source: D 道庭职称.xls, sheet: Sheet1
public sealed class FmlTtlInfoManager : Table.Manager<FmlTtlInfo>
{
	private static readonly FmlTtlInfoManager ms_instance = new FmlTtlInfoManager();
	
	private FmlTtlInfoManager()
	{
	}
	
	public static FmlTtlInfoManager instance
	{
		get { return ms_instance; }
	}
	
	public string source
	{
		get { return "family_title.tbl"; }
	}
	
	public bool Load(string path)
	{
		Register();
		return Load(path, source, FmlTtlInfo.Version);
	}
	
	public FmlTtlInfo Find(UInt32 key)
	{
		return FindInternal(key);
	}
	
	#region new helper
	public static object NewFmlTtlInfo()
	{
		return new FmlTtlInfo();
	}
	
	private static void Register()
	{
		Table.NewHelper.Clear();
		Table.NewHelper.Register(typeof(FmlTtlInfo), NewFmlTtlInfo);
	}
	#endregion
}

