--[[
	AU:Loong
	TM:2017.05.09
	BG:UI模块工厂
--]]

require("UI/Sub/UITip")
require("UI/Base/UIBase")
require("UI/Base/Cell")
require("UI/Base/EquipRoot")
require("UI/Base/UIItemCell")
require("UI/UICell/UICell")
require("UI/UICell/UICellLabel")
require("UI/UICell/UICellQuality")
require("UI/UICell/UICellSelect")
require("UI/UICell/UICellSkillUnlock")
require("UI/UICell/UICellAddFriend")
require("UI/UICell/UICellButton")
require("UI/UIScrollView/UIScrollViewBase")
require("UI/UIScrollView/UISVAreaBase")
require("UI/UIScrollView/UISVRepeatBase")
require("UI/Tween/UITweenDigtalFly")
require("UI/Cmn/UIProps")
require("UI/Cmn/UIPageCount")
require("UI/UIMainMenu/UIBuff")
require("UI/UIMainMenu/UISkill")
require("UI/UICopy/UICopyInfoBase")
require("UI/Base/BaseToggle")


--UI工厂
UIFty = {Name = "UIFty"}

local My = UIFty

--模块字典
My.dic = {}

--添加模块
--path(string):模块路径
function My.Add(path)
	local mod = require(path)
	if mod == nil then
		iTrace.Error("Loong", "UI模块:", path, "未返回")
		return
	end
	local name = mod.Name
	if name == nil then
		iTrace.Error("Loong", "UI模块:", path, "无Name字段")
		return
	end
	local dic = My.dic
	local it = dic[name]
	if it then
		iTrace.Error("Loong", "重复添加UI模块:", path)
	else
		dic[name] = mod
	end
end

local Add = My.Add
Add("UI/UILiveness/UILiveness")
Add("UI/UILiveness/UIGuideJump")
Add("UI/UIAnswer/UIAnswer")
Add("UI/UIAwardPopup/UIAwardPopup")
Add("UI/UILvAward/UILvAward")
Add("UI/UIFamilyAnswer/UIFamilyAnswer")
Add("UI/UIFamilyActiv/UIFamilyBossIt")
Add("UI/UIFamilyActiv/UIFamilyAnswerIt")
Add("UI/UIArena/UITopFightIt")
Add("UI/UIFamilyActiv/UIFamilyBoss")
-- Add("UI/UIFamilyActiv/UIOpenMsg")
Add("UI/UITreasure/UITreasure")
Add("UI/UITreasure/UITreasRuneTip")
Add("UI/UIRankActiv/UIRankActiv")
Add("UI/UIVIPExperience/UIVIPExperience")
Add("UI/UISuccess/UISuccess")
Add("UI/UISuccess/UISuccessShow")
Add("UI/UIImmortalSoul/UIImmortalSoul")
Add("UI/UIArena/UITopFight")
Add("UI/UIArena/UITopFightEnd")
Add("UI/UIMarry/UIMarry")
Add("UI/UIMarry/UIMarryPop")
Add("UI/UIMarry/UIMarryCopy/UIMarryCopy")
Add("UI/UIMarry/UIMarryCopy/UIMarryAnim")
Add("UI/UIMarry/UIProposePop/UIProposePop")
Add("UI/UIMarry/UIMarryInfo/UIMarryInfo")
Add("UI/UITimeLimitActiv/UITimeLimitActiv")
Add("UI/UITimeLimitActiv/UISevenInvest")
Add("UI/UITimeLimitActiv/UITimeLimitBuy")
Add("UI/UIWish/UIWish")
Add("UI/UIDiscountGift/UIDiscountGift")
Add("UI/UIFamilyMission/UIFamilyMission")
Add("UI/UIFamilyMission/UIFamilyHelp")
Add("UI/UICopyPopup/UICopyPopup")
Add("UI/UILimitActiv/UILimitActiv")
Add("UI/Base/UILoading")
Add("UI/Base/UILogin")
Add("UI/Base/UIMainMenu")
Add("UI/Base/UISystem")
Add("UI/Base/UINPCDialog")
Add("UI/Base/UIDialog")
Add("UI/Base/UIInteractPanel")
Add("UI/Base/UICopyTowerPanel")
Add("UI/Base/UIGetRewardPanel")
Add("UI/Base/UIGetRewardPanel_II")
Add("UI/Base/UIPicCollect")
Add("UI/Base/UIMission")
Add("UI/UIGet/UIGetItem")
Add("UI/Base/UISkyBook")
Add("UI/Base/UIRedMenu")
Add("UI/Sub/UICrossfade")
Add("UI/Sub/UICollection")
-- Add("UI/UIBackpack/PropSale")
-- Add("UI/UIBackpack/PropSaleTip")
Add("UI/UIBackpack/PsdPanel")
Add("UI/UIBackpack/PricePanel")
Add("UI/Base/UIVIPTip")
Add("UI/Base/UIToV4")
Add("UI/Sub/MsgBox")
Add("UI/Sub/MsgTip")
Add("UI/Sub/UIGM")
Add("UI/Sub/UIDownload")
Add("UI/Base/UIOther")
Add("UI/Base/UIChapterPanel")
Add("UI/Base/UIChapterEff")
Add("UI/UIBoss/BossKillOut")
Add("UI/UIBoss/BossCostTip")
Add("UI/UIBoss/MergeTip")
Add("UI/UIBoss/UIBossOpenTip")
Add("UI/UIBoss/ExitBtn")
Add("UI/Base/UITeamActive")
Add("UI/Base/UIOperationTip")
Add("UI/Robbery/UIRobbery")
Add("UI/Base/UIMoneyTreePanel")
Add("UI/Base/UIMask")
Add("UI/Base/UIMaskFade")
Add("UI/Pendants/UIShowPendant")
Add("UI/UIEquip/UIEquip")
Add("UI/UICompound/UICompound")
Add("UI/UIEquipCollection/UIEquipCollection")
Add("UI/Base/UIBetterEquip")
Add("UI/Base/UIEndPanel")
Add("UI/Base/UIEndPanelTX")
Add("UI/Adv/UIAdv")
Add("UI/Base/UICopy")
Add("UI/UIRevive/UIRevive")
Add("UI/UIFriend/UIFriendRequest")
Add("UI/UIFriend/UIFriendsRecommend")
Add("UI/UIFriend/UIFriendRequestPanel")
Add("UI/Base/UIMenuTip")
Add("UI/SelectGift/SelectGift")
--Add("UI/Base/UIFriend")
Add("UI/UIStore/UIStore")
Add("UI/UIVIPStore/UIVIPStore")
Add("UI/UIChat/UIChat")
Add("UI/UIChat/UISendVoice")
Add("UI/UINotice/UINotice")
Add("UI/UIMapSystem/UIMapWnd")
Add("UI/UIMapSystem/UIMapTipWnd")
Add("UI/UIFamily/UIFamilyListWnd")
Add("UI/UIFamily/UIFamilyMainWnd")
Add("UI/UIFamily/UIFamilyTipsWnd")
Add("UI/UIFamily/UIFamilyDepotWnd")
Add("UI/UIFamily/UIFamilyWarehouse")
Add("UI/UIFamily/UIFamilySkillWnd")
Add("UI/UIFamily/UIFamilyDefendWnd")
Add("UI/UIFamily/UIFamilyTDInfoWnd")
Add("UI/UIFamily/UIFamilyDefendtor")
Add("UI/UIFamily/UIFamilyRedPWnd")
Add("UI/UIFamily/UIGiftMoneyWnd")
Add("UI/Base/UITeam")
Add("UI/Base/UIMyTeam")
Add("UI/Sub/UIRefresh")
Add("UI/Sub/QuickUsePro")
Add("UI/UITop")
Add("UI/UICGTipWnd")
Add("UI/Base/PropTip")
Add("UI/Base/ImmortalSoulTip")
Add("UI/Base/StoreHouse")
Add("UI/UIStoreHouse/UIStoreHouse")
Add("UI/Base/KnotTip")
Add("UI/Base/EquipTip")
Add("UI/Base/SkyMysteryTip")
Add("UI/Base/GuardTip")
Add("UI/Base/UISkyMysterySeal")
Add("UI/UIElfRenewal/UIElfRenewal")
Add("UI/Base/UIElixirTip")
Add("UI/Base/FirstChangePack")
Add("UI/UIRole/UIRole")
Add("UI/UICreatePanel/UICreatePanel")
Add("UI/Base/UIRank")
Add("UI/Base/UIFlyPro")
Add("UI/Base/UIFlyExp")
Add("UI/Base/FightTip")
Add("UI/UIBoss/UIBoss")
Add("UI/UIVIP/UIVIP")
Add("UI/Guide/UIGuide")
Add("UI/Base/UICountDownTip")
Add("UI/UIBoss/UIExitMap")
Add("UI/UIThrUniBattle/UIUniverseBattle")
Add("UI/UIArena/UIArena")
Add("UI/UIArena/UIPeakResult")
Add("UI/UIArena/UIOffLBat")
Add("UI/UIBoss/UIBossList")
Add("UI/UIBoss/BossCareTip")
Add("UI/Sub/UIBBS")
Add("UI/Setting/UISetting")
Add("UI/Base/UISurverPanel")
Add("UI/UIRebirth/UIRebirth")
Add("UI/UIFestivalAct/UIFestivalAct")
Add("UI/UIBenefit/UIBenefit")
-- Add("UI/UIAmbit/UIAmbit")
Add("UI/UITitle/UITitle")
Add("UI/UIRank/UIOtherInfoCPM")
Add("UI/UIOffLineHang/UIOffLineReward")
Add("UI/UIActPreview/UIActPreview")
Add("UI/Base/AddCellPanel")
Add("UI/UIIdentification/UIIdentification")
Add("UI/Base/UIShowGetCPM")
Add("UI/UIOpenService/UIEvrDayPay")
Add("UI/UIComTips/UIComTips")
Add("UI/UIOpenService/UIFirstPay")
Add("UI/UIFamilyWar/UIFamilyWar")
Add("UI/Base/BatchUse")
Add("UI/UIFamilyWar/UIFamilyWarInfo")
Add("UI/UIFamilyWar/UIFamilyWarEnd")
Add("UI/UITemple/UITemple")
Add("UI/UIFashion/UIFashionPanel")
Add("UI/Market/UIMarketWnd")
Add("UI/Auction/UIAuction")
Add("UI/Auction/ShelfTip")
Add("UI/Auction/AttrTip")
Add("UI/UIElvesExperience/UIElvesExperience")
Add("UI/UIOpenService/UIFirstCPM")
Add("UI/Base/UIChangeName")
Add("UI/Rune/UIRune")
Add("UI/UIRoleList/UIRoleList")
Add("UI/UIRushBuy/UIRushBuy")
Add("UI/UILvLimitBuy/UILvLimitBuyWnd")
Add("UI/Cmn/UIUseTip")
Add("UI/Base/UIFightStatus")
Add("UI/Base/UIGetWay")
Add("UI/Robbery/RobberyTip/UIRobberyTip")
-- Add("UI/UICopy/UICopyInfoBase")
Add("UI/UICopy/UICopyInfoTimer")
Add("UI/UICopy/UICopyInfoExp")
Add("UI/UICopy/UICopyInfoCmn")
Add("UI/UICopy/UICopyInfoLove")
Add("UI/UICopy/UICopyInfoTower")
Add("UI/UICopy/UICopyInfoPub")
Add("UI/UICopy/UICopyInfoTD")
Add("UI/UICopy/UIRobberyInfo")
Add("UI/UICopy/UICopyFvElmnt")
Add("UI/UICloudBuy/UICloudBuy")
Add("UI/UIFeedback/UIConnPanel")
Add("UI/MarriageTree/MarrTipPanel")
Add("UI/Flowers/UIFlowers")
Add("UI/UIPray/UIRetreatAward")
Add("UI/UIPray/UIOffLineTip")
Add("UI/UISoulBearst/UISoulBearst")
Add("UI/UISoulBearst/UISBEquipTip")
Add("UI/UIOnWay/UIOnWay")
Add("UI/UITransApp/UITransApp")
Add("UI/Robbery/UISpiritEquipTip")
Add("UI/SpiritCompose/UISpiritCompose")
Add("UI/SpiritStrength/UISpiritStrength")
Add("UI/SpiritAdv/UISpiritAdv")
Add("UI/Cross/UICross")
Add("UI/UIThroneApp/UIThroneApp")
Add("UI/UICopy/UICopyInfoTreasure")
Add("UI/UITreasureReward/TreasureRewardBox")
Add("UI/UIActPreview/UIFuncOpen")
Add("UI/UICopy/UICopyInfoXM")
Add("UI/UIBossReward/UIBossReward")
Add("UI/UIBlastFur/UIBlastFur")
Add("UI/UIVIP/VipShoeMsg")
Add("UI/UISuit/UISuit")
Add("UI/UIDemon/UIDemonArea")
Add("UI/UIDemon/UIDemonReward")
Add("UI/UIDemon/UIDemonInfo")
Add("UI/Base/UIEndPanelT")
Add("UI/UIFightTreasure/UIFightTreasure")
Add("UI/UIV4Panel/UIV4Panel")
Add("UI/UIBoss/UIWBAtkList")
Add("UI/UIDemon/UICellsShow")
Add("UI/UIElvesNew/UIElvesNew")
Add("UI/UIPet/UIPetDevourPack")
Add("UI/UIFamilyEscort/UIFamilyEscort")
Add("UI/UIFamilyEscort/UIEscortBat")
Add("UI/UITreaFever/UITreaFever")
Add("UI/UIFiveElmnts/UIFiveElmntAttr")
Add("UI/FirstSmall/UIFirstSmall")
Add("UI/UIAlchemy/UIAlchemy")
Add("UI/ItemModel/UIItemModel")
Add("UI/ZaDan/UIZaDan")
Add("UI/UIDrawLots/UIDrawLots")
Add("FortuneCat/UIFortuneCatPanel");
Add("UI/UIBlackMarket/UIBlackMarket")
Add("UI/UILuckFull/UILuckFull")
Add("UI/UITongtianRank/UITongtianRank")
Add("UI/PayMul/UIPayMul")
Add("UI/OutGift/UIOutGift")
Add("TongTianTower/UITongTianTower");
Add("UI/UIHappyChest/UIHappyChest")
Add("UI/PracticeSec/UIPracticeSec")
Add("UI/UIHeavenLove/UIHeavenLove")

--根据UI类型名称创建 指定UI
function My.Create(name)
	local ui = My.dic[name]
	if ui == nil then
		iTrace.Error("Loong", "未在UIFty中添加:" .. name)
	end
	return ui
end

--判断是否包含UI
--name(string):ui名称
function My.Contains(name)
	if name == nil then return false end
	local ui = My.dic[name]
	if ui then
		return true
	else
		return false
	end
end

--获取模块
function My.Get(name)
	local ui = My.dic[name]
	do return ui end
end

return My
