// Generated by the Table Description Language compiler.  DO NOT EDIT!
// source: drop_boss.prot

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


public class DropBoss : Table.Binary, Table.IKey
{
	UInt32 m_id;
	UInt32 m_specialDrop;
	UInt32 m_drop1;
	UInt32 m_drop2;
	UInt32 m_drop3;
	UInt32 m_drop4;
	UInt32 m_drop5;
	UInt32 m_drop6;
	UInt32 m_drop7;
	UInt32 m_drop8;
	UInt32 m_drop9;
	UInt32 m_drop10;
	UInt32 m_drop11;
	UInt32 m_drop12;
	UInt32 m_drop13;
	UInt32 m_drop14;
	UInt32 m_drop15;
	UInt32 m_drop16;
	UInt32 m_drop17;
	UInt32 m_drop18;
	UInt32 m_drop19;
	UInt32 m_drop20;
	
	public const UInt32 Version = 4064357542;
	
	public UInt64 Key()
	{
		return m_id;
	}
	
	public UInt32 id
	{
		get { return m_id; }
	}
	
	public UInt32 specialDrop
	{
		get { return m_specialDrop; }
	}
	
	public UInt32 drop1
	{
		get { return m_drop1; }
	}
	
	public UInt32 drop2
	{
		get { return m_drop2; }
	}
	
	public UInt32 drop3
	{
		get { return m_drop3; }
	}
	
	public UInt32 drop4
	{
		get { return m_drop4; }
	}
	
	public UInt32 drop5
	{
		get { return m_drop5; }
	}
	
	public UInt32 drop6
	{
		get { return m_drop6; }
	}
	
	public UInt32 drop7
	{
		get { return m_drop7; }
	}
	
	public UInt32 drop8
	{
		get { return m_drop8; }
	}
	
	public UInt32 drop9
	{
		get { return m_drop9; }
	}
	
	public UInt32 drop10
	{
		get { return m_drop10; }
	}
	
	public UInt32 drop11
	{
		get { return m_drop11; }
	}
	
	public UInt32 drop12
	{
		get { return m_drop12; }
	}
	
	public UInt32 drop13
	{
		get { return m_drop13; }
	}
	
	public UInt32 drop14
	{
		get { return m_drop14; }
	}
	
	public UInt32 drop15
	{
		get { return m_drop15; }
	}
	
	public UInt32 drop16
	{
		get { return m_drop16; }
	}
	
	public UInt32 drop17
	{
		get { return m_drop17; }
	}
	
	public UInt32 drop18
	{
		get { return m_drop18; }
	}
	
	public UInt32 drop19
	{
		get { return m_drop19; }
	}
	
	public UInt32 drop20
	{
		get { return m_drop20; }
	}
	
	public override int Load(byte[] buffer, int index)
	{
		Table.Loader loader = new Table.Loader(ref buffer, index);
		loader.Load(ref m_id).Load(ref m_specialDrop).Load(ref m_drop1).Load(ref m_drop2).Load(ref m_drop3).Load(ref m_drop4).Load(ref m_drop5).Load(ref m_drop6).Load(ref m_drop7).Load(ref m_drop8).Load(ref m_drop9).Load(ref m_drop10).Load(ref m_drop11).Load(ref m_drop12).Load(ref m_drop13).Load(ref m_drop14).Load(ref m_drop15).Load(ref m_drop16).Load(ref m_drop17).Load(ref m_drop18).Load(ref m_drop19).Load(ref m_drop20);
		return loader.Size;
	}
}

// source: D 掉落Boss表.xls, sheet: Sheet1
public sealed class DropBossManager : Table.Manager<DropBoss>
{
	private static readonly DropBossManager ms_instance = new DropBossManager();
	
	private DropBossManager()
	{
	}
	
	public static DropBossManager instance
	{
		get { return ms_instance; }
	}
	
	public string source
	{
		get { return "drop_boss.tbl"; }
	}
	
	public bool Load(string path)
	{
		Register();
		return Load(path, source, DropBoss.Version);
	}
	
	public DropBoss Find(UInt32 key)
	{
		return FindInternal(key);
	}
	
	#region new helper
	public static object NewDropBoss()
	{
		return new DropBoss();
	}
	
	private static void Register()
	{
		Table.NewHelper.Clear();
		Table.NewHelper.Register(typeof(DropBoss), NewDropBoss);
	}
	#endregion
}

