--******************************************************************************
-- Copyright(C) Phantom CO,.LTD. All rights reserved
-- Created by Loong's tool. Please do not edit it.
-- proto:D_答题题库.xml, excel:D 答题题库.xlsx, sheet:Sheet1
--******************************************************************************
AnswerCfg={}
local We=AnswerCfg
We["1"]={id=1, question="昆虫是世界上种类和数量最多、分布最广的动物", result=1}
We["2"]={id=2, question="井水清澈透明，是一种纯净的水", result=0}
We["3"]={id=3, question="地球上最大的动物是蓝鲸", result=1}
We["4"]={id=4, question="地球上每一个地方都有明显的四季变化", result=0}
We["5"]={id=5, question="浮在水面上的物体受到水的浮力，沉在水中的物体没有受到水的浮力", result=0}
We["6"]={id=6, question="造纸术、印刷术、指南针和火药是我国古代的四大发明", result=1}
We["7"]={id=7, question="人脑中控制人平衡力的是小脑", result=1}
We["8"]={id=8, question="中华人民共和国位于亚洲的东部，太平洋的西岸", result=1}
We["9"]={id=9, question="老鼠和羊都是杂食动物", result=0}
We["10"]={id=10, question="空气中的氧气是支持燃烧的", result=1}
We["11"]={id=11, question="汉字是目前世界上使用人口最多的文字", result=1}
We["12"]={id=12, question="我国历史上第一个统一的多民族封建国家为秦朝", result=1}
We["13"]={id=13, question="所有的欲望对人对社会都是有害的", result=0}
We["14"]={id=14, question="睡眠是一种无意识的状态", result=1}
We["15"]={id=15, question="对他人的第一印象一旦形成，就不会再改变", result=0}
We["16"]={id=16, question="任何食品，不论什么环境下，不加防腐剂的食品是最好的食品", result=0}
We["17"]={id=17, question="中国素有“烹饪王国”称号", result=1}
We["18"]={id=18, question="150级开启仙侣系统", result=1}
We["19"]={id=19, question="空腹吃山楂有助于减肥", result=0}
We["20"]={id=20, question="这个游戏真好玩", result=1}
We["21"]={id=21, question="上海的最高建筑是东方明珠塔", result=1}
We["22"]={id=22, question="反复烧开的水亚硝酸盐含量增高，不宜饮用", result=1}
We["23"]={id=23, question="蛇有4颗毒牙", result=0}
We["24"]={id=24, question="蟋蟀是用翅膀发出声音", result=1}
We["25"]={id=25, question="击败BOSS可以使你变得更强", result=1}
We["26"]={id=26, question="正确护理头发的方法是：用干毛巾轻轻按湿头发", result=1}
We["27"]={id=27, question="蚯蚓是靠鼻子呼吸的", result=0}
We["28"]={id=28, question="生态危机与人类浪费的关系最密切", result=1}
We["29"]={id=29, question="甲骨文是写在龟骨上面的", result=1}
We["30"]={id=30, question="生态危机与人类浪费的关系最密切", result=1}
We["31"]={id=31, question="240级开启仙侣系统", result=0}
We["32"]={id=32, question="260级BOSS掉落八阶装备", result=0}
We["33"]={id=33, question="华佗被称为“药王”", result=0}
We["34"]={id=34, question="英国的乞丐要交纳乞丐税", result=1}
We["35"]={id=35, question="将塑料袋按在水中,松手后继续沉底的塑料袋是有毒的", result=1}
We["36"]={id=36, question="非洲最南端的国家是南非", result=1}
We["37"]={id=37, question="打BOSS是游戏装备的主要出处", result=1}
We["38"]={id=38, question="在野外击败挂机的玩家会变成红名", result=1}
We["39"]={id=39, question="世界上最大的鸟是孔雀", result=0}
We["40"]={id=40, question="荷兰风车主要用于发电", result=0}
We["41"]={id=41, question="亚马逊平原是世界上最大的平原", result=1}
We["42"]={id=42, question="万有引力是普朗克提出的", result=0}
We["43"]={id=43, question="食醋可以治疗牙周炎", result=1}
We["44"]={id=44, question="煤本身的元素与金刚石一样的", result=1}
We["45"]={id=45, question="宙斯神像属于世界七大奇迹", result=0}
We["46"]={id=46, question="食物的大部分营养成分是碳水化合物", result=1}
We["47"]={id=47, question="如果有猛兽要袭击你,你逃跑时应选择 “之”字形路线", result=1}
We["48"]={id=48, question="我国总计有72种语言", result=0}
We["49"]={id=49, question="在中国5月份的第二个星期日是母亲节", result=1}
We["50"]={id=50, question="海里有不游水的鱼", result=1}
We["51"]={id=51, question="“老骥伏枥,志在千里”是曹操的诗句", result=1}
We["52"]={id=52, question="被誉为“钢琴诗人”的是肖邦", result=1}
We["53"]={id=53, question="青蛙冬眠是因为青蛙是冷血动物", result=1}
We["54"]={id=54, question="随团旅游时,导游索要小费,旅行社应赔偿索要金额的3倍", result=0}
We["55"]={id=55, question="《水浒传》中人称“浪里白条”的是张顺", result=1}
We["56"]={id=56, question="金鱼身体变黑就会死去", result=1}
We["57"]={id=57, question="“海上丝绸之路”的始发点是上海", result=0}
We["58"]={id=58, question="蚊子叮人后吐出的唾液会使人发痒", result=1}
We["59"]={id=59, question="蝌蚪变成青蛙时,鳃变成了肺", result=0}
We["60"]={id=60, question="太阳风产生于日冕", result=1}
We["61"]={id=61, question="保温瓶能热但不能保“冷”", result=0}
We["62"]={id=62, question="走路比站着耗费体力", result=0}
We["63"]={id=63, question="夏天洗冷水浴对身体好", result=0}
We["64"]={id=64, question="日食是因为月球挡住了人们的视线", result=1}
We["65"]={id=65, question="小猫可以喝狗奶", result=1}
We["66"]={id=66, question="雪是规则的晶体", result=1}
We["67"]={id=67, question="“沉鱼落雁，闭月羞花”中的“闭月”指的是王昭君", result=0}
We["68"]={id=68, question="未满12岁的儿童,不能在马路上骑自行车", result=1}
We["69"]={id=69, question="火灾逃跑时,遇到浓烟,应直立行走", result=0}
We["70"]={id=70, question="用牙膏可以清洗茶渍", result=1}
We["71"]={id=71, question="出现低血糖时,应该躺下休息", result=0}
We["72"]={id=72, question="最早的扇子是羽毛做的", result=1}
We["73"]={id=73, question="沙漠地形地震发生机会最小", result=1}
We["74"]={id=74, question="世界地球日是每年的4月22号", result=1}
We["75"]={id=75, question="青竹院可以获得大量银两奖励", result=0}
We["76"]={id=76, question="青竹院可以获得大量经验奖励", result=1}
We["77"]={id=77, question="失落谷可以获得大量经验奖励", result=0}
We["78"]={id=78, question="海龟把蛋产在海底", result=0}
We["79"]={id=79, question="人们常用“闭月羞花,沉鱼落雁”形容女子的美貌，其中“沉鱼”是指貂蝉", result=0}
We["80"]={id=80, question="被称为“天下第一香”的是茉莉花", result=1}
We["81"]={id=81, question="中药可用铁锅煎", result=0}
We["82"]={id=82, question="猫的味觉很发达,因此舌尖很敏感,所以猫怕吃烫东西", result=1}
We["83"]={id=83, question="钢化玻璃强度很高,但破碎后容易伤人", result=0}
We["84"]={id=84, question="开屏的孔雀是母孔雀", result=0}
We["85"]={id=85, question="围棋对局开始是由黑方先下", result=1}
We["86"]={id=86, question="京剧、国画、中医被誉为中国的3大国粹", result=1}
We["87"]={id=87, question="完成成就可以获得大量铜钱奖励", result=1}
We["88"]={id=88, question="完成成就可以获得大量绑元奖励", result=1}
We["89"]={id=89, question="世界上最大的古代土石建筑工程是中国的万里长城", result=1}
We["90"]={id=90, question="天机印系统开启等级为135", result=1}
We["91"]={id=91, question="百湾角可以获得大量银两奖励", result=1}
We["92"]={id=92, question="250级开启幽冥地界", result=0}
We["93"]={id=93, question="我国被称为“不夜城”的城市是上海", result=0}
We["94"]={id=94, question="被鲁迅称为“史家之绝唱，无韵之离骚”的作品是《史记》", result=1}
We["95"]={id=95, question="击败世界BOSS不会减少挑战次数", result=0}
We["96"]={id=96, question="炒菜前应该把油倒到锅里就开始炒菜", result=1}
We["97"]={id=97, question="V1玩家可免费进入洞天福地二层", result=0}
We["98"]={id=98, question="骨折高发期在冬季", result=1}
We["99"]={id=99, question="世界BOSS疲劳值上限是5", result=0}
We["100"]={id=100, question="馒头是诸葛亮发明的", result=1}
