--******************************************************************************
-- Copyright(C) Phantom CO,.LTD. All rights reserved
-- Created by Loong's tool. Please do not edit it.
-- proto:U_打开场景入口UI表.xml, excel:U 打开场景入口UI表.xls, sheet:Sheet1
--******************************************************************************
ESOUICfg={}
local We=ESOUICfg
We["100"]={tn="UILoading"}
We["101"]={tn="UILogin"}
We["102"]={tn="UIMainMenu"}
We["104"]={tn="UINPCDialog"}
We["105"]={tn="UICrossfade"}
We["107"]={tn="UIGM"}
We["109"]={tn="UISkill"}
We["110"]={tn="UICopyInfo"}
We["111"]={tn="UIEquip"}
We["112"]={tn="UIOperationTip"}
We["113"]={tn="UIMask"}
We["114"]={tn="UICopy"}
We["115"]={tn="UIBuff"}
We["116"]={tn="UIEndPanel"}
We["118"]={tn="MsgBox"}
We["120"]={tn="UIAdv"}
We["121"]={tn="UIPet"}
We["124"]={tn="UIRevive"}
We["125"]={tn="UIStore"}
We["127"]={tn="UIFriendsRecommend"}
We["128"]={tn="UIFriend"}
We["129"]={tn="UIChat"}
We["130"]={tn="UIMapWnd"}
We["131"]={tn="UIFamilyListWnd"}
We["133"]={tn="UITeam"}
We["134"]={tn="UIMyTeam"}
We["135"]={tn="UIFamilyMainWnd"}
We["136"]={tn="UIMessagebox"}
We["137"]={tn="UICGTipWnd"}
We["138"]={tn="UICollection"}
We["139"]={tn="UIRole"}
We["140"]={tn="UICreatePanel"}
We["141"]={tn="UIRank"}
We["143"]={tn="UINPCDialog"}
We["144"]={tn="UIFlyPro"}
We["145"]={tn="UIVIP"}
We["146"]={tn="UIGuide"}
We["147"]={tn="UIMainMenuLeft"}
We["150"]={tn="UIUniverseBattle"}
We["151"]={tn="UIInteractPanel"}
We["154"]={tn="UIFamilyDepotWnd"}
We["155"]={tn="UIFamilyDefendWnd"}
We["156"]={tn="UIFriendRequestPanel"}
We["157"]={tn="UIFamilyTDInfoWnd"}
We["158"]={tn="UIDialog"}
We["159"]={tn="UIArena"}
We["160"]={tn="UIPeakResult"}
We["161"]={tn="UIOffLBat"}
We["162"]={tn="UIFamilySkillWnd"}
We["163"]={tn="UILiveness"}
We["164"]={tn="UISystem"}
We["165"]={tn="PropSale"}
We["166"]={tn="UIBoss"}
We["167"]={tn="UIBossList"}
We["168"]={tn="UITeamActive"}
We["169"]={tn="UIMenuTip"}
We["170"]={tn="UIAnswer"}
We["171"]={tn="UICopyTowerPanel"}
We["172"]={tn="UIGetRewardPanel"}
We["173"]={tn="UIGetRewardPanel_II"}
We["174"]={tn="UISign"}
We["175"]={tn="UISurverPanel"}
We["176"]={tn="FightTip"}
We["177"]={tn="UIAwardPopup"}
We["178"]={tn="QuickUsePro"}
We["179"]={tn="UIRebirth"}
We["180"]={tn="UIFamilyAnswer"}
We["181"]={tn="UILvAward"}
We["182"]={tn="UIFamilyAnswerIt"}
We["183"]={tn="UIOther"}
We["184"]={tn="UIOpenMsg"}
We["185"]={tn="UIFamilyBoss"}
We["186"]={tn="UIEscort"}
We["187"]={tn="UIFamilyDefendtor"}
We["188"]={tn="UITreasure"}
We["189"]={tn="UIFestivalActivities"}
We["190"]={tn="UISkyBook"}
We["191"]={tn="UITreasRuneTip"}
We["192"]={tn="UIBenefit"}
We["193"]={tn="UIAmbit"}
We["194"]={tn="UIFamilyRedPWnd"}
We["195"]={tn="UITitle"}
We["196"]={tn="UIRankActiv"}
We["197"]={tn="UIOtherInfoCPM"}
We["198"]={tn="UIOffLineReward"}
We["199"]={tn="UIFamilyBossIt"}
We["200"]={tn="AddCellPanel"}
We["201"]={tn="UIActPreview"}
We["202"]={tn="UIIdentification"}
We["203"]={tn="UIShowGetCPM"}
We["204"]={tn="UIEvrDayPay"}
We["205"]={tn="UIChapterPanel"}
We["206"]={tn="UIComTips"}
We["207"]={tn="UIFirstPay"}
We["208"]={tn="UIChapterEff"}
We["209"]={tn="UIFamilyWar"}
We["210"]={tn="UIFamilyWarInfo"}
We["211"]={tn="UIFamilyWarEnd"}
We["212"]={tn="UIVIPExperience"}
We["213"]={tn="UISuccess"}
We["214"]={tn="BatchUse"}
We["215"]={tn="UIMarketWnd"}
We["216"]={tn="UIFashionPanel"}
We["217"]={tn="UISuccessShow"}
We["218"]={tn="UIElvesExperience"}
We["219"]={tn="UIFirstCPM"}
We["220"]={tn="UIChangeName"}
We["221"]={tn="UITemple"}
We["222"]={tn="UITopFight"}
We["223"]={tn="UITopFightEnd"}
We["224"]={tn="UIRune"}
We["225"]={tn="UIRoleList"}
We["226"]={tn="UIChooseQuality"}
We["227"]={tn="SelectGift"}
We["229"]={tn="UITopFightIt"}
We["230"]={tn="UIRobbery"}
We["10025"]={tn="UIShowPendant"}
We["10026"]={tn="PropTip"}
We["10027"]={tn="EquipTip"}
We["10029"]={tn="UICountDownTip"}
We["10030"]={tn="UIExitMap"}
We["10031"]={tn="UINotice"}
