--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_act_online_get_reward_tos_pb')

M_ACT_ONLINE_GET_REWARD_TOS = protobuf.Descriptor();
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD = protobuf.FieldDescriptor();

M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.name = "minute"
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.full_name = ".m_act_online_get_reward_tos.minute"
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.number = 1
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.index = 0
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.label = 1
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.has_default_value = true
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.default_value = 0
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.type = 5
M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD.cpp_type = 1

M_ACT_ONLINE_GET_REWARD_TOS.name = "m_act_online_get_reward_tos"
M_ACT_ONLINE_GET_REWARD_TOS.full_name = ".m_act_online_get_reward_tos"
M_ACT_ONLINE_GET_REWARD_TOS.nested_types = {}
M_ACT_ONLINE_GET_REWARD_TOS.enum_types = {}
M_ACT_ONLINE_GET_REWARD_TOS.fields = {M_ACT_ONLINE_GET_REWARD_TOS_MINUTE_FIELD}
M_ACT_ONLINE_GET_REWARD_TOS.is_extendable = false
M_ACT_ONLINE_GET_REWARD_TOS.extensions = {}

m_act_online_get_reward_tos = protobuf.Message(M_ACT_ONLINE_GET_REWARD_TOS)

