--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_act_marry_three_life_achieve_toc_pb')

M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC = protobuf.Descriptor();
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();

M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.name = "err_code"
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.full_name = ".m_act_marry_three_life_achieve_toc.err_code"
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.number = 1
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.index = 0
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.label = 1
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.has_default_value = true
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.default_value = 0
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.type = 5
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD.cpp_type = 1

M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC.name = "m_act_marry_three_life_achieve_toc"
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC.full_name = ".m_act_marry_three_life_achieve_toc"
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC.nested_types = {}
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC.enum_types = {}
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC.fields = {M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC_ERR_CODE_FIELD}
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC.is_extendable = false
M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC.extensions = {}

m_act_marry_three_life_achieve_toc = protobuf.Message(M_ACT_MARRY_THREE_LIFE_ACHIEVE_TOC)

