--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_achievement_reward_tos_pb')

M_ACHIEVEMENT_REWARD_TOS = protobuf.Descriptor();
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD = protobuf.FieldDescriptor();

M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.name = "achievement_id"
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.full_name = ".m_achievement_reward_tos.achievement_id"
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.number = 1
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.index = 0
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.label = 1
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.has_default_value = true
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.default_value = 0
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.type = 5
M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD.cpp_type = 1

M_ACHIEVEMENT_REWARD_TOS.name = "m_achievement_reward_tos"
M_ACHIEVEMENT_REWARD_TOS.full_name = ".m_achievement_reward_tos"
M_ACHIEVEMENT_REWARD_TOS.nested_types = {}
M_ACHIEVEMENT_REWARD_TOS.enum_types = {}
M_ACHIEVEMENT_REWARD_TOS.fields = {M_ACHIEVEMENT_REWARD_TOS_ACHIEVEMENT_ID_FIELD}
M_ACHIEVEMENT_REWARD_TOS.is_extendable = false
M_ACHIEVEMENT_REWARD_TOS.extensions = {}

m_achievement_reward_tos = protobuf.Message(M_ACHIEVEMENT_REWARD_TOS)

