--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_act_rank_info_tos_pb')

M_ACT_RANK_INFO_TOS = protobuf.Descriptor();
M_ACT_RANK_INFO_TOS_ID_FIELD = protobuf.FieldDescriptor();

M_ACT_RANK_INFO_TOS_ID_FIELD.name = "id"
M_ACT_RANK_INFO_TOS_ID_FIELD.full_name = ".m_act_rank_info_tos.id"
M_ACT_RANK_INFO_TOS_ID_FIELD.number = 1
M_ACT_RANK_INFO_TOS_ID_FIELD.index = 0
M_ACT_RANK_INFO_TOS_ID_FIELD.label = 1
M_ACT_RANK_INFO_TOS_ID_FIELD.has_default_value = true
M_ACT_RANK_INFO_TOS_ID_FIELD.default_value = 0
M_ACT_RANK_INFO_TOS_ID_FIELD.type = 5
M_ACT_RANK_INFO_TOS_ID_FIELD.cpp_type = 1

M_ACT_RANK_INFO_TOS.name = "m_act_rank_info_tos"
M_ACT_RANK_INFO_TOS.full_name = ".m_act_rank_info_tos"
M_ACT_RANK_INFO_TOS.nested_types = {}
M_ACT_RANK_INFO_TOS.enum_types = {}
M_ACT_RANK_INFO_TOS.fields = {M_ACT_RANK_INFO_TOS_ID_FIELD}
M_ACT_RANK_INFO_TOS.is_extendable = false
M_ACT_RANK_INFO_TOS.extensions = {}

m_act_rank_info_tos = protobuf.Message(M_ACT_RANK_INFO_TOS)

