--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_act_limitedtime_buy_round_toc_pb')

M_ACT_LIMITEDTIME_BUY_ROUND_TOC = protobuf.Descriptor();
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD = protobuf.FieldDescriptor();

M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.name = "stage"
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.full_name = ".m_act_limitedtime_buy_round_toc.stage"
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.number = 1
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.index = 0
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.label = 1
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.has_default_value = true
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.default_value = 0
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.type = 5
M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD.cpp_type = 1

M_ACT_LIMITEDTIME_BUY_ROUND_TOC.name = "m_act_limitedtime_buy_round_toc"
M_ACT_LIMITEDTIME_BUY_ROUND_TOC.full_name = ".m_act_limitedtime_buy_round_toc"
M_ACT_LIMITEDTIME_BUY_ROUND_TOC.nested_types = {}
M_ACT_LIMITEDTIME_BUY_ROUND_TOC.enum_types = {}
M_ACT_LIMITEDTIME_BUY_ROUND_TOC.fields = {M_ACT_LIMITEDTIME_BUY_ROUND_TOC_STAGE_FIELD}
M_ACT_LIMITEDTIME_BUY_ROUND_TOC.is_extendable = false
M_ACT_LIMITEDTIME_BUY_ROUND_TOC.extensions = {}

m_act_limitedtime_buy_round_toc = protobuf.Message(M_ACT_LIMITEDTIME_BUY_ROUND_TOC)

