--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_answer_res_toc_pb')

M_ANSWER_RES_TOC = protobuf.Descriptor();
M_ANSWER_RES_TOC_RES_FIELD = protobuf.FieldDescriptor();
M_ANSWER_RES_TOC_ANSWER_RES_FIELD = protobuf.FieldDescriptor();

M_ANSWER_RES_TOC_RES_FIELD.name = "res"
M_ANSWER_RES_TOC_RES_FIELD.full_name = ".m_answer_res_toc.res"
M_ANSWER_RES_TOC_RES_FIELD.number = 1
M_ANSWER_RES_TOC_RES_FIELD.index = 0
M_ANSWER_RES_TOC_RES_FIELD.label = 1
M_ANSWER_RES_TOC_RES_FIELD.has_default_value = true
M_ANSWER_RES_TOC_RES_FIELD.default_value = 0
M_ANSWER_RES_TOC_RES_FIELD.type = 5
M_ANSWER_RES_TOC_RES_FIELD.cpp_type = 1

M_ANSWER_RES_TOC_ANSWER_RES_FIELD.name = "answer_res"
M_ANSWER_RES_TOC_ANSWER_RES_FIELD.full_name = ".m_answer_res_toc.answer_res"
M_ANSWER_RES_TOC_ANSWER_RES_FIELD.number = 2
M_ANSWER_RES_TOC_ANSWER_RES_FIELD.index = 1
M_ANSWER_RES_TOC_ANSWER_RES_FIELD.label = 1
M_ANSWER_RES_TOC_ANSWER_RES_FIELD.has_default_value = true
M_ANSWER_RES_TOC_ANSWER_RES_FIELD.default_value = 0
M_ANSWER_RES_TOC_ANSWER_RES_FIELD.type = 5
M_ANSWER_RES_TOC_ANSWER_RES_FIELD.cpp_type = 1

M_ANSWER_RES_TOC.name = "m_answer_res_toc"
M_ANSWER_RES_TOC.full_name = ".m_answer_res_toc"
M_ANSWER_RES_TOC.nested_types = {}
M_ANSWER_RES_TOC.enum_types = {}
M_ANSWER_RES_TOC.fields = {M_ANSWER_RES_TOC_RES_FIELD, M_ANSWER_RES_TOC_ANSWER_RES_FIELD}
M_ANSWER_RES_TOC.is_extendable = false
M_ANSWER_RES_TOC.extensions = {}

m_answer_res_toc = protobuf.Message(M_ANSWER_RES_TOC)

