--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_answer_attack_toc_pb')

M_ANSWER_ATTACK_TOC = protobuf.Descriptor();
M_ANSWER_ATTACK_TOC_SKILL_FIELD = protobuf.FieldDescriptor();

M_ANSWER_ATTACK_TOC_SKILL_FIELD.name = "skill"
M_ANSWER_ATTACK_TOC_SKILL_FIELD.full_name = ".m_answer_attack_toc.skill"
M_ANSWER_ATTACK_TOC_SKILL_FIELD.number = 1
M_ANSWER_ATTACK_TOC_SKILL_FIELD.index = 0
M_ANSWER_ATTACK_TOC_SKILL_FIELD.label = 1
M_ANSWER_ATTACK_TOC_SKILL_FIELD.has_default_value = true
M_ANSWER_ATTACK_TOC_SKILL_FIELD.default_value = 0
M_ANSWER_ATTACK_TOC_SKILL_FIELD.type = 5
M_ANSWER_ATTACK_TOC_SKILL_FIELD.cpp_type = 1

M_ANSWER_ATTACK_TOC.name = "m_answer_attack_toc"
M_ANSWER_ATTACK_TOC.full_name = ".m_answer_attack_toc"
M_ANSWER_ATTACK_TOC.nested_types = {}
M_ANSWER_ATTACK_TOC.enum_types = {}
M_ANSWER_ATTACK_TOC.fields = {M_ANSWER_ATTACK_TOC_SKILL_FIELD}
M_ANSWER_ATTACK_TOC.is_extendable = false
M_ANSWER_ATTACK_TOC.extensions = {}

m_answer_attack_toc = protobuf.Message(M_ANSWER_ATTACK_TOC)

