--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_auction_goods_pb = require("Protol.p_auction_goods_pb")
module('Protol.m_auction_panel_update_toc_pb')

M_AUCTION_PANEL_UPDATE_TOC = protobuf.Descriptor();
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD = protobuf.FieldDescriptor();

M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.name = "update_goods"
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.full_name = ".m_auction_panel_update_toc.update_goods"
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.number = 1
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.index = 0
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.label = 1
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.has_default_value = false
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.default_value = nil
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.message_type = p_auction_goods_pb.P_AUCTION_GOODS
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.type = 11
M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD.cpp_type = 10

M_AUCTION_PANEL_UPDATE_TOC.name = "m_auction_panel_update_toc"
M_AUCTION_PANEL_UPDATE_TOC.full_name = ".m_auction_panel_update_toc"
M_AUCTION_PANEL_UPDATE_TOC.nested_types = {}
M_AUCTION_PANEL_UPDATE_TOC.enum_types = {}
M_AUCTION_PANEL_UPDATE_TOC.fields = {M_AUCTION_PANEL_UPDATE_TOC_UPDATE_GOODS_FIELD}
M_AUCTION_PANEL_UPDATE_TOC.is_extendable = false
M_AUCTION_PANEL_UPDATE_TOC.extensions = {}

m_auction_panel_update_toc = protobuf.Message(M_AUCTION_PANEL_UPDATE_TOC)

