--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_auction_class_tos_pb')

M_AUCTION_CLASS_TOS = protobuf.Descriptor();
M_AUCTION_CLASS_TOS_CLASS_FIELD = protobuf.FieldDescriptor();

M_AUCTION_CLASS_TOS_CLASS_FIELD.name = "class"
M_AUCTION_CLASS_TOS_CLASS_FIELD.full_name = ".m_auction_class_tos.class"
M_AUCTION_CLASS_TOS_CLASS_FIELD.number = 1
M_AUCTION_CLASS_TOS_CLASS_FIELD.index = 0
M_AUCTION_CLASS_TOS_CLASS_FIELD.label = 1
M_AUCTION_CLASS_TOS_CLASS_FIELD.has_default_value = true
M_AUCTION_CLASS_TOS_CLASS_FIELD.default_value = 0
M_AUCTION_CLASS_TOS_CLASS_FIELD.type = 5
M_AUCTION_CLASS_TOS_CLASS_FIELD.cpp_type = 1

M_AUCTION_CLASS_TOS.name = "m_auction_class_tos"
M_AUCTION_CLASS_TOS.full_name = ".m_auction_class_tos"
M_AUCTION_CLASS_TOS.nested_types = {}
M_AUCTION_CLASS_TOS.enum_types = {}
M_AUCTION_CLASS_TOS.fields = {M_AUCTION_CLASS_TOS_CLASS_FIELD}
M_AUCTION_CLASS_TOS.is_extendable = false
M_AUCTION_CLASS_TOS.extensions = {}

m_auction_class_tos = protobuf.Message(M_AUCTION_CLASS_TOS)

