--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_auction_care_toc_pb')

M_AUCTION_CARE_TOC = protobuf.Descriptor();
M_AUCTION_CARE_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_AUCTION_CARE_TOC_TYPE_FIELD = protobuf.FieldDescriptor();
M_AUCTION_CARE_TOC_TYPE_ID_FIELD = protobuf.FieldDescriptor();

M_AUCTION_CARE_TOC_ERR_CODE_FIELD.name = "err_code"
M_AUCTION_CARE_TOC_ERR_CODE_FIELD.full_name = ".m_auction_care_toc.err_code"
M_AUCTION_CARE_TOC_ERR_CODE_FIELD.number = 1
M_AUCTION_CARE_TOC_ERR_CODE_FIELD.index = 0
M_AUCTION_CARE_TOC_ERR_CODE_FIELD.label = 1
M_AUCTION_CARE_TOC_ERR_CODE_FIELD.has_default_value = true
M_AUCTION_CARE_TOC_ERR_CODE_FIELD.default_value = 0
M_AUCTION_CARE_TOC_ERR_CODE_FIELD.type = 5
M_AUCTION_CARE_TOC_ERR_CODE_FIELD.cpp_type = 1

M_AUCTION_CARE_TOC_TYPE_FIELD.name = "type"
M_AUCTION_CARE_TOC_TYPE_FIELD.full_name = ".m_auction_care_toc.type"
M_AUCTION_CARE_TOC_TYPE_FIELD.number = 2
M_AUCTION_CARE_TOC_TYPE_FIELD.index = 1
M_AUCTION_CARE_TOC_TYPE_FIELD.label = 1
M_AUCTION_CARE_TOC_TYPE_FIELD.has_default_value = true
M_AUCTION_CARE_TOC_TYPE_FIELD.default_value = 0
M_AUCTION_CARE_TOC_TYPE_FIELD.type = 5
M_AUCTION_CARE_TOC_TYPE_FIELD.cpp_type = 1

M_AUCTION_CARE_TOC_TYPE_ID_FIELD.name = "type_id"
M_AUCTION_CARE_TOC_TYPE_ID_FIELD.full_name = ".m_auction_care_toc.type_id"
M_AUCTION_CARE_TOC_TYPE_ID_FIELD.number = 3
M_AUCTION_CARE_TOC_TYPE_ID_FIELD.index = 2
M_AUCTION_CARE_TOC_TYPE_ID_FIELD.label = 1
M_AUCTION_CARE_TOC_TYPE_ID_FIELD.has_default_value = true
M_AUCTION_CARE_TOC_TYPE_ID_FIELD.default_value = 0
M_AUCTION_CARE_TOC_TYPE_ID_FIELD.type = 5
M_AUCTION_CARE_TOC_TYPE_ID_FIELD.cpp_type = 1

M_AUCTION_CARE_TOC.name = "m_auction_care_toc"
M_AUCTION_CARE_TOC.full_name = ".m_auction_care_toc"
M_AUCTION_CARE_TOC.nested_types = {}
M_AUCTION_CARE_TOC.enum_types = {}
M_AUCTION_CARE_TOC.fields = {M_AUCTION_CARE_TOC_ERR_CODE_FIELD, M_AUCTION_CARE_TOC_TYPE_FIELD, M_AUCTION_CARE_TOC_TYPE_ID_FIELD}
M_AUCTION_CARE_TOC.is_extendable = false
M_AUCTION_CARE_TOC.extensions = {}

m_auction_care_toc = protobuf.Message(M_AUCTION_CARE_TOC)

