--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_bag_all_depot_tos_pb')

M_BAG_ALL_DEPOT_TOS = protobuf.Descriptor();
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD = protobuf.FieldDescriptor();

M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.name = "bag_id"
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.full_name = ".m_bag_all_depot_tos.bag_id"
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.number = 1
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.index = 0
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.label = 1
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.has_default_value = true
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.default_value = 0
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.type = 5
M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD.cpp_type = 1

M_BAG_ALL_DEPOT_TOS.name = "m_bag_all_depot_tos"
M_BAG_ALL_DEPOT_TOS.full_name = ".m_bag_all_depot_tos"
M_BAG_ALL_DEPOT_TOS.nested_types = {}
M_BAG_ALL_DEPOT_TOS.enum_types = {}
M_BAG_ALL_DEPOT_TOS.fields = {M_BAG_ALL_DEPOT_TOS_BAG_ID_FIELD}
M_BAG_ALL_DEPOT_TOS.is_extendable = false
M_BAG_ALL_DEPOT_TOS.extensions = {}

m_bag_all_depot_tos = protobuf.Message(M_BAG_ALL_DEPOT_TOS)

