--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_bag_content_pb = require("Protol.p_bag_content_pb")
module('Protol.m_bag_info_toc_pb')

M_BAG_INFO_TOC = protobuf.Descriptor();
M_BAG_INFO_TOC_BAG_LIST_FIELD = protobuf.FieldDescriptor();

M_BAG_INFO_TOC_BAG_LIST_FIELD.name = "bag_list"
M_BAG_INFO_TOC_BAG_LIST_FIELD.full_name = ".m_bag_info_toc.bag_list"
M_BAG_INFO_TOC_BAG_LIST_FIELD.number = 1
M_BAG_INFO_TOC_BAG_LIST_FIELD.index = 0
M_BAG_INFO_TOC_BAG_LIST_FIELD.label = 3
M_BAG_INFO_TOC_BAG_LIST_FIELD.has_default_value = false
M_BAG_INFO_TOC_BAG_LIST_FIELD.default_value = {}
M_BAG_INFO_TOC_BAG_LIST_FIELD.message_type = p_bag_content_pb.P_BAG_CONTENT
M_BAG_INFO_TOC_BAG_LIST_FIELD.type = 11
M_BAG_INFO_TOC_BAG_LIST_FIELD.cpp_type = 10

M_BAG_INFO_TOC.name = "m_bag_info_toc"
M_BAG_INFO_TOC.full_name = ".m_bag_info_toc"
M_BAG_INFO_TOC.nested_types = {}
M_BAG_INFO_TOC.enum_types = {}
M_BAG_INFO_TOC.fields = {M_BAG_INFO_TOC_BAG_LIST_FIELD}
M_BAG_INFO_TOC.is_extendable = false
M_BAG_INFO_TOC.extensions = {}

m_bag_info_toc = protobuf.Message(M_BAG_INFO_TOC)

