--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_bg_act_update_a_toc_pb')

M_BG_ACT_UPDATE_A_TOC = protobuf.Descriptor();
M_BG_ACT_UPDATE_A_TOC_ID_FIELD = protobuf.FieldDescriptor();
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD = protobuf.FieldDescriptor();

M_BG_ACT_UPDATE_A_TOC_ID_FIELD.name = "id"
M_BG_ACT_UPDATE_A_TOC_ID_FIELD.full_name = ".m_bg_act_update_a_toc.id"
M_BG_ACT_UPDATE_A_TOC_ID_FIELD.number = 1
M_BG_ACT_UPDATE_A_TOC_ID_FIELD.index = 0
M_BG_ACT_UPDATE_A_TOC_ID_FIELD.label = 1
M_BG_ACT_UPDATE_A_TOC_ID_FIELD.has_default_value = true
M_BG_ACT_UPDATE_A_TOC_ID_FIELD.default_value = 0
M_BG_ACT_UPDATE_A_TOC_ID_FIELD.type = 5
M_BG_ACT_UPDATE_A_TOC_ID_FIELD.cpp_type = 1

M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.name = "val"
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.full_name = ".m_bg_act_update_a_toc.val"
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.number = 2
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.index = 1
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.label = 1
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.has_default_value = true
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.default_value = 0
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.type = 5
M_BG_ACT_UPDATE_A_TOC_VAL_FIELD.cpp_type = 1

M_BG_ACT_UPDATE_A_TOC.name = "m_bg_act_update_a_toc"
M_BG_ACT_UPDATE_A_TOC.full_name = ".m_bg_act_update_a_toc"
M_BG_ACT_UPDATE_A_TOC.nested_types = {}
M_BG_ACT_UPDATE_A_TOC.enum_types = {}
M_BG_ACT_UPDATE_A_TOC.fields = {M_BG_ACT_UPDATE_A_TOC_ID_FIELD, M_BG_ACT_UPDATE_A_TOC_VAL_FIELD}
M_BG_ACT_UPDATE_A_TOC.is_extendable = false
M_BG_ACT_UPDATE_A_TOC.extensions = {}

m_bg_act_update_a_toc = protobuf.Message(M_BG_ACT_UPDATE_A_TOC)

