--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_bg_act_close_toc_pb')

M_BG_ACT_CLOSE_TOC = protobuf.Descriptor();
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD = protobuf.FieldDescriptor();

M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.name = "act_id"
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.full_name = ".m_bg_act_close_toc.act_id"
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.number = 1
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.index = 0
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.label = 1
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.has_default_value = true
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.default_value = 0
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.type = 5
M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD.cpp_type = 1

M_BG_ACT_CLOSE_TOC.name = "m_bg_act_close_toc"
M_BG_ACT_CLOSE_TOC.full_name = ".m_bg_act_close_toc"
M_BG_ACT_CLOSE_TOC.nested_types = {}
M_BG_ACT_CLOSE_TOC.enum_types = {}
M_BG_ACT_CLOSE_TOC.fields = {M_BG_ACT_CLOSE_TOC_ACT_ID_FIELD}
M_BG_ACT_CLOSE_TOC.is_extendable = false
M_BG_ACT_CLOSE_TOC.extensions = {}

m_bg_act_close_toc = protobuf.Message(M_BG_ACT_CLOSE_TOC)

