--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_bg_act_pb = require("Protol.p_bg_act_pb")
module('Protol.m_bg_store_toc_pb')

M_BG_STORE_TOC = protobuf.Descriptor();
M_BG_STORE_TOC_INFO_FIELD = protobuf.FieldDescriptor();
M_BG_STORE_TOC_ITEM_FIELD = protobuf.FieldDescriptor();

M_BG_STORE_TOC_INFO_FIELD.name = "info"
M_BG_STORE_TOC_INFO_FIELD.full_name = ".m_bg_store_toc.info"
M_BG_STORE_TOC_INFO_FIELD.number = 1
M_BG_STORE_TOC_INFO_FIELD.index = 0
M_BG_STORE_TOC_INFO_FIELD.label = 1
M_BG_STORE_TOC_INFO_FIELD.has_default_value = false
M_BG_STORE_TOC_INFO_FIELD.default_value = nil
M_BG_STORE_TOC_INFO_FIELD.message_type = p_bg_act_pb.P_BG_ACT
M_BG_STORE_TOC_INFO_FIELD.type = 11
M_BG_STORE_TOC_INFO_FIELD.cpp_type = 10

M_BG_STORE_TOC_ITEM_FIELD.name = "item"
M_BG_STORE_TOC_ITEM_FIELD.full_name = ".m_bg_store_toc.item"
M_BG_STORE_TOC_ITEM_FIELD.number = 2
M_BG_STORE_TOC_ITEM_FIELD.index = 1
M_BG_STORE_TOC_ITEM_FIELD.label = 1
M_BG_STORE_TOC_ITEM_FIELD.has_default_value = true
M_BG_STORE_TOC_ITEM_FIELD.default_value = 0
M_BG_STORE_TOC_ITEM_FIELD.type = 5
M_BG_STORE_TOC_ITEM_FIELD.cpp_type = 1

M_BG_STORE_TOC.name = "m_bg_store_toc"
M_BG_STORE_TOC.full_name = ".m_bg_store_toc"
M_BG_STORE_TOC.nested_types = {}
M_BG_STORE_TOC.enum_types = {}
M_BG_STORE_TOC.fields = {M_BG_STORE_TOC_INFO_FIELD, M_BG_STORE_TOC_ITEM_FIELD}
M_BG_STORE_TOC.is_extendable = false
M_BG_STORE_TOC.extensions = {}

m_bg_store_toc = protobuf.Message(M_BG_STORE_TOC)

