--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_bg_act_reward_num_tos_pb')

M_BG_ACT_REWARD_NUM_TOS = protobuf.Descriptor();
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD = protobuf.FieldDescriptor();

M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.name = "id"
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.full_name = ".m_bg_act_reward_num_tos.id"
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.number = 1
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.index = 0
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.label = 1
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.has_default_value = true
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.default_value = 0
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.type = 5
M_BG_ACT_REWARD_NUM_TOS_ID_FIELD.cpp_type = 1

M_BG_ACT_REWARD_NUM_TOS.name = "m_bg_act_reward_num_tos"
M_BG_ACT_REWARD_NUM_TOS.full_name = ".m_bg_act_reward_num_tos"
M_BG_ACT_REWARD_NUM_TOS.nested_types = {}
M_BG_ACT_REWARD_NUM_TOS.enum_types = {}
M_BG_ACT_REWARD_NUM_TOS.fields = {M_BG_ACT_REWARD_NUM_TOS_ID_FIELD}
M_BG_ACT_REWARD_NUM_TOS.is_extendable = false
M_BG_ACT_REWARD_NUM_TOS.extensions = {}

m_bg_act_reward_num_tos = protobuf.Message(M_BG_ACT_REWARD_NUM_TOS)

