--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_bg_act_reward_num_toc_pb')

M_BG_ACT_REWARD_NUM_TOC = protobuf.Descriptor();
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD = protobuf.FieldDescriptor();
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD = protobuf.FieldDescriptor();

M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.name = "id"
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.full_name = ".m_bg_act_reward_num_toc.id"
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.number = 1
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.index = 0
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.label = 1
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.has_default_value = true
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.default_value = 0
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.type = 5
M_BG_ACT_REWARD_NUM_TOC_ID_FIELD.cpp_type = 1

M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.name = "list"
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.full_name = ".m_bg_act_reward_num_toc.list"
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.number = 2
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.index = 1
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.label = 3
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.has_default_value = false
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.default_value = {}
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.message_type = p_kv_pb.P_KV
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.type = 11
M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD.cpp_type = 10

M_BG_ACT_REWARD_NUM_TOC.name = "m_bg_act_reward_num_toc"
M_BG_ACT_REWARD_NUM_TOC.full_name = ".m_bg_act_reward_num_toc"
M_BG_ACT_REWARD_NUM_TOC.nested_types = {}
M_BG_ACT_REWARD_NUM_TOC.enum_types = {}
M_BG_ACT_REWARD_NUM_TOC.fields = {M_BG_ACT_REWARD_NUM_TOC_ID_FIELD, M_BG_ACT_REWARD_NUM_TOC_LIST_FIELD}
M_BG_ACT_REWARD_NUM_TOC.is_extendable = false
M_BG_ACT_REWARD_NUM_TOC.extensions = {}

m_bg_act_reward_num_toc = protobuf.Message(M_BG_ACT_REWARD_NUM_TOC)

