--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_boss_reward_toc_pb')

M_BOSS_REWARD_TOC = protobuf.Descriptor();
M_BOSS_REWARD_TOC_GRADE_FIELD = protobuf.FieldDescriptor();
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD = protobuf.FieldDescriptor();
M_BOSS_REWARD_TOC_KILL_NUM_FIELD = protobuf.FieldDescriptor();

M_BOSS_REWARD_TOC_GRADE_FIELD.name = "grade"
M_BOSS_REWARD_TOC_GRADE_FIELD.full_name = ".m_boss_reward_toc.grade"
M_BOSS_REWARD_TOC_GRADE_FIELD.number = 1
M_BOSS_REWARD_TOC_GRADE_FIELD.index = 0
M_BOSS_REWARD_TOC_GRADE_FIELD.label = 1
M_BOSS_REWARD_TOC_GRADE_FIELD.has_default_value = true
M_BOSS_REWARD_TOC_GRADE_FIELD.default_value = 0
M_BOSS_REWARD_TOC_GRADE_FIELD.type = 5
M_BOSS_REWARD_TOC_GRADE_FIELD.cpp_type = 1

M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.name = "got_reward"
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.full_name = ".m_boss_reward_toc.got_reward"
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.number = 2
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.index = 1
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.label = 1
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.has_default_value = true
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.default_value = 0
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.type = 5
M_BOSS_REWARD_TOC_GOT_REWARD_FIELD.cpp_type = 1

M_BOSS_REWARD_TOC_KILL_NUM_FIELD.name = "kill_num"
M_BOSS_REWARD_TOC_KILL_NUM_FIELD.full_name = ".m_boss_reward_toc.kill_num"
M_BOSS_REWARD_TOC_KILL_NUM_FIELD.number = 3
M_BOSS_REWARD_TOC_KILL_NUM_FIELD.index = 2
M_BOSS_REWARD_TOC_KILL_NUM_FIELD.label = 1
M_BOSS_REWARD_TOC_KILL_NUM_FIELD.has_default_value = true
M_BOSS_REWARD_TOC_KILL_NUM_FIELD.default_value = 0
M_BOSS_REWARD_TOC_KILL_NUM_FIELD.type = 5
M_BOSS_REWARD_TOC_KILL_NUM_FIELD.cpp_type = 1

M_BOSS_REWARD_TOC.name = "m_boss_reward_toc"
M_BOSS_REWARD_TOC.full_name = ".m_boss_reward_toc"
M_BOSS_REWARD_TOC.nested_types = {}
M_BOSS_REWARD_TOC.enum_types = {}
M_BOSS_REWARD_TOC.fields = {M_BOSS_REWARD_TOC_GRADE_FIELD, M_BOSS_REWARD_TOC_GOT_REWARD_FIELD, M_BOSS_REWARD_TOC_KILL_NUM_FIELD}
M_BOSS_REWARD_TOC.is_extendable = false
M_BOSS_REWARD_TOC.extensions = {}

m_boss_reward_toc = protobuf.Message(M_BOSS_REWARD_TOC)

