--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_chat_delete_top_toc_pb')

M_CHAT_DELETE_TOP_TOC = protobuf.Descriptor();

M_CHAT_DELETE_TOP_TOC.name = "m_chat_delete_top_toc"
M_CHAT_DELETE_TOP_TOC.full_name = ".m_chat_delete_top_toc"
M_CHAT_DELETE_TOP_TOC.nested_types = {}
M_CHAT_DELETE_TOP_TOC.enum_types = {}
M_CHAT_DELETE_TOP_TOC.fields = {}
M_CHAT_DELETE_TOP_TOC.is_extendable = false
M_CHAT_DELETE_TOP_TOC.extensions = {}

m_chat_delete_top_toc = protobuf.Message(M_CHAT_DELETE_TOP_TOC)

