--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_copy_cheer_tos_pb')

M_COPY_CHEER_TOS = protobuf.Descriptor();
M_COPY_CHEER_TOS_ID_FIELD = protobuf.FieldDescriptor();
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD = protobuf.FieldDescriptor();

M_COPY_CHEER_TOS_ID_FIELD.name = "id"
M_COPY_CHEER_TOS_ID_FIELD.full_name = ".m_copy_cheer_tos.id"
M_COPY_CHEER_TOS_ID_FIELD.number = 1
M_COPY_CHEER_TOS_ID_FIELD.index = 0
M_COPY_CHEER_TOS_ID_FIELD.label = 1
M_COPY_CHEER_TOS_ID_FIELD.has_default_value = true
M_COPY_CHEER_TOS_ID_FIELD.default_value = 0
M_COPY_CHEER_TOS_ID_FIELD.type = 5
M_COPY_CHEER_TOS_ID_FIELD.cpp_type = 1

M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.name = "asset_type"
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.full_name = ".m_copy_cheer_tos.asset_type"
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.number = 2
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.index = 1
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.label = 1
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.has_default_value = true
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.default_value = 0
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.type = 5
M_COPY_CHEER_TOS_ASSET_TYPE_FIELD.cpp_type = 1

M_COPY_CHEER_TOS.name = "m_copy_cheer_tos"
M_COPY_CHEER_TOS.full_name = ".m_copy_cheer_tos"
M_COPY_CHEER_TOS.nested_types = {}
M_COPY_CHEER_TOS.enum_types = {}
M_COPY_CHEER_TOS.fields = {M_COPY_CHEER_TOS_ID_FIELD, M_COPY_CHEER_TOS_ASSET_TYPE_FIELD}
M_COPY_CHEER_TOS.is_extendable = false
M_COPY_CHEER_TOS.extensions = {}

m_copy_cheer_tos = protobuf.Message(M_COPY_CHEER_TOS)

