--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_copy_cd_remove_tos_pb')

M_COPY_CD_REMOVE_TOS = protobuf.Descriptor();
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD = protobuf.FieldDescriptor();

M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.name = "copy_id"
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.full_name = ".m_copy_cd_remove_tos.copy_id"
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.number = 1
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.index = 0
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.label = 1
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.has_default_value = true
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.default_value = 0
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.type = 5
M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD.cpp_type = 1

M_COPY_CD_REMOVE_TOS.name = "m_copy_cd_remove_tos"
M_COPY_CD_REMOVE_TOS.full_name = ".m_copy_cd_remove_tos"
M_COPY_CD_REMOVE_TOS.nested_types = {}
M_COPY_CD_REMOVE_TOS.enum_types = {}
M_COPY_CD_REMOVE_TOS.fields = {M_COPY_CD_REMOVE_TOS_COPY_ID_FIELD}
M_COPY_CD_REMOVE_TOS.is_extendable = false
M_COPY_CD_REMOVE_TOS.extensions = {}

m_copy_cd_remove_tos = protobuf.Message(M_COPY_CD_REMOVE_TOS)

