--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_confine_up_toc_pb')

M_CONFINE_UP_TOC = protobuf.Descriptor();
M_CONFINE_UP_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_CONFINE_UP_TOC_CONFINE_FIELD = protobuf.FieldDescriptor();

M_CONFINE_UP_TOC_ERR_CODE_FIELD.name = "err_code"
M_CONFINE_UP_TOC_ERR_CODE_FIELD.full_name = ".m_confine_up_toc.err_code"
M_CONFINE_UP_TOC_ERR_CODE_FIELD.number = 1
M_CONFINE_UP_TOC_ERR_CODE_FIELD.index = 0
M_CONFINE_UP_TOC_ERR_CODE_FIELD.label = 1
M_CONFINE_UP_TOC_ERR_CODE_FIELD.has_default_value = true
M_CONFINE_UP_TOC_ERR_CODE_FIELD.default_value = 0
M_CONFINE_UP_TOC_ERR_CODE_FIELD.type = 5
M_CONFINE_UP_TOC_ERR_CODE_FIELD.cpp_type = 1

M_CONFINE_UP_TOC_CONFINE_FIELD.name = "confine"
M_CONFINE_UP_TOC_CONFINE_FIELD.full_name = ".m_confine_up_toc.confine"
M_CONFINE_UP_TOC_CONFINE_FIELD.number = 2
M_CONFINE_UP_TOC_CONFINE_FIELD.index = 1
M_CONFINE_UP_TOC_CONFINE_FIELD.label = 1
M_CONFINE_UP_TOC_CONFINE_FIELD.has_default_value = true
M_CONFINE_UP_TOC_CONFINE_FIELD.default_value = 0
M_CONFINE_UP_TOC_CONFINE_FIELD.type = 5
M_CONFINE_UP_TOC_CONFINE_FIELD.cpp_type = 1

M_CONFINE_UP_TOC.name = "m_confine_up_toc"
M_CONFINE_UP_TOC.full_name = ".m_confine_up_toc"
M_CONFINE_UP_TOC.nested_types = {}
M_CONFINE_UP_TOC.enum_types = {}
M_CONFINE_UP_TOC.fields = {M_CONFINE_UP_TOC_ERR_CODE_FIELD, M_CONFINE_UP_TOC_CONFINE_FIELD}
M_CONFINE_UP_TOC.is_extendable = false
M_CONFINE_UP_TOC.extensions = {}

m_confine_up_toc = protobuf.Message(M_CONFINE_UP_TOC)

