--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_copy_cd_remove_toc_pb')

M_COPY_CD_REMOVE_TOC = protobuf.Descriptor();
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();

M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.name = "err_code"
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.full_name = ".m_copy_cd_remove_toc.err_code"
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.number = 1
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.index = 0
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.label = 1
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.has_default_value = true
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.default_value = 0
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.type = 5
M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD.cpp_type = 1

M_COPY_CD_REMOVE_TOC.name = "m_copy_cd_remove_toc"
M_COPY_CD_REMOVE_TOC.full_name = ".m_copy_cd_remove_toc"
M_COPY_CD_REMOVE_TOC.nested_types = {}
M_COPY_CD_REMOVE_TOC.enum_types = {}
M_COPY_CD_REMOVE_TOC.fields = {M_COPY_CD_REMOVE_TOC_ERR_CODE_FIELD}
M_COPY_CD_REMOVE_TOC.is_extendable = false
M_COPY_CD_REMOVE_TOC.extensions = {}

m_copy_cd_remove_toc = protobuf.Message(M_COPY_CD_REMOVE_TOC)

