--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_copy_first_past_toc_pb')

M_COPY_FIRST_PAST_TOC = protobuf.Descriptor();
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD = protobuf.FieldDescriptor();

M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.name = "copy_type"
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.full_name = ".m_copy_first_past_toc.copy_type"
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.number = 1
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.index = 0
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.label = 1
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.has_default_value = true
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.default_value = 0
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.type = 5
M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD.cpp_type = 1

M_COPY_FIRST_PAST_TOC.name = "m_copy_first_past_toc"
M_COPY_FIRST_PAST_TOC.full_name = ".m_copy_first_past_toc"
M_COPY_FIRST_PAST_TOC.nested_types = {}
M_COPY_FIRST_PAST_TOC.enum_types = {}
M_COPY_FIRST_PAST_TOC.fields = {M_COPY_FIRST_PAST_TOC_COPY_TYPE_FIELD}
M_COPY_FIRST_PAST_TOC.is_extendable = false
M_COPY_FIRST_PAST_TOC.extensions = {}

m_copy_first_past_toc = protobuf.Message(M_COPY_FIRST_PAST_TOC)

