--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_copy_exp_merge_times_tos_pb')

M_COPY_EXP_MERGE_TIMES_TOS = protobuf.Descriptor();
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD = protobuf.FieldDescriptor();

M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.name = "merge_times"
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.full_name = ".m_copy_exp_merge_times_tos.merge_times"
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.number = 1
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.index = 0
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.label = 1
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.has_default_value = true
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.default_value = 0
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.type = 5
M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD.cpp_type = 1

M_COPY_EXP_MERGE_TIMES_TOS.name = "m_copy_exp_merge_times_tos"
M_COPY_EXP_MERGE_TIMES_TOS.full_name = ".m_copy_exp_merge_times_tos"
M_COPY_EXP_MERGE_TIMES_TOS.nested_types = {}
M_COPY_EXP_MERGE_TIMES_TOS.enum_types = {}
M_COPY_EXP_MERGE_TIMES_TOS.fields = {M_COPY_EXP_MERGE_TIMES_TOS_MERGE_TIMES_FIELD}
M_COPY_EXP_MERGE_TIMES_TOS.is_extendable = false
M_COPY_EXP_MERGE_TIMES_TOS.extensions = {}

m_copy_exp_merge_times_tos = protobuf.Message(M_COPY_EXP_MERGE_TIMES_TOS)

