--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_cycle_act_couple_pray_tos_pb')

M_CYCLE_ACT_COUPLE_PRAY_TOS = protobuf.Descriptor();
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD = protobuf.FieldDescriptor();

M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.name = "times"
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.full_name = ".m_cycle_act_couple_pray_tos.times"
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.number = 1
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.index = 0
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.label = 1
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.has_default_value = true
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.default_value = 0
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.type = 5
M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD.cpp_type = 1

M_CYCLE_ACT_COUPLE_PRAY_TOS.name = "m_cycle_act_couple_pray_tos"
M_CYCLE_ACT_COUPLE_PRAY_TOS.full_name = ".m_cycle_act_couple_pray_tos"
M_CYCLE_ACT_COUPLE_PRAY_TOS.nested_types = {}
M_CYCLE_ACT_COUPLE_PRAY_TOS.enum_types = {}
M_CYCLE_ACT_COUPLE_PRAY_TOS.fields = {M_CYCLE_ACT_COUPLE_PRAY_TOS_TIMES_FIELD}
M_CYCLE_ACT_COUPLE_PRAY_TOS.is_extendable = false
M_CYCLE_ACT_COUPLE_PRAY_TOS.extensions = {}

m_cycle_act_couple_pray_tos = protobuf.Message(M_CYCLE_ACT_COUPLE_PRAY_TOS)

