--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_cycle_tower_toc_pb')

M_CYCLE_TOWER_TOC = protobuf.Descriptor();
M_CYCLE_TOWER_TOC_LAYER_FIELD = protobuf.FieldDescriptor();
M_CYCLE_TOWER_TOC_POOL_FIELD = protobuf.FieldDescriptor();

M_CYCLE_TOWER_TOC_LAYER_FIELD.name = "layer"
M_CYCLE_TOWER_TOC_LAYER_FIELD.full_name = ".m_cycle_tower_toc.layer"
M_CYCLE_TOWER_TOC_LAYER_FIELD.number = 1
M_CYCLE_TOWER_TOC_LAYER_FIELD.index = 0
M_CYCLE_TOWER_TOC_LAYER_FIELD.label = 1
M_CYCLE_TOWER_TOC_LAYER_FIELD.has_default_value = true
M_CYCLE_TOWER_TOC_LAYER_FIELD.default_value = 0
M_CYCLE_TOWER_TOC_LAYER_FIELD.type = 5
M_CYCLE_TOWER_TOC_LAYER_FIELD.cpp_type = 1

M_CYCLE_TOWER_TOC_POOL_FIELD.name = "pool"
M_CYCLE_TOWER_TOC_POOL_FIELD.full_name = ".m_cycle_tower_toc.pool"
M_CYCLE_TOWER_TOC_POOL_FIELD.number = 2
M_CYCLE_TOWER_TOC_POOL_FIELD.index = 1
M_CYCLE_TOWER_TOC_POOL_FIELD.label = 1
M_CYCLE_TOWER_TOC_POOL_FIELD.has_default_value = true
M_CYCLE_TOWER_TOC_POOL_FIELD.default_value = 0
M_CYCLE_TOWER_TOC_POOL_FIELD.type = 5
M_CYCLE_TOWER_TOC_POOL_FIELD.cpp_type = 1

M_CYCLE_TOWER_TOC.name = "m_cycle_tower_toc"
M_CYCLE_TOWER_TOC.full_name = ".m_cycle_tower_toc"
M_CYCLE_TOWER_TOC.nested_types = {}
M_CYCLE_TOWER_TOC.enum_types = {}
M_CYCLE_TOWER_TOC.fields = {M_CYCLE_TOWER_TOC_LAYER_FIELD, M_CYCLE_TOWER_TOC_POOL_FIELD}
M_CYCLE_TOWER_TOC.is_extendable = false
M_CYCLE_TOWER_TOC.extensions = {}

m_cycle_tower_toc = protobuf.Message(M_CYCLE_TOWER_TOC)

