--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_pray_log_pb = require("Protol.p_pray_log_pb")
module('Protol.m_cycle_act_couple_pray_log_toc_pb')

M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC = protobuf.Descriptor();
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD = protobuf.FieldDescriptor();

M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.name = "add_logs"
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.full_name = ".m_cycle_act_couple_pray_log_toc.add_logs"
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.number = 1
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.index = 0
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.label = 3
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.has_default_value = false
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.default_value = {}
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.message_type = p_pray_log_pb.P_PRAY_LOG
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.type = 11
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD.cpp_type = 10

M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC.name = "m_cycle_act_couple_pray_log_toc"
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC.full_name = ".m_cycle_act_couple_pray_log_toc"
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC.nested_types = {}
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC.enum_types = {}
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC.fields = {M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC_ADD_LOGS_FIELD}
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC.is_extendable = false
M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC.extensions = {}

m_cycle_act_couple_pray_log_toc = protobuf.Message(M_CYCLE_ACT_COUPLE_PRAY_LOG_TOC)

