--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_day_target_progress_tos_pb')

M_DAY_TARGET_PROGRESS_TOS = protobuf.Descriptor();
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD = protobuf.FieldDescriptor();

M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.name = "progress"
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.full_name = ".m_day_target_progress_tos.progress"
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.number = 1
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.index = 0
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.label = 1
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.has_default_value = true
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.default_value = 0
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.type = 5
M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD.cpp_type = 1

M_DAY_TARGET_PROGRESS_TOS.name = "m_day_target_progress_tos"
M_DAY_TARGET_PROGRESS_TOS.full_name = ".m_day_target_progress_tos"
M_DAY_TARGET_PROGRESS_TOS.nested_types = {}
M_DAY_TARGET_PROGRESS_TOS.enum_types = {}
M_DAY_TARGET_PROGRESS_TOS.fields = {M_DAY_TARGET_PROGRESS_TOS_PROGRESS_FIELD}
M_DAY_TARGET_PROGRESS_TOS.is_extendable = false
M_DAY_TARGET_PROGRESS_TOS.extensions = {}

m_day_target_progress_tos = protobuf.Message(M_DAY_TARGET_PROGRESS_TOS)

