--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_demon_boss_hp_reward_tos_pb')

M_DEMON_BOSS_HP_REWARD_TOS = protobuf.Descriptor();
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD = protobuf.FieldDescriptor();

M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.name = "reward_id"
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.full_name = ".m_demon_boss_hp_reward_tos.reward_id"
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.number = 1
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.index = 0
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.label = 1
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.has_default_value = true
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.default_value = 0
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.type = 5
M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD.cpp_type = 1

M_DEMON_BOSS_HP_REWARD_TOS.name = "m_demon_boss_hp_reward_tos"
M_DEMON_BOSS_HP_REWARD_TOS.full_name = ".m_demon_boss_hp_reward_tos"
M_DEMON_BOSS_HP_REWARD_TOS.nested_types = {}
M_DEMON_BOSS_HP_REWARD_TOS.enum_types = {}
M_DEMON_BOSS_HP_REWARD_TOS.fields = {M_DEMON_BOSS_HP_REWARD_TOS_REWARD_ID_FIELD}
M_DEMON_BOSS_HP_REWARD_TOS.is_extendable = false
M_DEMON_BOSS_HP_REWARD_TOS.extensions = {}

m_demon_boss_hp_reward_tos = protobuf.Message(M_DEMON_BOSS_HP_REWARD_TOS)

