--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_demon_boss_hp_reward_toc_pb')

M_DEMON_BOSS_HP_REWARD_TOC = protobuf.Descriptor();
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD = protobuf.FieldDescriptor();

M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.name = "err_code"
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.full_name = ".m_demon_boss_hp_reward_toc.err_code"
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.number = 1
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.index = 0
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.label = 1
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.has_default_value = true
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.default_value = 0
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.type = 5
M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD.cpp_type = 1

M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.name = "hp_reward_status"
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.full_name = ".m_demon_boss_hp_reward_toc.hp_reward_status"
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.number = 2
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.index = 1
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.label = 1
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.has_default_value = false
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.default_value = nil
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.message_type = p_kv_pb.P_KV
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.type = 11
M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD.cpp_type = 10

M_DEMON_BOSS_HP_REWARD_TOC.name = "m_demon_boss_hp_reward_toc"
M_DEMON_BOSS_HP_REWARD_TOC.full_name = ".m_demon_boss_hp_reward_toc"
M_DEMON_BOSS_HP_REWARD_TOC.nested_types = {}
M_DEMON_BOSS_HP_REWARD_TOC.enum_types = {}
M_DEMON_BOSS_HP_REWARD_TOC.fields = {M_DEMON_BOSS_HP_REWARD_TOC_ERR_CODE_FIELD, M_DEMON_BOSS_HP_REWARD_TOC_HP_REWARD_STATUS_FIELD}
M_DEMON_BOSS_HP_REWARD_TOC.is_extendable = false
M_DEMON_BOSS_HP_REWARD_TOC.extensions = {}

m_demon_boss_hp_reward_toc = protobuf.Message(M_DEMON_BOSS_HP_REWARD_TOC)

