--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_equip_pb = require("Protol.p_equip_pb")
module('Protol.m_equip_info_toc_pb')

M_EQUIP_INFO_TOC = protobuf.Descriptor();
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD = protobuf.FieldDescriptor();

M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.name = "equip_list"
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.full_name = ".m_equip_info_toc.equip_list"
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.number = 1
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.index = 0
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.label = 3
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.has_default_value = false
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.default_value = {}
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.message_type = p_equip_pb.P_EQUIP
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.type = 11
M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD.cpp_type = 10

M_EQUIP_INFO_TOC.name = "m_equip_info_toc"
M_EQUIP_INFO_TOC.full_name = ".m_equip_info_toc"
M_EQUIP_INFO_TOC.nested_types = {}
M_EQUIP_INFO_TOC.enum_types = {}
M_EQUIP_INFO_TOC.fields = {M_EQUIP_INFO_TOC_EQUIP_LIST_FIELD}
M_EQUIP_INFO_TOC.is_extendable = false
M_EQUIP_INFO_TOC.extensions = {}

m_equip_info_toc = protobuf.Message(M_EQUIP_INFO_TOC)

