--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_equip_compose_tos_pb')

M_EQUIP_COMPOSE_TOS = protobuf.Descriptor();
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD = protobuf.FieldDescriptor();
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD = protobuf.FieldDescriptor();

M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.name = "equip_id"
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.full_name = ".m_equip_compose_tos.equip_id"
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.number = 1
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.index = 0
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.label = 1
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.has_default_value = true
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.default_value = 0
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.type = 5
M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD.cpp_type = 1

M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.name = "material_list"
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.full_name = ".m_equip_compose_tos.material_list"
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.number = 2
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.index = 1
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.label = 3
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.has_default_value = false
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.default_value = {}
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.type = 5
M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD.cpp_type = 1

M_EQUIP_COMPOSE_TOS.name = "m_equip_compose_tos"
M_EQUIP_COMPOSE_TOS.full_name = ".m_equip_compose_tos"
M_EQUIP_COMPOSE_TOS.nested_types = {}
M_EQUIP_COMPOSE_TOS.enum_types = {}
M_EQUIP_COMPOSE_TOS.fields = {M_EQUIP_COMPOSE_TOS_EQUIP_ID_FIELD, M_EQUIP_COMPOSE_TOS_MATERIAL_LIST_FIELD}
M_EQUIP_COMPOSE_TOS.is_extendable = false
M_EQUIP_COMPOSE_TOS.extensions = {}

m_equip_compose_tos = protobuf.Message(M_EQUIP_COMPOSE_TOS)

