--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_family_battle_salary_update_toc_pb')

M_FAMILY_BATTLE_SALARY_UPDATE_TOC = protobuf.Descriptor();

M_FAMILY_BATTLE_SALARY_UPDATE_TOC.name = "m_family_battle_salary_update_toc"
M_FAMILY_BATTLE_SALARY_UPDATE_TOC.full_name = ".m_family_battle_salary_update_toc"
M_FAMILY_BATTLE_SALARY_UPDATE_TOC.nested_types = {}
M_FAMILY_BATTLE_SALARY_UPDATE_TOC.enum_types = {}
M_FAMILY_BATTLE_SALARY_UPDATE_TOC.fields = {}
M_FAMILY_BATTLE_SALARY_UPDATE_TOC.is_extendable = false
M_FAMILY_BATTLE_SALARY_UPDATE_TOC.extensions = {}

m_family_battle_salary_update_toc = protobuf.Message(M_FAMILY_BATTLE_SALARY_UPDATE_TOC)

