--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_fairy_info_toc_pb')

M_FAIRY_INFO_TOC = protobuf.Descriptor();
M_FAIRY_INFO_TOC_TIMES_FIELD = protobuf.FieldDescriptor();
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD = protobuf.FieldDescriptor();

M_FAIRY_INFO_TOC_TIMES_FIELD.name = "times"
M_FAIRY_INFO_TOC_TIMES_FIELD.full_name = ".m_fairy_info_toc.times"
M_FAIRY_INFO_TOC_TIMES_FIELD.number = 1
M_FAIRY_INFO_TOC_TIMES_FIELD.index = 0
M_FAIRY_INFO_TOC_TIMES_FIELD.label = 1
M_FAIRY_INFO_TOC_TIMES_FIELD.has_default_value = true
M_FAIRY_INFO_TOC_TIMES_FIELD.default_value = 0
M_FAIRY_INFO_TOC_TIMES_FIELD.type = 5
M_FAIRY_INFO_TOC_TIMES_FIELD.cpp_type = 1

M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.name = "fairy_id"
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.full_name = ".m_fairy_info_toc.fairy_id"
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.number = 2
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.index = 1
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.label = 1
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.has_default_value = true
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.default_value = 0
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.type = 5
M_FAIRY_INFO_TOC_FAIRY_ID_FIELD.cpp_type = 1

M_FAIRY_INFO_TOC.name = "m_fairy_info_toc"
M_FAIRY_INFO_TOC.full_name = ".m_fairy_info_toc"
M_FAIRY_INFO_TOC.nested_types = {}
M_FAIRY_INFO_TOC.enum_types = {}
M_FAIRY_INFO_TOC.fields = {M_FAIRY_INFO_TOC_TIMES_FIELD, M_FAIRY_INFO_TOC_FAIRY_ID_FIELD}
M_FAIRY_INFO_TOC.is_extendable = false
M_FAIRY_INFO_TOC.extensions = {}

m_fairy_info_toc = protobuf.Message(M_FAIRY_INFO_TOC)

