--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_family_day_reward_tos_pb')

M_FAMILY_DAY_REWARD_TOS = protobuf.Descriptor();

M_FAMILY_DAY_REWARD_TOS.name = "m_family_day_reward_tos"
M_FAMILY_DAY_REWARD_TOS.full_name = ".m_family_day_reward_tos"
M_FAMILY_DAY_REWARD_TOS.nested_types = {}
M_FAMILY_DAY_REWARD_TOS.enum_types = {}
M_FAMILY_DAY_REWARD_TOS.fields = {}
M_FAMILY_DAY_REWARD_TOS.is_extendable = false
M_FAMILY_DAY_REWARD_TOS.extensions = {}

m_family_day_reward_tos = protobuf.Message(M_FAMILY_DAY_REWARD_TOS)

