--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_fashion_give_toc_pb')

M_FASHION_GIVE_TOC = protobuf.Descriptor();
M_FASHION_GIVE_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();

M_FASHION_GIVE_TOC_ERR_CODE_FIELD.name = "err_code"
M_FASHION_GIVE_TOC_ERR_CODE_FIELD.full_name = ".m_fashion_give_toc.err_code"
M_FASHION_GIVE_TOC_ERR_CODE_FIELD.number = 1
M_FASHION_GIVE_TOC_ERR_CODE_FIELD.index = 0
M_FASHION_GIVE_TOC_ERR_CODE_FIELD.label = 1
M_FASHION_GIVE_TOC_ERR_CODE_FIELD.has_default_value = true
M_FASHION_GIVE_TOC_ERR_CODE_FIELD.default_value = 0
M_FASHION_GIVE_TOC_ERR_CODE_FIELD.type = 5
M_FASHION_GIVE_TOC_ERR_CODE_FIELD.cpp_type = 1

M_FASHION_GIVE_TOC.name = "m_fashion_give_toc"
M_FASHION_GIVE_TOC.full_name = ".m_fashion_give_toc"
M_FASHION_GIVE_TOC.nested_types = {}
M_FASHION_GIVE_TOC.enum_types = {}
M_FASHION_GIVE_TOC.fields = {M_FASHION_GIVE_TOC_ERR_CODE_FIELD}
M_FASHION_GIVE_TOC.is_extendable = false
M_FASHION_GIVE_TOC.extensions = {}

m_fashion_give_toc = protobuf.Message(M_FASHION_GIVE_TOC)

