--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_family_td_rank_pb = require("Protol.p_family_td_rank_pb")
module('Protol.m_family_td_rank_info_toc_pb')

M_FAMILY_TD_RANK_INFO_TOC = protobuf.Descriptor();
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD = protobuf.FieldDescriptor();

M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.name = "rank_info"
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.full_name = ".m_family_td_rank_info_toc.rank_info"
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.number = 1
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.index = 0
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.label = 3
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.has_default_value = false
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.default_value = {}
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.message_type = p_family_td_rank_pb.P_FAMILY_TD_RANK
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.type = 11
M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD.cpp_type = 10

M_FAMILY_TD_RANK_INFO_TOC.name = "m_family_td_rank_info_toc"
M_FAMILY_TD_RANK_INFO_TOC.full_name = ".m_family_td_rank_info_toc"
M_FAMILY_TD_RANK_INFO_TOC.nested_types = {}
M_FAMILY_TD_RANK_INFO_TOC.enum_types = {}
M_FAMILY_TD_RANK_INFO_TOC.fields = {M_FAMILY_TD_RANK_INFO_TOC_RANK_INFO_FIELD}
M_FAMILY_TD_RANK_INFO_TOC.is_extendable = false
M_FAMILY_TD_RANK_INFO_TOC.extensions = {}

m_family_td_rank_info_toc = protobuf.Message(M_FAMILY_TD_RANK_INFO_TOC)

