--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kvt_pb = require("Protol.p_kvt_pb")
module('Protol.m_family_battle_score_toc_pb')

M_FAMILY_BATTLE_SCORE_TOC = protobuf.Descriptor();
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD = protobuf.FieldDescriptor();

M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.name = "list"
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.full_name = ".m_family_battle_score_toc.list"
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.number = 1
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.index = 0
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.label = 3
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.has_default_value = false
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.default_value = {}
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.message_type = p_kvt_pb.P_KVT
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.type = 11
M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD.cpp_type = 10

M_FAMILY_BATTLE_SCORE_TOC.name = "m_family_battle_score_toc"
M_FAMILY_BATTLE_SCORE_TOC.full_name = ".m_family_battle_score_toc"
M_FAMILY_BATTLE_SCORE_TOC.nested_types = {}
M_FAMILY_BATTLE_SCORE_TOC.enum_types = {}
M_FAMILY_BATTLE_SCORE_TOC.fields = {M_FAMILY_BATTLE_SCORE_TOC_LIST_FIELD}
M_FAMILY_BATTLE_SCORE_TOC.is_extendable = false
M_FAMILY_BATTLE_SCORE_TOC.extensions = {}

m_family_battle_score_toc = protobuf.Message(M_FAMILY_BATTLE_SCORE_TOC)

