--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_family_boss_times_update_toc_pb')

M_FAMILY_BOSS_TIMES_UPDATE_TOC = protobuf.Descriptor();
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD = protobuf.FieldDescriptor();

M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.name = "times"
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.full_name = ".m_family_boss_times_update_toc.times"
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.number = 1
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.index = 0
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.label = 1
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.has_default_value = true
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.default_value = 0
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.type = 5
M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD.cpp_type = 1

M_FAMILY_BOSS_TIMES_UPDATE_TOC.name = "m_family_boss_times_update_toc"
M_FAMILY_BOSS_TIMES_UPDATE_TOC.full_name = ".m_family_boss_times_update_toc"
M_FAMILY_BOSS_TIMES_UPDATE_TOC.nested_types = {}
M_FAMILY_BOSS_TIMES_UPDATE_TOC.enum_types = {}
M_FAMILY_BOSS_TIMES_UPDATE_TOC.fields = {M_FAMILY_BOSS_TIMES_UPDATE_TOC_TIMES_FIELD}
M_FAMILY_BOSS_TIMES_UPDATE_TOC.is_extendable = false
M_FAMILY_BOSS_TIMES_UPDATE_TOC.extensions = {}

m_family_boss_times_update_toc = protobuf.Message(M_FAMILY_BOSS_TIMES_UPDATE_TOC)

