--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_fashion_time_pb = require("Protol.p_fashion_time_pb")
local p_fashion_pb = require("Protol.p_fashion_pb")
local p_fashion_suit_pb = require("Protol.p_fashion_suit_pb")
module('Protol.m_fashion_info_toc_pb')

M_FASHION_INFO_TOC = protobuf.Descriptor();
M_FASHION_INFO_TOC_OP_TYPE_FIELD = protobuf.FieldDescriptor();
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD = protobuf.FieldDescriptor();
M_FASHION_INFO_TOC_FASHION_LIST_FIELD = protobuf.FieldDescriptor();
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD = protobuf.FieldDescriptor();
M_FASHION_INFO_TOC_SUIT_LIST_FIELD = protobuf.FieldDescriptor();

M_FASHION_INFO_TOC_OP_TYPE_FIELD.name = "op_type"
M_FASHION_INFO_TOC_OP_TYPE_FIELD.full_name = ".m_fashion_info_toc.op_type"
M_FASHION_INFO_TOC_OP_TYPE_FIELD.number = 1
M_FASHION_INFO_TOC_OP_TYPE_FIELD.index = 0
M_FASHION_INFO_TOC_OP_TYPE_FIELD.label = 1
M_FASHION_INFO_TOC_OP_TYPE_FIELD.has_default_value = true
M_FASHION_INFO_TOC_OP_TYPE_FIELD.default_value = 0
M_FASHION_INFO_TOC_OP_TYPE_FIELD.type = 5
M_FASHION_INFO_TOC_OP_TYPE_FIELD.cpp_type = 1

M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.name = "cur_id_list"
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.full_name = ".m_fashion_info_toc.cur_id_list"
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.number = 2
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.index = 1
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.label = 3
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.has_default_value = false
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.default_value = {}
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.type = 5
M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD.cpp_type = 1

M_FASHION_INFO_TOC_FASHION_LIST_FIELD.name = "fashion_list"
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.full_name = ".m_fashion_info_toc.fashion_list"
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.number = 3
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.index = 2
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.label = 3
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.has_default_value = false
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.default_value = {}
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.message_type = p_fashion_time_pb.P_FASHION_TIME
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.type = 11
M_FASHION_INFO_TOC_FASHION_LIST_FIELD.cpp_type = 10

M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.name = "essence_list"
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.full_name = ".m_fashion_info_toc.essence_list"
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.number = 4
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.index = 3
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.label = 3
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.has_default_value = false
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.default_value = {}
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.message_type = p_fashion_pb.P_FASHION
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.type = 11
M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD.cpp_type = 10

M_FASHION_INFO_TOC_SUIT_LIST_FIELD.name = "suit_list"
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.full_name = ".m_fashion_info_toc.suit_list"
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.number = 5
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.index = 4
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.label = 3
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.has_default_value = false
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.default_value = {}
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.message_type = p_fashion_suit_pb.P_FASHION_SUIT
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.type = 11
M_FASHION_INFO_TOC_SUIT_LIST_FIELD.cpp_type = 10

M_FASHION_INFO_TOC.name = "m_fashion_info_toc"
M_FASHION_INFO_TOC.full_name = ".m_fashion_info_toc"
M_FASHION_INFO_TOC.nested_types = {}
M_FASHION_INFO_TOC.enum_types = {}
M_FASHION_INFO_TOC.fields = {M_FASHION_INFO_TOC_OP_TYPE_FIELD, M_FASHION_INFO_TOC_CUR_ID_LIST_FIELD, M_FASHION_INFO_TOC_FASHION_LIST_FIELD, M_FASHION_INFO_TOC_ESSENCE_LIST_FIELD, M_FASHION_INFO_TOC_SUIT_LIST_FIELD}
M_FASHION_INFO_TOC.is_extendable = false
M_FASHION_INFO_TOC.extensions = {}

m_fashion_info_toc = protobuf.Message(M_FASHION_INFO_TOC)

