--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_family_day_reward_info_toc_pb')

M_FAMILY_DAY_REWARD_INFO_TOC = protobuf.Descriptor();
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD = protobuf.FieldDescriptor();

M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.name = "reward"
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.full_name = ".m_family_day_reward_info_toc.reward"
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.number = 1
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.index = 0
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.label = 1
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.has_default_value = true
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.default_value = true
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.type = 8
M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD.cpp_type = 7

M_FAMILY_DAY_REWARD_INFO_TOC.name = "m_family_day_reward_info_toc"
M_FAMILY_DAY_REWARD_INFO_TOC.full_name = ".m_family_day_reward_info_toc"
M_FAMILY_DAY_REWARD_INFO_TOC.nested_types = {}
M_FAMILY_DAY_REWARD_INFO_TOC.enum_types = {}
M_FAMILY_DAY_REWARD_INFO_TOC.fields = {M_FAMILY_DAY_REWARD_INFO_TOC_REWARD_FIELD}
M_FAMILY_DAY_REWARD_INFO_TOC.is_extendable = false
M_FAMILY_DAY_REWARD_INFO_TOC.extensions = {}

m_family_day_reward_info_toc = protobuf.Message(M_FAMILY_DAY_REWARD_INFO_TOC)

