--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_family_battle_ecv_reward_tos_pb')

M_FAMILY_BATTLE_ECV_REWARD_TOS = protobuf.Descriptor();
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD = protobuf.FieldDescriptor();

M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.name = "role_id"
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.full_name = ".m_family_battle_ecv_reward_tos.role_id"
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.number = 1
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.index = 0
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.label = 1
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.has_default_value = true
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.default_value = 0
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.type = 3
M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD.cpp_type = 2

M_FAMILY_BATTLE_ECV_REWARD_TOS.name = "m_family_battle_ecv_reward_tos"
M_FAMILY_BATTLE_ECV_REWARD_TOS.full_name = ".m_family_battle_ecv_reward_tos"
M_FAMILY_BATTLE_ECV_REWARD_TOS.nested_types = {}
M_FAMILY_BATTLE_ECV_REWARD_TOS.enum_types = {}
M_FAMILY_BATTLE_ECV_REWARD_TOS.fields = {M_FAMILY_BATTLE_ECV_REWARD_TOS_ROLE_ID_FIELD}
M_FAMILY_BATTLE_ECV_REWARD_TOS.is_extendable = false
M_FAMILY_BATTLE_ECV_REWARD_TOS.extensions = {}

m_family_battle_ecv_reward_tos = protobuf.Message(M_FAMILY_BATTLE_ECV_REWARD_TOS)

