--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_red_packet_content_pb = require("Protol.p_red_packet_content_pb")
module('Protol.m_family_see_red_packet_toc_pb')

M_FAMILY_SEE_RED_PACKET_TOC = protobuf.Descriptor();
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD = protobuf.FieldDescriptor();
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD = protobuf.FieldDescriptor();

M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.name = "err_code"
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.full_name = ".m_family_see_red_packet_toc.err_code"
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.number = 1
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.index = 0
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.label = 1
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.has_default_value = true
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.default_value = 0
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.type = 5
M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD.cpp_type = 1

M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.name = "id"
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.full_name = ".m_family_see_red_packet_toc.id"
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.number = 2
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.index = 1
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.label = 1
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.has_default_value = true
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.default_value = 0
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.type = 5
M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD.cpp_type = 1

M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.name = "list"
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.full_name = ".m_family_see_red_packet_toc.list"
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.number = 3
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.index = 2
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.label = 3
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.has_default_value = false
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.default_value = {}
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.message_type = p_red_packet_content_pb.P_RED_PACKET_CONTENT
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.type = 11
M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD.cpp_type = 10

M_FAMILY_SEE_RED_PACKET_TOC.name = "m_family_see_red_packet_toc"
M_FAMILY_SEE_RED_PACKET_TOC.full_name = ".m_family_see_red_packet_toc"
M_FAMILY_SEE_RED_PACKET_TOC.nested_types = {}
M_FAMILY_SEE_RED_PACKET_TOC.enum_types = {}
M_FAMILY_SEE_RED_PACKET_TOC.fields = {M_FAMILY_SEE_RED_PACKET_TOC_ERR_CODE_FIELD, M_FAMILY_SEE_RED_PACKET_TOC_ID_FIELD, M_FAMILY_SEE_RED_PACKET_TOC_LIST_FIELD}
M_FAMILY_SEE_RED_PACKET_TOC.is_extendable = false
M_FAMILY_SEE_RED_PACKET_TOC.extensions = {}

m_family_see_red_packet_toc = protobuf.Message(M_FAMILY_SEE_RED_PACKET_TOC)

