--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_family_battle_salary_tos_pb')

M_FAMILY_BATTLE_SALARY_TOS = protobuf.Descriptor();

M_FAMILY_BATTLE_SALARY_TOS.name = "m_family_battle_salary_tos"
M_FAMILY_BATTLE_SALARY_TOS.full_name = ".m_family_battle_salary_tos"
M_FAMILY_BATTLE_SALARY_TOS.nested_types = {}
M_FAMILY_BATTLE_SALARY_TOS.enum_types = {}
M_FAMILY_BATTLE_SALARY_TOS.fields = {}
M_FAMILY_BATTLE_SALARY_TOS.is_extendable = false
M_FAMILY_BATTLE_SALARY_TOS.extensions = {}

m_family_battle_salary_tos = protobuf.Message(M_FAMILY_BATTLE_SALARY_TOS)

