--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_friend_request_del_toc_pb')

M_FRIEND_REQUEST_DEL_TOC = protobuf.Descriptor();
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD = protobuf.FieldDescriptor();

M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.name = "request_id"
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.full_name = ".m_friend_request_del_toc.request_id"
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.number = 1
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.index = 0
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.label = 1
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.has_default_value = true
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.default_value = 0
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.type = 3
M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD.cpp_type = 2

M_FRIEND_REQUEST_DEL_TOC.name = "m_friend_request_del_toc"
M_FRIEND_REQUEST_DEL_TOC.full_name = ".m_friend_request_del_toc"
M_FRIEND_REQUEST_DEL_TOC.nested_types = {}
M_FRIEND_REQUEST_DEL_TOC.enum_types = {}
M_FRIEND_REQUEST_DEL_TOC.fields = {M_FRIEND_REQUEST_DEL_TOC_REQUEST_ID_FIELD}
M_FRIEND_REQUEST_DEL_TOC.is_extendable = false
M_FRIEND_REQUEST_DEL_TOC.extensions = {}

m_friend_request_del_toc = protobuf.Message(M_FRIEND_REQUEST_DEL_TOC)

