--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_friend_pb = require("Protol.p_friend_pb")
module('Protol.m_friend_info_toc_pb')

M_FRIEND_INFO_TOC = protobuf.Descriptor();
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD = protobuf.FieldDescriptor();
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD = protobuf.FieldDescriptor();
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD = protobuf.FieldDescriptor();
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD = protobuf.FieldDescriptor();

M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.name = "friend_list"
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.full_name = ".m_friend_info_toc.friend_list"
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.number = 1
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.index = 0
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.label = 3
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.has_default_value = false
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.default_value = {}
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.message_type = p_friend_pb.P_FRIEND
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.type = 11
M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD.cpp_type = 10

M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.name = "black_list"
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.full_name = ".m_friend_info_toc.black_list"
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.number = 2
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.index = 1
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.label = 3
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.has_default_value = false
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.default_value = {}
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.message_type = p_friend_pb.P_FRIEND
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.type = 11
M_FRIEND_INFO_TOC_BLACK_LIST_FIELD.cpp_type = 10

M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.name = "request_list"
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.full_name = ".m_friend_info_toc.request_list"
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.number = 3
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.index = 2
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.label = 3
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.has_default_value = false
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.default_value = {}
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.message_type = p_friend_pb.P_FRIEND
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.type = 11
M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD.cpp_type = 10

M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.name = "chat_list"
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.full_name = ".m_friend_info_toc.chat_list"
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.number = 4
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.index = 3
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.label = 3
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.has_default_value = false
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.default_value = {}
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.message_type = p_friend_pb.P_FRIEND
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.type = 11
M_FRIEND_INFO_TOC_CHAT_LIST_FIELD.cpp_type = 10

M_FRIEND_INFO_TOC.name = "m_friend_info_toc"
M_FRIEND_INFO_TOC.full_name = ".m_friend_info_toc"
M_FRIEND_INFO_TOC.nested_types = {}
M_FRIEND_INFO_TOC.enum_types = {}
M_FRIEND_INFO_TOC.fields = {M_FRIEND_INFO_TOC_FRIEND_LIST_FIELD, M_FRIEND_INFO_TOC_BLACK_LIST_FIELD, M_FRIEND_INFO_TOC_REQUEST_LIST_FIELD, M_FRIEND_INFO_TOC_CHAT_LIST_FIELD}
M_FRIEND_INFO_TOC.is_extendable = false
M_FRIEND_INFO_TOC.extensions = {}

m_friend_info_toc = protobuf.Message(M_FRIEND_INFO_TOC)

