--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_friend_all_add_tos_pb')

M_FRIEND_ALL_ADD_TOS = protobuf.Descriptor();
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD = protobuf.FieldDescriptor();

M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.name = "choose"
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.full_name = ".m_friend_all_add_tos.choose"
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.number = 1
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.index = 0
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.label = 1
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.has_default_value = true
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.default_value = 0
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.type = 5
M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD.cpp_type = 1

M_FRIEND_ALL_ADD_TOS.name = "m_friend_all_add_tos"
M_FRIEND_ALL_ADD_TOS.full_name = ".m_friend_all_add_tos"
M_FRIEND_ALL_ADD_TOS.nested_types = {}
M_FRIEND_ALL_ADD_TOS.enum_types = {}
M_FRIEND_ALL_ADD_TOS.fields = {M_FRIEND_ALL_ADD_TOS_CHOOSE_FIELD}
M_FRIEND_ALL_ADD_TOS.is_extendable = false
M_FRIEND_ALL_ADD_TOS.extensions = {}

m_friend_all_add_tos = protobuf.Message(M_FRIEND_ALL_ADD_TOS)

