--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_friend_recommend_tos_pb')

M_FRIEND_RECOMMEND_TOS = protobuf.Descriptor();

M_FRIEND_RECOMMEND_TOS.name = "m_friend_recommend_tos"
M_FRIEND_RECOMMEND_TOS.full_name = ".m_friend_recommend_tos"
M_FRIEND_RECOMMEND_TOS.nested_types = {}
M_FRIEND_RECOMMEND_TOS.enum_types = {}
M_FRIEND_RECOMMEND_TOS.fields = {}
M_FRIEND_RECOMMEND_TOS.is_extendable = false
M_FRIEND_RECOMMEND_TOS.extensions = {}

m_friend_recommend_tos = protobuf.Message(M_FRIEND_RECOMMEND_TOS)

