--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_friend_black_del_tos_pb')

M_FRIEND_BLACK_DEL_TOS = protobuf.Descriptor();
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD = protobuf.FieldDescriptor();

M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.name = "black_id"
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.full_name = ".m_friend_black_del_tos.black_id"
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.number = 1
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.index = 0
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.label = 1
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.has_default_value = true
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.default_value = 0
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.type = 3
M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD.cpp_type = 2

M_FRIEND_BLACK_DEL_TOS.name = "m_friend_black_del_tos"
M_FRIEND_BLACK_DEL_TOS.full_name = ".m_friend_black_del_tos"
M_FRIEND_BLACK_DEL_TOS.nested_types = {}
M_FRIEND_BLACK_DEL_TOS.enum_types = {}
M_FRIEND_BLACK_DEL_TOS.fields = {M_FRIEND_BLACK_DEL_TOS_BLACK_ID_FIELD}
M_FRIEND_BLACK_DEL_TOS.is_extendable = false
M_FRIEND_BLACK_DEL_TOS.extensions = {}

m_friend_black_del_tos = protobuf.Message(M_FRIEND_BLACK_DEL_TOS)

