--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kvl_pb = require("Protol.p_kvl_pb")
module('Protol.m_god_book_update_toc_pb')

M_GOD_BOOK_UPDATE_TOC = protobuf.Descriptor();
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD = protobuf.FieldDescriptor();

M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.name = "doing"
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.full_name = ".m_god_book_update_toc.doing"
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.number = 1
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.index = 0
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.label = 3
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.has_default_value = false
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.default_value = {}
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.message_type = p_kvl_pb.P_KVL
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.type = 11
M_GOD_BOOK_UPDATE_TOC_DOING_FIELD.cpp_type = 10

M_GOD_BOOK_UPDATE_TOC.name = "m_god_book_update_toc"
M_GOD_BOOK_UPDATE_TOC.full_name = ".m_god_book_update_toc"
M_GOD_BOOK_UPDATE_TOC.nested_types = {}
M_GOD_BOOK_UPDATE_TOC.enum_types = {}
M_GOD_BOOK_UPDATE_TOC.fields = {M_GOD_BOOK_UPDATE_TOC_DOING_FIELD}
M_GOD_BOOK_UPDATE_TOC.is_extendable = false
M_GOD_BOOK_UPDATE_TOC.extensions = {}

m_god_book_update_toc = protobuf.Message(M_GOD_BOOK_UPDATE_TOC)

