--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_goods_compose_toc_pb')

M_GOODS_COMPOSE_TOC = protobuf.Descriptor();
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD = protobuf.FieldDescriptor();

M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.name = "err_code"
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.full_name = ".m_goods_compose_toc.err_code"
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.number = 1
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.index = 0
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.label = 1
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.has_default_value = true
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.default_value = 0
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.type = 5
M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD.cpp_type = 1

M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.name = "is_success"
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.full_name = ".m_goods_compose_toc.is_success"
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.number = 2
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.index = 1
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.label = 1
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.has_default_value = true
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.default_value = true
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.type = 8
M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD.cpp_type = 7

M_GOODS_COMPOSE_TOC.name = "m_goods_compose_toc"
M_GOODS_COMPOSE_TOC.full_name = ".m_goods_compose_toc"
M_GOODS_COMPOSE_TOC.nested_types = {}
M_GOODS_COMPOSE_TOC.enum_types = {}
M_GOODS_COMPOSE_TOC.fields = {M_GOODS_COMPOSE_TOC_ERR_CODE_FIELD, M_GOODS_COMPOSE_TOC_IS_SUCCESS_FIELD}
M_GOODS_COMPOSE_TOC.is_extendable = false
M_GOODS_COMPOSE_TOC.extensions = {}

m_goods_compose_toc = protobuf.Message(M_GOODS_COMPOSE_TOC)

