--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_invest_gold_buy_toc_pb')

M_INVEST_GOLD_BUY_TOC = protobuf.Descriptor();
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD = protobuf.FieldDescriptor();

M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.name = "err_code"
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.full_name = ".m_invest_gold_buy_toc.err_code"
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.number = 1
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.index = 0
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.label = 1
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.has_default_value = true
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.default_value = 0
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.type = 5
M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD.cpp_type = 1

M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.name = "invest_gold"
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.full_name = ".m_invest_gold_buy_toc.invest_gold"
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.number = 2
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.index = 1
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.label = 1
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.has_default_value = true
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.default_value = 0
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.type = 5
M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD.cpp_type = 1

M_INVEST_GOLD_BUY_TOC.name = "m_invest_gold_buy_toc"
M_INVEST_GOLD_BUY_TOC.full_name = ".m_invest_gold_buy_toc"
M_INVEST_GOLD_BUY_TOC.nested_types = {}
M_INVEST_GOLD_BUY_TOC.enum_types = {}
M_INVEST_GOLD_BUY_TOC.fields = {M_INVEST_GOLD_BUY_TOC_ERR_CODE_FIELD, M_INVEST_GOLD_BUY_TOC_INVEST_GOLD_FIELD}
M_INVEST_GOLD_BUY_TOC.is_extendable = false
M_INVEST_GOLD_BUY_TOC.extensions = {}

m_invest_gold_buy_toc = protobuf.Message(M_INVEST_GOLD_BUY_TOC)

