--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_invest_gold_reward_tos_pb')

M_INVEST_GOLD_REWARD_TOS = protobuf.Descriptor();
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD = protobuf.FieldDescriptor();

M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.name = "level"
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.full_name = ".m_invest_gold_reward_tos.level"
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.number = 1
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.index = 0
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.label = 1
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.has_default_value = true
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.default_value = 0
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.type = 5
M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD.cpp_type = 1

M_INVEST_GOLD_REWARD_TOS.name = "m_invest_gold_reward_tos"
M_INVEST_GOLD_REWARD_TOS.full_name = ".m_invest_gold_reward_tos"
M_INVEST_GOLD_REWARD_TOS.nested_types = {}
M_INVEST_GOLD_REWARD_TOS.enum_types = {}
M_INVEST_GOLD_REWARD_TOS.fields = {M_INVEST_GOLD_REWARD_TOS_LEVEL_FIELD}
M_INVEST_GOLD_REWARD_TOS.is_extendable = false
M_INVEST_GOLD_REWARD_TOS.extensions = {}

m_invest_gold_reward_tos = protobuf.Message(M_INVEST_GOLD_REWARD_TOS)

