--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_invest_gold_info_toc_pb')

M_INVEST_GOLD_INFO_TOC = protobuf.Descriptor();
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD = protobuf.FieldDescriptor();
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD = protobuf.FieldDescriptor();

M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.name = "invest_gold"
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.full_name = ".m_invest_gold_info_toc.invest_gold"
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.number = 1
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.index = 0
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.label = 1
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.has_default_value = true
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.default_value = 0
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.type = 5
M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD.cpp_type = 1

M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.name = "reward_list"
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.full_name = ".m_invest_gold_info_toc.reward_list"
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.number = 2
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.index = 1
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.label = 3
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.has_default_value = false
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.default_value = {}
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.message_type = p_kv_pb.P_KV
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.type = 11
M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD.cpp_type = 10

M_INVEST_GOLD_INFO_TOC.name = "m_invest_gold_info_toc"
M_INVEST_GOLD_INFO_TOC.full_name = ".m_invest_gold_info_toc"
M_INVEST_GOLD_INFO_TOC.nested_types = {}
M_INVEST_GOLD_INFO_TOC.enum_types = {}
M_INVEST_GOLD_INFO_TOC.fields = {M_INVEST_GOLD_INFO_TOC_INVEST_GOLD_FIELD, M_INVEST_GOLD_INFO_TOC_REWARD_LIST_FIELD}
M_INVEST_GOLD_INFO_TOC.is_extendable = false
M_INVEST_GOLD_INFO_TOC.extensions = {}

m_invest_gold_info_toc = protobuf.Message(M_INVEST_GOLD_INFO_TOC)

