--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_map_taste_times_toc_pb')

M_MARRY_MAP_TASTE_TIMES_TOC = protobuf.Descriptor();
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD = protobuf.FieldDescriptor();

M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.name = "taste_times"
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.full_name = ".m_marry_map_taste_times_toc.taste_times"
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.number = 1
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.index = 0
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.label = 1
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.has_default_value = true
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.default_value = 0
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.type = 5
M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD.cpp_type = 1

M_MARRY_MAP_TASTE_TIMES_TOC.name = "m_marry_map_taste_times_toc"
M_MARRY_MAP_TASTE_TIMES_TOC.full_name = ".m_marry_map_taste_times_toc"
M_MARRY_MAP_TASTE_TIMES_TOC.nested_types = {}
M_MARRY_MAP_TASTE_TIMES_TOC.enum_types = {}
M_MARRY_MAP_TASTE_TIMES_TOC.fields = {M_MARRY_MAP_TASTE_TIMES_TOC_TASTE_TIMES_FIELD}
M_MARRY_MAP_TASTE_TIMES_TOC.is_extendable = false
M_MARRY_MAP_TASTE_TIMES_TOC.extensions = {}

m_marry_map_taste_times_toc = protobuf.Message(M_MARRY_MAP_TASTE_TIMES_TOC)

