--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_invite_guest_tos_pb')

M_MARRY_INVITE_GUEST_TOS = protobuf.Descriptor();
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD = protobuf.FieldDescriptor();

M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.name = "role_id"
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.full_name = ".m_marry_invite_guest_tos.role_id"
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.number = 1
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.index = 0
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.label = 1
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.has_default_value = true
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.default_value = 0
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.type = 3
M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD.cpp_type = 2

M_MARRY_INVITE_GUEST_TOS.name = "m_marry_invite_guest_tos"
M_MARRY_INVITE_GUEST_TOS.full_name = ".m_marry_invite_guest_tos"
M_MARRY_INVITE_GUEST_TOS.nested_types = {}
M_MARRY_INVITE_GUEST_TOS.enum_types = {}
M_MARRY_INVITE_GUEST_TOS.fields = {M_MARRY_INVITE_GUEST_TOS_ROLE_ID_FIELD}
M_MARRY_INVITE_GUEST_TOS.is_extendable = false
M_MARRY_INVITE_GUEST_TOS.extensions = {}

m_marry_invite_guest_tos = protobuf.Message(M_MARRY_INVITE_GUEST_TOS)

