--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_map_line_info_tos_pb')

M_MAP_LINE_INFO_TOS = protobuf.Descriptor();
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD = protobuf.FieldDescriptor();

M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.name = "map_id"
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.full_name = ".m_map_line_info_tos.map_id"
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.number = 1
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.index = 0
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.label = 1
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.has_default_value = true
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.default_value = 0
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.type = 5
M_MAP_LINE_INFO_TOS_MAP_ID_FIELD.cpp_type = 1

M_MAP_LINE_INFO_TOS.name = "m_map_line_info_tos"
M_MAP_LINE_INFO_TOS.full_name = ".m_map_line_info_tos"
M_MAP_LINE_INFO_TOS.nested_types = {}
M_MAP_LINE_INFO_TOS.enum_types = {}
M_MAP_LINE_INFO_TOS.fields = {M_MAP_LINE_INFO_TOS_MAP_ID_FIELD}
M_MAP_LINE_INFO_TOS.is_extendable = false
M_MAP_LINE_INFO_TOS.extensions = {}

m_map_line_info_tos = protobuf.Message(M_MAP_LINE_INFO_TOS)

