--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_tree_reward_tos_pb')

M_MARRY_TREE_REWARD_TOS = protobuf.Descriptor();
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD = protobuf.FieldDescriptor();

M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.name = "type"
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.full_name = ".m_marry_tree_reward_tos.type"
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.number = 1
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.index = 0
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.label = 1
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.has_default_value = true
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.default_value = 0
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.type = 5
M_MARRY_TREE_REWARD_TOS_TYPE_FIELD.cpp_type = 1

M_MARRY_TREE_REWARD_TOS.name = "m_marry_tree_reward_tos"
M_MARRY_TREE_REWARD_TOS.full_name = ".m_marry_tree_reward_tos"
M_MARRY_TREE_REWARD_TOS.nested_types = {}
M_MARRY_TREE_REWARD_TOS.enum_types = {}
M_MARRY_TREE_REWARD_TOS.fields = {M_MARRY_TREE_REWARD_TOS_TYPE_FIELD}
M_MARRY_TREE_REWARD_TOS.is_extendable = false
M_MARRY_TREE_REWARD_TOS.extensions = {}

m_marry_tree_reward_tos = protobuf.Message(M_MARRY_TREE_REWARD_TOS)

