--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_copy_select_tos_pb')

M_MARRY_COPY_SELECT_TOS = protobuf.Descriptor();
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD = protobuf.FieldDescriptor();

M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.name = "item"
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.full_name = ".m_marry_copy_select_tos.item"
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.number = 1
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.index = 0
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.label = 1
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.has_default_value = true
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.default_value = 0
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.type = 5
M_MARRY_COPY_SELECT_TOS_ITEM_FIELD.cpp_type = 1

M_MARRY_COPY_SELECT_TOS.name = "m_marry_copy_select_tos"
M_MARRY_COPY_SELECT_TOS.full_name = ".m_marry_copy_select_tos"
M_MARRY_COPY_SELECT_TOS.nested_types = {}
M_MARRY_COPY_SELECT_TOS.enum_types = {}
M_MARRY_COPY_SELECT_TOS.fields = {M_MARRY_COPY_SELECT_TOS_ITEM_FIELD}
M_MARRY_COPY_SELECT_TOS.is_extendable = false
M_MARRY_COPY_SELECT_TOS.extensions = {}

m_marry_copy_select_tos = protobuf.Message(M_MARRY_COPY_SELECT_TOS)

