--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_fairy_tos_pb')

M_MARRY_FAIRY_TOS = protobuf.Descriptor();
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD = protobuf.FieldDescriptor();
M_MARRY_FAIRY_TOS_TEXT_FIELD = protobuf.FieldDescriptor();

M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.name = "goods_list"
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.full_name = ".m_marry_fairy_tos.goods_list"
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.number = 1
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.index = 0
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.label = 3
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.has_default_value = false
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.default_value = {}
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.type = 5
M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD.cpp_type = 1

M_MARRY_FAIRY_TOS_TEXT_FIELD.name = "text"
M_MARRY_FAIRY_TOS_TEXT_FIELD.full_name = ".m_marry_fairy_tos.text"
M_MARRY_FAIRY_TOS_TEXT_FIELD.number = 2
M_MARRY_FAIRY_TOS_TEXT_FIELD.index = 1
M_MARRY_FAIRY_TOS_TEXT_FIELD.label = 1
M_MARRY_FAIRY_TOS_TEXT_FIELD.has_default_value = false
M_MARRY_FAIRY_TOS_TEXT_FIELD.default_value = ""
M_MARRY_FAIRY_TOS_TEXT_FIELD.type = 9
M_MARRY_FAIRY_TOS_TEXT_FIELD.cpp_type = 9

M_MARRY_FAIRY_TOS.name = "m_marry_fairy_tos"
M_MARRY_FAIRY_TOS.full_name = ".m_marry_fairy_tos"
M_MARRY_FAIRY_TOS.nested_types = {}
M_MARRY_FAIRY_TOS.enum_types = {}
M_MARRY_FAIRY_TOS.fields = {M_MARRY_FAIRY_TOS_GOODS_LIST_FIELD, M_MARRY_FAIRY_TOS_TEXT_FIELD}
M_MARRY_FAIRY_TOS.is_extendable = false
M_MARRY_FAIRY_TOS.extensions = {}

m_marry_fairy_tos = protobuf.Message(M_MARRY_FAIRY_TOS)

