--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_market_goods_pb = require("Protol.p_market_goods_pb")
module('Protol.m_market_search_toc_pb')

M_MARKET_SEARCH_TOC = protobuf.Descriptor();
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_MARKET_SEARCH_TOC_GOODS_FIELD = protobuf.FieldDescriptor();
M_MARKET_SEARCH_TOC_TYPE_FIELD = protobuf.FieldDescriptor();
M_MARKET_SEARCH_TOC_DIC_ID_FIELD = protobuf.FieldDescriptor();
M_MARKET_SEARCH_TOC_IS_NULL_FIELD = protobuf.FieldDescriptor();

M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.name = "err_code"
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.full_name = ".m_market_search_toc.err_code"
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.number = 1
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.index = 0
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.label = 1
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.has_default_value = true
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.default_value = 0
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.type = 5
M_MARKET_SEARCH_TOC_ERR_CODE_FIELD.cpp_type = 1

M_MARKET_SEARCH_TOC_GOODS_FIELD.name = "goods"
M_MARKET_SEARCH_TOC_GOODS_FIELD.full_name = ".m_market_search_toc.goods"
M_MARKET_SEARCH_TOC_GOODS_FIELD.number = 2
M_MARKET_SEARCH_TOC_GOODS_FIELD.index = 1
M_MARKET_SEARCH_TOC_GOODS_FIELD.label = 3
M_MARKET_SEARCH_TOC_GOODS_FIELD.has_default_value = false
M_MARKET_SEARCH_TOC_GOODS_FIELD.default_value = {}
M_MARKET_SEARCH_TOC_GOODS_FIELD.message_type = p_market_goods_pb.P_MARKET_GOODS
M_MARKET_SEARCH_TOC_GOODS_FIELD.type = 11
M_MARKET_SEARCH_TOC_GOODS_FIELD.cpp_type = 10

M_MARKET_SEARCH_TOC_TYPE_FIELD.name = "type"
M_MARKET_SEARCH_TOC_TYPE_FIELD.full_name = ".m_market_search_toc.type"
M_MARKET_SEARCH_TOC_TYPE_FIELD.number = 3
M_MARKET_SEARCH_TOC_TYPE_FIELD.index = 2
M_MARKET_SEARCH_TOC_TYPE_FIELD.label = 1
M_MARKET_SEARCH_TOC_TYPE_FIELD.has_default_value = true
M_MARKET_SEARCH_TOC_TYPE_FIELD.default_value = 0
M_MARKET_SEARCH_TOC_TYPE_FIELD.type = 5
M_MARKET_SEARCH_TOC_TYPE_FIELD.cpp_type = 1

M_MARKET_SEARCH_TOC_DIC_ID_FIELD.name = "dic_id"
M_MARKET_SEARCH_TOC_DIC_ID_FIELD.full_name = ".m_market_search_toc.dic_id"
M_MARKET_SEARCH_TOC_DIC_ID_FIELD.number = 4
M_MARKET_SEARCH_TOC_DIC_ID_FIELD.index = 3
M_MARKET_SEARCH_TOC_DIC_ID_FIELD.label = 1
M_MARKET_SEARCH_TOC_DIC_ID_FIELD.has_default_value = true
M_MARKET_SEARCH_TOC_DIC_ID_FIELD.default_value = 0
M_MARKET_SEARCH_TOC_DIC_ID_FIELD.type = 5
M_MARKET_SEARCH_TOC_DIC_ID_FIELD.cpp_type = 1

M_MARKET_SEARCH_TOC_IS_NULL_FIELD.name = "is_null"
M_MARKET_SEARCH_TOC_IS_NULL_FIELD.full_name = ".m_market_search_toc.is_null"
M_MARKET_SEARCH_TOC_IS_NULL_FIELD.number = 5
M_MARKET_SEARCH_TOC_IS_NULL_FIELD.index = 4
M_MARKET_SEARCH_TOC_IS_NULL_FIELD.label = 1
M_MARKET_SEARCH_TOC_IS_NULL_FIELD.has_default_value = true
M_MARKET_SEARCH_TOC_IS_NULL_FIELD.default_value = true
M_MARKET_SEARCH_TOC_IS_NULL_FIELD.type = 8
M_MARKET_SEARCH_TOC_IS_NULL_FIELD.cpp_type = 7

M_MARKET_SEARCH_TOC.name = "m_market_search_toc"
M_MARKET_SEARCH_TOC.full_name = ".m_market_search_toc"
M_MARKET_SEARCH_TOC.nested_types = {}
M_MARKET_SEARCH_TOC.enum_types = {}
M_MARKET_SEARCH_TOC.fields = {M_MARKET_SEARCH_TOC_ERR_CODE_FIELD, M_MARKET_SEARCH_TOC_GOODS_FIELD, M_MARKET_SEARCH_TOC_TYPE_FIELD, M_MARKET_SEARCH_TOC_DIC_ID_FIELD, M_MARKET_SEARCH_TOC_IS_NULL_FIELD}
M_MARKET_SEARCH_TOC.is_extendable = false
M_MARKET_SEARCH_TOC.extensions = {}

m_market_search_toc = protobuf.Message(M_MARKET_SEARCH_TOC)

