--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_map_wish_tos_pb')

M_MARRY_MAP_WISH_TOS = protobuf.Descriptor();
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD = protobuf.FieldDescriptor();
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD = protobuf.FieldDescriptor();

M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.name = "index_id"
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.full_name = ".m_marry_map_wish_tos.index_id"
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.number = 1
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.index = 0
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.label = 1
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.has_default_value = true
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.default_value = 0
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.type = 5
M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD.cpp_type = 1

M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.name = "to_role_id"
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.full_name = ".m_marry_map_wish_tos.to_role_id"
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.number = 2
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.index = 1
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.label = 1
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.has_default_value = true
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.default_value = 0
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.type = 3
M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD.cpp_type = 2

M_MARRY_MAP_WISH_TOS.name = "m_marry_map_wish_tos"
M_MARRY_MAP_WISH_TOS.full_name = ".m_marry_map_wish_tos"
M_MARRY_MAP_WISH_TOS.nested_types = {}
M_MARRY_MAP_WISH_TOS.enum_types = {}
M_MARRY_MAP_WISH_TOS.fields = {M_MARRY_MAP_WISH_TOS_INDEX_ID_FIELD, M_MARRY_MAP_WISH_TOS_TO_ROLE_ID_FIELD}
M_MARRY_MAP_WISH_TOS.is_extendable = false
M_MARRY_MAP_WISH_TOS.extensions = {}

m_marry_map_wish_tos = protobuf.Message(M_MARRY_MAP_WISH_TOS)

