--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_couple_tos_pb')

M_MARRY_COUPLE_TOS = protobuf.Descriptor();

M_MARRY_COUPLE_TOS.name = "m_marry_couple_tos"
M_MARRY_COUPLE_TOS.full_name = ".m_marry_couple_tos"
M_MARRY_COUPLE_TOS.nested_types = {}
M_MARRY_COUPLE_TOS.enum_types = {}
M_MARRY_COUPLE_TOS.fields = {}
M_MARRY_COUPLE_TOS.is_extendable = false
M_MARRY_COUPLE_TOS.extensions = {}

m_marry_couple_tos = protobuf.Message(M_MARRY_COUPLE_TOS)

