--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_knot_update_toc_pb')

M_MARRY_KNOT_UPDATE_TOC = protobuf.Descriptor();
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD = protobuf.FieldDescriptor();
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD = protobuf.FieldDescriptor();

M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.name = "knot_id"
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.full_name = ".m_marry_knot_update_toc.knot_id"
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.number = 1
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.index = 0
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.label = 1
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.has_default_value = true
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.default_value = 0
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.type = 5
M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD.cpp_type = 1

M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.name = "knot_exp"
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.full_name = ".m_marry_knot_update_toc.knot_exp"
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.number = 2
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.index = 1
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.label = 1
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.has_default_value = true
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.default_value = 0
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.type = 5
M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD.cpp_type = 1

M_MARRY_KNOT_UPDATE_TOC.name = "m_marry_knot_update_toc"
M_MARRY_KNOT_UPDATE_TOC.full_name = ".m_marry_knot_update_toc"
M_MARRY_KNOT_UPDATE_TOC.nested_types = {}
M_MARRY_KNOT_UPDATE_TOC.enum_types = {}
M_MARRY_KNOT_UPDATE_TOC.fields = {M_MARRY_KNOT_UPDATE_TOC_KNOT_ID_FIELD, M_MARRY_KNOT_UPDATE_TOC_KNOT_EXP_FIELD}
M_MARRY_KNOT_UPDATE_TOC.is_extendable = false
M_MARRY_KNOT_UPDATE_TOC.extensions = {}

m_marry_knot_update_toc = protobuf.Message(M_MARRY_KNOT_UPDATE_TOC)

