--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_copy_icon_toc_pb')

M_MARRY_COPY_ICON_TOC = protobuf.Descriptor();
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD = protobuf.FieldDescriptor();
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD = protobuf.FieldDescriptor();

M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.name = "item_list"
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.full_name = ".m_marry_copy_icon_toc.item_list"
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.number = 1
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.index = 0
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.label = 3
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.has_default_value = false
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.default_value = {}
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.type = 5
M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD.cpp_type = 1

M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.name = "end_time"
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.full_name = ".m_marry_copy_icon_toc.end_time"
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.number = 2
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.index = 1
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.label = 1
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.has_default_value = true
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.default_value = 0
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.type = 5
M_MARRY_COPY_ICON_TOC_END_TIME_FIELD.cpp_type = 1

M_MARRY_COPY_ICON_TOC.name = "m_marry_copy_icon_toc"
M_MARRY_COPY_ICON_TOC.full_name = ".m_marry_copy_icon_toc"
M_MARRY_COPY_ICON_TOC.nested_types = {}
M_MARRY_COPY_ICON_TOC.enum_types = {}
M_MARRY_COPY_ICON_TOC.fields = {M_MARRY_COPY_ICON_TOC_ITEM_LIST_FIELD, M_MARRY_COPY_ICON_TOC_END_TIME_FIELD}
M_MARRY_COPY_ICON_TOC.is_extendable = false
M_MARRY_COPY_ICON_TOC.extensions = {}

m_marry_copy_icon_toc = protobuf.Message(M_MARRY_COPY_ICON_TOC)

