--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_marry_set_buy_tos_pb')

M_MARRY_SET_BUY_TOS = protobuf.Descriptor();
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD = protobuf.FieldDescriptor();

M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.name = "is_buy_join"
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.full_name = ".m_marry_set_buy_tos.is_buy_join"
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.number = 1
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.index = 0
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.label = 1
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.has_default_value = true
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.default_value = true
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.type = 8
M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD.cpp_type = 7

M_MARRY_SET_BUY_TOS.name = "m_marry_set_buy_tos"
M_MARRY_SET_BUY_TOS.full_name = ".m_marry_set_buy_tos"
M_MARRY_SET_BUY_TOS.nested_types = {}
M_MARRY_SET_BUY_TOS.enum_types = {}
M_MARRY_SET_BUY_TOS.fields = {M_MARRY_SET_BUY_TOS_IS_BUY_JOIN_FIELD}
M_MARRY_SET_BUY_TOS.is_extendable = false
M_MARRY_SET_BUY_TOS.extensions = {}

m_marry_set_buy_tos = protobuf.Message(M_MARRY_SET_BUY_TOS)

