--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_market_log_pb = require("Protol.p_market_log_pb")
module('Protol.m_market_self_log_toc_pb')

M_MARKET_SELF_LOG_TOC = protobuf.Descriptor();
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_MARKET_SELF_LOG_TOC_LOGS_FIELD = protobuf.FieldDescriptor();

M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.name = "err_code"
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.full_name = ".m_market_self_log_toc.err_code"
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.number = 1
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.index = 0
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.label = 1
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.has_default_value = true
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.default_value = 0
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.type = 5
M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD.cpp_type = 1

M_MARKET_SELF_LOG_TOC_LOGS_FIELD.name = "logs"
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.full_name = ".m_market_self_log_toc.logs"
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.number = 2
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.index = 1
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.label = 3
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.has_default_value = false
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.default_value = {}
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.message_type = p_market_log_pb.P_MARKET_LOG
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.type = 11
M_MARKET_SELF_LOG_TOC_LOGS_FIELD.cpp_type = 10

M_MARKET_SELF_LOG_TOC.name = "m_market_self_log_toc"
M_MARKET_SELF_LOG_TOC.full_name = ".m_market_self_log_toc"
M_MARKET_SELF_LOG_TOC.nested_types = {}
M_MARKET_SELF_LOG_TOC.enum_types = {}
M_MARKET_SELF_LOG_TOC.fields = {M_MARKET_SELF_LOG_TOC_ERR_CODE_FIELD, M_MARKET_SELF_LOG_TOC_LOGS_FIELD}
M_MARKET_SELF_LOG_TOC.is_extendable = false
M_MARKET_SELF_LOG_TOC.extensions = {}

m_market_self_log_toc = protobuf.Message(M_MARKET_SELF_LOG_TOC)

