--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_mission_pb = require("Protol.p_mission_pb")
module('Protol.m_mission_update_toc_pb')

M_MISSION_UPDATE_TOC = protobuf.Descriptor();
M_MISSION_UPDATE_TOC_DEL_FIELD = protobuf.FieldDescriptor();
M_MISSION_UPDATE_TOC_UPDATE_FIELD = protobuf.FieldDescriptor();

M_MISSION_UPDATE_TOC_DEL_FIELD.name = "del"
M_MISSION_UPDATE_TOC_DEL_FIELD.full_name = ".m_mission_update_toc.del"
M_MISSION_UPDATE_TOC_DEL_FIELD.number = 1
M_MISSION_UPDATE_TOC_DEL_FIELD.index = 0
M_MISSION_UPDATE_TOC_DEL_FIELD.label = 3
M_MISSION_UPDATE_TOC_DEL_FIELD.has_default_value = false
M_MISSION_UPDATE_TOC_DEL_FIELD.default_value = {}
M_MISSION_UPDATE_TOC_DEL_FIELD.type = 5
M_MISSION_UPDATE_TOC_DEL_FIELD.cpp_type = 1

M_MISSION_UPDATE_TOC_UPDATE_FIELD.name = "update"
M_MISSION_UPDATE_TOC_UPDATE_FIELD.full_name = ".m_mission_update_toc.update"
M_MISSION_UPDATE_TOC_UPDATE_FIELD.number = 2
M_MISSION_UPDATE_TOC_UPDATE_FIELD.index = 1
M_MISSION_UPDATE_TOC_UPDATE_FIELD.label = 3
M_MISSION_UPDATE_TOC_UPDATE_FIELD.has_default_value = false
M_MISSION_UPDATE_TOC_UPDATE_FIELD.default_value = {}
M_MISSION_UPDATE_TOC_UPDATE_FIELD.message_type = p_mission_pb.P_MISSION
M_MISSION_UPDATE_TOC_UPDATE_FIELD.type = 11
M_MISSION_UPDATE_TOC_UPDATE_FIELD.cpp_type = 10

M_MISSION_UPDATE_TOC.name = "m_mission_update_toc"
M_MISSION_UPDATE_TOC.full_name = ".m_mission_update_toc"
M_MISSION_UPDATE_TOC.nested_types = {}
M_MISSION_UPDATE_TOC.enum_types = {}
M_MISSION_UPDATE_TOC.fields = {M_MISSION_UPDATE_TOC_DEL_FIELD, M_MISSION_UPDATE_TOC_UPDATE_FIELD}
M_MISSION_UPDATE_TOC.is_extendable = false
M_MISSION_UPDATE_TOC.extensions = {}

m_mission_update_toc = protobuf.Message(M_MISSION_UPDATE_TOC)

