--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_mount_step_toc_pb')

M_MOUNT_STEP_TOC = protobuf.Descriptor();
M_MOUNT_STEP_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD = protobuf.FieldDescriptor();
M_MOUNT_STEP_TOC_EXP_FIELD = protobuf.FieldDescriptor();

M_MOUNT_STEP_TOC_ERR_CODE_FIELD.name = "err_code"
M_MOUNT_STEP_TOC_ERR_CODE_FIELD.full_name = ".m_mount_step_toc.err_code"
M_MOUNT_STEP_TOC_ERR_CODE_FIELD.number = 1
M_MOUNT_STEP_TOC_ERR_CODE_FIELD.index = 0
M_MOUNT_STEP_TOC_ERR_CODE_FIELD.label = 1
M_MOUNT_STEP_TOC_ERR_CODE_FIELD.has_default_value = true
M_MOUNT_STEP_TOC_ERR_CODE_FIELD.default_value = 0
M_MOUNT_STEP_TOC_ERR_CODE_FIELD.type = 5
M_MOUNT_STEP_TOC_ERR_CODE_FIELD.cpp_type = 1

M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.name = "mount_id"
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.full_name = ".m_mount_step_toc.mount_id"
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.number = 2
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.index = 1
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.label = 1
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.has_default_value = true
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.default_value = 0
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.type = 5
M_MOUNT_STEP_TOC_MOUNT_ID_FIELD.cpp_type = 1

M_MOUNT_STEP_TOC_EXP_FIELD.name = "exp"
M_MOUNT_STEP_TOC_EXP_FIELD.full_name = ".m_mount_step_toc.exp"
M_MOUNT_STEP_TOC_EXP_FIELD.number = 3
M_MOUNT_STEP_TOC_EXP_FIELD.index = 2
M_MOUNT_STEP_TOC_EXP_FIELD.label = 1
M_MOUNT_STEP_TOC_EXP_FIELD.has_default_value = true
M_MOUNT_STEP_TOC_EXP_FIELD.default_value = 0
M_MOUNT_STEP_TOC_EXP_FIELD.type = 5
M_MOUNT_STEP_TOC_EXP_FIELD.cpp_type = 1

M_MOUNT_STEP_TOC.name = "m_mount_step_toc"
M_MOUNT_STEP_TOC.full_name = ".m_mount_step_toc"
M_MOUNT_STEP_TOC.nested_types = {}
M_MOUNT_STEP_TOC.enum_types = {}
M_MOUNT_STEP_TOC.fields = {M_MOUNT_STEP_TOC_ERR_CODE_FIELD, M_MOUNT_STEP_TOC_MOUNT_ID_FIELD, M_MOUNT_STEP_TOC_EXP_FIELD}
M_MOUNT_STEP_TOC.is_extendable = false
M_MOUNT_STEP_TOC.extensions = {}

m_mount_step_toc = protobuf.Message(M_MOUNT_STEP_TOC)

