--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_mount_pb = require("Protol.p_mount_pb")
module('Protol.m_mount_info_toc_pb')

M_MOUNT_INFO_TOC = protobuf.Descriptor();
M_MOUNT_INFO_TOC_OP_TYPE_FIELD = protobuf.FieldDescriptor();
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD = protobuf.FieldDescriptor();

M_MOUNT_INFO_TOC_OP_TYPE_FIELD.name = "op_type"
M_MOUNT_INFO_TOC_OP_TYPE_FIELD.full_name = ".m_mount_info_toc.op_type"
M_MOUNT_INFO_TOC_OP_TYPE_FIELD.number = 1
M_MOUNT_INFO_TOC_OP_TYPE_FIELD.index = 0
M_MOUNT_INFO_TOC_OP_TYPE_FIELD.label = 1
M_MOUNT_INFO_TOC_OP_TYPE_FIELD.has_default_value = true
M_MOUNT_INFO_TOC_OP_TYPE_FIELD.default_value = 0
M_MOUNT_INFO_TOC_OP_TYPE_FIELD.type = 5
M_MOUNT_INFO_TOC_OP_TYPE_FIELD.cpp_type = 1

M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.name = "mount_info"
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.full_name = ".m_mount_info_toc.mount_info"
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.number = 2
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.index = 1
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.label = 1
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.has_default_value = false
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.default_value = nil
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.message_type = p_mount_pb.P_MOUNT
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.type = 11
M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD.cpp_type = 10

M_MOUNT_INFO_TOC.name = "m_mount_info_toc"
M_MOUNT_INFO_TOC.full_name = ".m_mount_info_toc"
M_MOUNT_INFO_TOC.nested_types = {}
M_MOUNT_INFO_TOC.enum_types = {}
M_MOUNT_INFO_TOC.fields = {M_MOUNT_INFO_TOC_OP_TYPE_FIELD, M_MOUNT_INFO_TOC_MOUNT_INFO_FIELD}
M_MOUNT_INFO_TOC.is_extendable = false
M_MOUNT_INFO_TOC.extensions = {}

m_mount_info_toc = protobuf.Message(M_MOUNT_INFO_TOC)

