--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_mount_skin_toc_pb')

M_MOUNT_SKIN_TOC = protobuf.Descriptor();
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_MOUNT_SKIN_TOC_SKIN_FIELD = protobuf.FieldDescriptor();

M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.name = "err_code"
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.full_name = ".m_mount_skin_toc.err_code"
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.number = 1
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.index = 0
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.label = 1
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.has_default_value = true
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.default_value = 0
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.type = 5
M_MOUNT_SKIN_TOC_ERR_CODE_FIELD.cpp_type = 1

M_MOUNT_SKIN_TOC_SKIN_FIELD.name = "skin"
M_MOUNT_SKIN_TOC_SKIN_FIELD.full_name = ".m_mount_skin_toc.skin"
M_MOUNT_SKIN_TOC_SKIN_FIELD.number = 2
M_MOUNT_SKIN_TOC_SKIN_FIELD.index = 1
M_MOUNT_SKIN_TOC_SKIN_FIELD.label = 1
M_MOUNT_SKIN_TOC_SKIN_FIELD.has_default_value = false
M_MOUNT_SKIN_TOC_SKIN_FIELD.default_value = nil
M_MOUNT_SKIN_TOC_SKIN_FIELD.message_type = p_kv_pb.P_KV
M_MOUNT_SKIN_TOC_SKIN_FIELD.type = 11
M_MOUNT_SKIN_TOC_SKIN_FIELD.cpp_type = 10

M_MOUNT_SKIN_TOC.name = "m_mount_skin_toc"
M_MOUNT_SKIN_TOC.full_name = ".m_mount_skin_toc"
M_MOUNT_SKIN_TOC.nested_types = {}
M_MOUNT_SKIN_TOC.enum_types = {}
M_MOUNT_SKIN_TOC.fields = {M_MOUNT_SKIN_TOC_ERR_CODE_FIELD, M_MOUNT_SKIN_TOC_SKIN_FIELD}
M_MOUNT_SKIN_TOC.is_extendable = false
M_MOUNT_SKIN_TOC.extensions = {}

m_mount_skin_toc = protobuf.Message(M_MOUNT_SKIN_TOC)

