--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_money_tree_i_tos_pb')

M_MONEY_TREE_I_TOS = protobuf.Descriptor();

M_MONEY_TREE_I_TOS.name = "m_money_tree_i_tos"
M_MONEY_TREE_I_TOS.full_name = ".m_money_tree_i_tos"
M_MONEY_TREE_I_TOS.nested_types = {}
M_MONEY_TREE_I_TOS.enum_types = {}
M_MONEY_TREE_I_TOS.fields = {}
M_MONEY_TREE_I_TOS.is_extendable = false
M_MONEY_TREE_I_TOS.extensions = {}

m_money_tree_i_tos = protobuf.Message(M_MONEY_TREE_I_TOS)

