--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_offline_solo_quit_tos_pb')

M_OFFLINE_SOLO_QUIT_TOS = protobuf.Descriptor();

M_OFFLINE_SOLO_QUIT_TOS.name = "m_offline_solo_quit_tos"
M_OFFLINE_SOLO_QUIT_TOS.full_name = ".m_offline_solo_quit_tos"
M_OFFLINE_SOLO_QUIT_TOS.nested_types = {}
M_OFFLINE_SOLO_QUIT_TOS.enum_types = {}
M_OFFLINE_SOLO_QUIT_TOS.fields = {}
M_OFFLINE_SOLO_QUIT_TOS.is_extendable = false
M_OFFLINE_SOLO_QUIT_TOS.extensions = {}

m_offline_solo_quit_tos = protobuf.Message(M_OFFLINE_SOLO_QUIT_TOS)

