--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_offline_solo_panel_tos_pb')

M_OFFLINE_SOLO_PANEL_TOS = protobuf.Descriptor();
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD = protobuf.FieldDescriptor();

M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.name = "type"
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.full_name = ".m_offline_solo_panel_tos.type"
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.number = 1
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.index = 0
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.label = 1
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.has_default_value = true
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.default_value = 0
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.type = 5
M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD.cpp_type = 1

M_OFFLINE_SOLO_PANEL_TOS.name = "m_offline_solo_panel_tos"
M_OFFLINE_SOLO_PANEL_TOS.full_name = ".m_offline_solo_panel_tos"
M_OFFLINE_SOLO_PANEL_TOS.nested_types = {}
M_OFFLINE_SOLO_PANEL_TOS.enum_types = {}
M_OFFLINE_SOLO_PANEL_TOS.fields = {M_OFFLINE_SOLO_PANEL_TOS_TYPE_FIELD}
M_OFFLINE_SOLO_PANEL_TOS.is_extendable = false
M_OFFLINE_SOLO_PANEL_TOS.extensions = {}

m_offline_solo_panel_tos = protobuf.Message(M_OFFLINE_SOLO_PANEL_TOS)

