--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_open_act_rank_pb = require("Protol.p_open_act_rank_pb")
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_oss_rank_toc_pb')

M_OSS_RANK_TOC = protobuf.Descriptor();
M_OSS_RANK_TOC_TYPE_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_RANK_REWARD_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_POWER_REWARD_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_PANIC_BUY_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_MANA_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_MANA_LIST_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_MANA_REWARD_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_RANK_LIST_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD = protobuf.FieldDescriptor();
M_OSS_RANK_TOC_RECHARGE_FIELD = protobuf.FieldDescriptor();

M_OSS_RANK_TOC_TYPE_FIELD.name = "type"
M_OSS_RANK_TOC_TYPE_FIELD.full_name = ".m_oss_rank_toc.type"
M_OSS_RANK_TOC_TYPE_FIELD.number = 1
M_OSS_RANK_TOC_TYPE_FIELD.index = 0
M_OSS_RANK_TOC_TYPE_FIELD.label = 1
M_OSS_RANK_TOC_TYPE_FIELD.has_default_value = true
M_OSS_RANK_TOC_TYPE_FIELD.default_value = 0
M_OSS_RANK_TOC_TYPE_FIELD.type = 5
M_OSS_RANK_TOC_TYPE_FIELD.cpp_type = 1

M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.name = "is_last_day"
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.full_name = ".m_oss_rank_toc.is_last_day"
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.number = 2
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.index = 1
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.label = 1
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.has_default_value = true
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.default_value = 0
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.type = 5
M_OSS_RANK_TOC_IS_LAST_DAY_FIELD.cpp_type = 1

M_OSS_RANK_TOC_RANK_REWARD_FIELD.name = "rank_reward"
M_OSS_RANK_TOC_RANK_REWARD_FIELD.full_name = ".m_oss_rank_toc.rank_reward"
M_OSS_RANK_TOC_RANK_REWARD_FIELD.number = 3
M_OSS_RANK_TOC_RANK_REWARD_FIELD.index = 2
M_OSS_RANK_TOC_RANK_REWARD_FIELD.label = 3
M_OSS_RANK_TOC_RANK_REWARD_FIELD.has_default_value = false
M_OSS_RANK_TOC_RANK_REWARD_FIELD.default_value = {}
M_OSS_RANK_TOC_RANK_REWARD_FIELD.message_type = p_kv_pb.P_KV
M_OSS_RANK_TOC_RANK_REWARD_FIELD.type = 11
M_OSS_RANK_TOC_RANK_REWARD_FIELD.cpp_type = 10

M_OSS_RANK_TOC_POWER_REWARD_FIELD.name = "power_reward"
M_OSS_RANK_TOC_POWER_REWARD_FIELD.full_name = ".m_oss_rank_toc.power_reward"
M_OSS_RANK_TOC_POWER_REWARD_FIELD.number = 4
M_OSS_RANK_TOC_POWER_REWARD_FIELD.index = 3
M_OSS_RANK_TOC_POWER_REWARD_FIELD.label = 3
M_OSS_RANK_TOC_POWER_REWARD_FIELD.has_default_value = false
M_OSS_RANK_TOC_POWER_REWARD_FIELD.default_value = {}
M_OSS_RANK_TOC_POWER_REWARD_FIELD.message_type = p_kv_pb.P_KV
M_OSS_RANK_TOC_POWER_REWARD_FIELD.type = 11
M_OSS_RANK_TOC_POWER_REWARD_FIELD.cpp_type = 10

M_OSS_RANK_TOC_PANIC_BUY_FIELD.name = "panic_buy"
M_OSS_RANK_TOC_PANIC_BUY_FIELD.full_name = ".m_oss_rank_toc.panic_buy"
M_OSS_RANK_TOC_PANIC_BUY_FIELD.number = 5
M_OSS_RANK_TOC_PANIC_BUY_FIELD.index = 4
M_OSS_RANK_TOC_PANIC_BUY_FIELD.label = 3
M_OSS_RANK_TOC_PANIC_BUY_FIELD.has_default_value = false
M_OSS_RANK_TOC_PANIC_BUY_FIELD.default_value = {}
M_OSS_RANK_TOC_PANIC_BUY_FIELD.message_type = p_kv_pb.P_KV
M_OSS_RANK_TOC_PANIC_BUY_FIELD.type = 11
M_OSS_RANK_TOC_PANIC_BUY_FIELD.cpp_type = 10

M_OSS_RANK_TOC_MANA_FIELD.name = "mana"
M_OSS_RANK_TOC_MANA_FIELD.full_name = ".m_oss_rank_toc.mana"
M_OSS_RANK_TOC_MANA_FIELD.number = 6
M_OSS_RANK_TOC_MANA_FIELD.index = 5
M_OSS_RANK_TOC_MANA_FIELD.label = 1
M_OSS_RANK_TOC_MANA_FIELD.has_default_value = true
M_OSS_RANK_TOC_MANA_FIELD.default_value = 0
M_OSS_RANK_TOC_MANA_FIELD.type = 5
M_OSS_RANK_TOC_MANA_FIELD.cpp_type = 1

M_OSS_RANK_TOC_MANA_LIST_FIELD.name = "mana_list"
M_OSS_RANK_TOC_MANA_LIST_FIELD.full_name = ".m_oss_rank_toc.mana_list"
M_OSS_RANK_TOC_MANA_LIST_FIELD.number = 7
M_OSS_RANK_TOC_MANA_LIST_FIELD.index = 6
M_OSS_RANK_TOC_MANA_LIST_FIELD.label = 3
M_OSS_RANK_TOC_MANA_LIST_FIELD.has_default_value = false
M_OSS_RANK_TOC_MANA_LIST_FIELD.default_value = {}
M_OSS_RANK_TOC_MANA_LIST_FIELD.message_type = p_kv_pb.P_KV
M_OSS_RANK_TOC_MANA_LIST_FIELD.type = 11
M_OSS_RANK_TOC_MANA_LIST_FIELD.cpp_type = 10

M_OSS_RANK_TOC_MANA_REWARD_FIELD.name = "mana_reward"
M_OSS_RANK_TOC_MANA_REWARD_FIELD.full_name = ".m_oss_rank_toc.mana_reward"
M_OSS_RANK_TOC_MANA_REWARD_FIELD.number = 8
M_OSS_RANK_TOC_MANA_REWARD_FIELD.index = 7
M_OSS_RANK_TOC_MANA_REWARD_FIELD.label = 3
M_OSS_RANK_TOC_MANA_REWARD_FIELD.has_default_value = false
M_OSS_RANK_TOC_MANA_REWARD_FIELD.default_value = {}
M_OSS_RANK_TOC_MANA_REWARD_FIELD.message_type = p_kv_pb.P_KV
M_OSS_RANK_TOC_MANA_REWARD_FIELD.type = 11
M_OSS_RANK_TOC_MANA_REWARD_FIELD.cpp_type = 10

M_OSS_RANK_TOC_RANK_LIST_FIELD.name = "rank_list"
M_OSS_RANK_TOC_RANK_LIST_FIELD.full_name = ".m_oss_rank_toc.rank_list"
M_OSS_RANK_TOC_RANK_LIST_FIELD.number = 9
M_OSS_RANK_TOC_RANK_LIST_FIELD.index = 8
M_OSS_RANK_TOC_RANK_LIST_FIELD.label = 3
M_OSS_RANK_TOC_RANK_LIST_FIELD.has_default_value = false
M_OSS_RANK_TOC_RANK_LIST_FIELD.default_value = {}
M_OSS_RANK_TOC_RANK_LIST_FIELD.message_type = p_open_act_rank_pb.P_OPEN_ACT_RANK
M_OSS_RANK_TOC_RANK_LIST_FIELD.type = 11
M_OSS_RANK_TOC_RANK_LIST_FIELD.cpp_type = 10

M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.name = "recharge_reward"
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.full_name = ".m_oss_rank_toc.recharge_reward"
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.number = 10
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.index = 9
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.label = 3
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.has_default_value = false
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.default_value = {}
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.message_type = p_kv_pb.P_KV
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.type = 11
M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD.cpp_type = 10

M_OSS_RANK_TOC_RECHARGE_FIELD.name = "recharge"
M_OSS_RANK_TOC_RECHARGE_FIELD.full_name = ".m_oss_rank_toc.recharge"
M_OSS_RANK_TOC_RECHARGE_FIELD.number = 11
M_OSS_RANK_TOC_RECHARGE_FIELD.index = 10
M_OSS_RANK_TOC_RECHARGE_FIELD.label = 1
M_OSS_RANK_TOC_RECHARGE_FIELD.has_default_value = true
M_OSS_RANK_TOC_RECHARGE_FIELD.default_value = 0
M_OSS_RANK_TOC_RECHARGE_FIELD.type = 5
M_OSS_RANK_TOC_RECHARGE_FIELD.cpp_type = 1

M_OSS_RANK_TOC.name = "m_oss_rank_toc"
M_OSS_RANK_TOC.full_name = ".m_oss_rank_toc"
M_OSS_RANK_TOC.nested_types = {}
M_OSS_RANK_TOC.enum_types = {}
M_OSS_RANK_TOC.fields = {M_OSS_RANK_TOC_TYPE_FIELD, M_OSS_RANK_TOC_IS_LAST_DAY_FIELD, M_OSS_RANK_TOC_RANK_REWARD_FIELD, M_OSS_RANK_TOC_POWER_REWARD_FIELD, M_OSS_RANK_TOC_PANIC_BUY_FIELD, M_OSS_RANK_TOC_MANA_FIELD, M_OSS_RANK_TOC_MANA_LIST_FIELD, M_OSS_RANK_TOC_MANA_REWARD_FIELD, M_OSS_RANK_TOC_RANK_LIST_FIELD, M_OSS_RANK_TOC_RECHARGE_REWARD_FIELD, M_OSS_RANK_TOC_RECHARGE_FIELD}
M_OSS_RANK_TOC.is_extendable = false
M_OSS_RANK_TOC.extensions = {}

m_oss_rank_toc = protobuf.Message(M_OSS_RANK_TOC)

