--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_otf_reward_tos_pb')

M_OTF_REWARD_TOS = protobuf.Descriptor();
M_OTF_REWARD_TOS_ID_FIELD = protobuf.FieldDescriptor();

M_OTF_REWARD_TOS_ID_FIELD.name = "id"
M_OTF_REWARD_TOS_ID_FIELD.full_name = ".m_otf_reward_tos.id"
M_OTF_REWARD_TOS_ID_FIELD.number = 1
M_OTF_REWARD_TOS_ID_FIELD.index = 0
M_OTF_REWARD_TOS_ID_FIELD.label = 1
M_OTF_REWARD_TOS_ID_FIELD.has_default_value = true
M_OTF_REWARD_TOS_ID_FIELD.default_value = 0
M_OTF_REWARD_TOS_ID_FIELD.type = 5
M_OTF_REWARD_TOS_ID_FIELD.cpp_type = 1

M_OTF_REWARD_TOS.name = "m_otf_reward_tos"
M_OTF_REWARD_TOS.full_name = ".m_otf_reward_tos"
M_OTF_REWARD_TOS.nested_types = {}
M_OTF_REWARD_TOS.enum_types = {}
M_OTF_REWARD_TOS.fields = {M_OTF_REWARD_TOS_ID_FIELD}
M_OTF_REWARD_TOS.is_extendable = false
M_OTF_REWARD_TOS.extensions = {}

m_otf_reward_tos = protobuf.Message(M_OTF_REWARD_TOS)

