--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_pet_spirit_update_toc_pb')

M_PET_SPIRIT_UPDATE_TOC = protobuf.Descriptor();
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD = protobuf.FieldDescriptor();

M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.name = "pet_spirit"
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.full_name = ".m_pet_spirit_update_toc.pet_spirit"
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.number = 1
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.index = 0
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.label = 1
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.has_default_value = false
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.default_value = nil
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.message_type = p_kv_pb.P_KV
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.type = 11
M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD.cpp_type = 10

M_PET_SPIRIT_UPDATE_TOC.name = "m_pet_spirit_update_toc"
M_PET_SPIRIT_UPDATE_TOC.full_name = ".m_pet_spirit_update_toc"
M_PET_SPIRIT_UPDATE_TOC.nested_types = {}
M_PET_SPIRIT_UPDATE_TOC.enum_types = {}
M_PET_SPIRIT_UPDATE_TOC.fields = {M_PET_SPIRIT_UPDATE_TOC_PET_SPIRIT_FIELD}
M_PET_SPIRIT_UPDATE_TOC.is_extendable = false
M_PET_SPIRIT_UPDATE_TOC.extensions = {}

m_pet_spirit_update_toc = protobuf.Message(M_PET_SPIRIT_UPDATE_TOC)

