--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_pet_change_tos_pb')

M_PET_CHANGE_TOS = protobuf.Descriptor();
M_PET_CHANGE_TOS_CUR_ID_FIELD = protobuf.FieldDescriptor();

M_PET_CHANGE_TOS_CUR_ID_FIELD.name = "cur_id"
M_PET_CHANGE_TOS_CUR_ID_FIELD.full_name = ".m_pet_change_tos.cur_id"
M_PET_CHANGE_TOS_CUR_ID_FIELD.number = 1
M_PET_CHANGE_TOS_CUR_ID_FIELD.index = 0
M_PET_CHANGE_TOS_CUR_ID_FIELD.label = 1
M_PET_CHANGE_TOS_CUR_ID_FIELD.has_default_value = true
M_PET_CHANGE_TOS_CUR_ID_FIELD.default_value = 0
M_PET_CHANGE_TOS_CUR_ID_FIELD.type = 5
M_PET_CHANGE_TOS_CUR_ID_FIELD.cpp_type = 1

M_PET_CHANGE_TOS.name = "m_pet_change_tos"
M_PET_CHANGE_TOS.full_name = ".m_pet_change_tos"
M_PET_CHANGE_TOS.nested_types = {}
M_PET_CHANGE_TOS.enum_types = {}
M_PET_CHANGE_TOS.fields = {M_PET_CHANGE_TOS_CUR_ID_FIELD}
M_PET_CHANGE_TOS.is_extendable = false
M_PET_CHANGE_TOS.extensions = {}

m_pet_change_tos = protobuf.Message(M_PET_CHANGE_TOS)

