--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_rank_info_tos_pb')

M_RANK_INFO_TOS = protobuf.Descriptor();
M_RANK_INFO_TOS_RANK_ID_FIELD = protobuf.FieldDescriptor();

M_RANK_INFO_TOS_RANK_ID_FIELD.name = "rank_id"
M_RANK_INFO_TOS_RANK_ID_FIELD.full_name = ".m_rank_info_tos.rank_id"
M_RANK_INFO_TOS_RANK_ID_FIELD.number = 1
M_RANK_INFO_TOS_RANK_ID_FIELD.index = 0
M_RANK_INFO_TOS_RANK_ID_FIELD.label = 1
M_RANK_INFO_TOS_RANK_ID_FIELD.has_default_value = true
M_RANK_INFO_TOS_RANK_ID_FIELD.default_value = 0
M_RANK_INFO_TOS_RANK_ID_FIELD.type = 5
M_RANK_INFO_TOS_RANK_ID_FIELD.cpp_type = 1

M_RANK_INFO_TOS.name = "m_rank_info_tos"
M_RANK_INFO_TOS.full_name = ".m_rank_info_tos"
M_RANK_INFO_TOS.nested_types = {}
M_RANK_INFO_TOS.enum_types = {}
M_RANK_INFO_TOS.fields = {M_RANK_INFO_TOS_RANK_ID_FIELD}
M_RANK_INFO_TOS.is_extendable = false
M_RANK_INFO_TOS.extensions = {}

m_rank_info_tos = protobuf.Message(M_RANK_INFO_TOS)

