--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_relive_up_tos_pb')

M_RELIVE_UP_TOS = protobuf.Descriptor();

M_RELIVE_UP_TOS.name = "m_relive_up_tos"
M_RELIVE_UP_TOS.full_name = ".m_relive_up_tos"
M_RELIVE_UP_TOS.nested_types = {}
M_RELIVE_UP_TOS.enum_types = {}
M_RELIVE_UP_TOS.fields = {}
M_RELIVE_UP_TOS.is_extendable = false
M_RELIVE_UP_TOS.extensions = {}

m_relive_up_tos = protobuf.Message(M_RELIVE_UP_TOS)

