--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_immortal_soul_down_tos_pb')

M_ROLE_IMMORTAL_SOUL_DOWN_TOS = protobuf.Descriptor();
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD = protobuf.FieldDescriptor();

M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.name = "pos"
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.full_name = ".m_role_immortal_soul_down_tos.pos"
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.number = 1
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.index = 0
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.label = 1
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.has_default_value = true
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.default_value = 0
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.type = 5
M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD.cpp_type = 1

M_ROLE_IMMORTAL_SOUL_DOWN_TOS.name = "m_role_immortal_soul_down_tos"
M_ROLE_IMMORTAL_SOUL_DOWN_TOS.full_name = ".m_role_immortal_soul_down_tos"
M_ROLE_IMMORTAL_SOUL_DOWN_TOS.nested_types = {}
M_ROLE_IMMORTAL_SOUL_DOWN_TOS.enum_types = {}
M_ROLE_IMMORTAL_SOUL_DOWN_TOS.fields = {M_ROLE_IMMORTAL_SOUL_DOWN_TOS_POS_FIELD}
M_ROLE_IMMORTAL_SOUL_DOWN_TOS.is_extendable = false
M_ROLE_IMMORTAL_SOUL_DOWN_TOS.extensions = {}

m_role_immortal_soul_down_tos = protobuf.Message(M_ROLE_IMMORTAL_SOUL_DOWN_TOS)

