--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_week_card_del_toc_pb')

M_ROLE_WEEK_CARD_DEL_TOC = protobuf.Descriptor();
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD = protobuf.FieldDescriptor();

M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.name = "list"
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.full_name = ".m_role_week_card_del_toc.list"
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.number = 1
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.index = 0
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.label = 3
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.has_default_value = false
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.default_value = {}
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.type = 5
M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD.cpp_type = 1

M_ROLE_WEEK_CARD_DEL_TOC.name = "m_role_week_card_del_toc"
M_ROLE_WEEK_CARD_DEL_TOC.full_name = ".m_role_week_card_del_toc"
M_ROLE_WEEK_CARD_DEL_TOC.nested_types = {}
M_ROLE_WEEK_CARD_DEL_TOC.enum_types = {}
M_ROLE_WEEK_CARD_DEL_TOC.fields = {M_ROLE_WEEK_CARD_DEL_TOC_LIST_FIELD}
M_ROLE_WEEK_CARD_DEL_TOC.is_extendable = false
M_ROLE_WEEK_CARD_DEL_TOC.extensions = {}

m_role_week_card_del_toc = protobuf.Message(M_ROLE_WEEK_CARD_DEL_TOC)

