--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_nature_goods_refine_tos_pb')

M_ROLE_NATURE_GOODS_REFINE_TOS = protobuf.Descriptor();
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD = protobuf.FieldDescriptor();

M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.name = "rune_ids"
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.full_name = ".m_role_nature_goods_refine_tos.rune_ids"
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.number = 1
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.index = 0
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.label = 3
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.has_default_value = false
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.default_value = {}
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.type = 5
M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD.cpp_type = 1

M_ROLE_NATURE_GOODS_REFINE_TOS.name = "m_role_nature_goods_refine_tos"
M_ROLE_NATURE_GOODS_REFINE_TOS.full_name = ".m_role_nature_goods_refine_tos"
M_ROLE_NATURE_GOODS_REFINE_TOS.nested_types = {}
M_ROLE_NATURE_GOODS_REFINE_TOS.enum_types = {}
M_ROLE_NATURE_GOODS_REFINE_TOS.fields = {M_ROLE_NATURE_GOODS_REFINE_TOS_RUNE_IDS_FIELD}
M_ROLE_NATURE_GOODS_REFINE_TOS.is_extendable = false
M_ROLE_NATURE_GOODS_REFINE_TOS.extensions = {}

m_role_nature_goods_refine_tos = protobuf.Message(M_ROLE_NATURE_GOODS_REFINE_TOS)

