--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_family_mission_ask_pb = require("Protol.p_family_mission_ask_pb")
module('Protol.m_role_family_asm_ask_info_toc_pb')

M_ROLE_FAMILY_ASM_ASK_INFO_TOC = protobuf.Descriptor();
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD = protobuf.FieldDescriptor();
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD = protobuf.FieldDescriptor();

M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.name = "inspire"
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.full_name = ".m_role_family_asm_ask_info_toc.inspire"
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.number = 1
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.index = 0
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.label = 1
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.has_default_value = true
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.default_value = 0
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.type = 5
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD.cpp_type = 1

M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.name = "mission_ask"
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.full_name = ".m_role_family_asm_ask_info_toc.mission_ask"
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.number = 2
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.index = 1
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.label = 3
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.has_default_value = false
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.default_value = {}
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.message_type = p_family_mission_ask_pb.P_FAMILY_MISSION_ASK
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.type = 11
M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD.cpp_type = 10

M_ROLE_FAMILY_ASM_ASK_INFO_TOC.name = "m_role_family_asm_ask_info_toc"
M_ROLE_FAMILY_ASM_ASK_INFO_TOC.full_name = ".m_role_family_asm_ask_info_toc"
M_ROLE_FAMILY_ASM_ASK_INFO_TOC.nested_types = {}
M_ROLE_FAMILY_ASM_ASK_INFO_TOC.enum_types = {}
M_ROLE_FAMILY_ASM_ASK_INFO_TOC.fields = {M_ROLE_FAMILY_ASM_ASK_INFO_TOC_INSPIRE_FIELD, M_ROLE_FAMILY_ASM_ASK_INFO_TOC_MISSION_ASK_FIELD}
M_ROLE_FAMILY_ASM_ASK_INFO_TOC.is_extendable = false
M_ROLE_FAMILY_ASM_ASK_INFO_TOC.extensions = {}

m_role_family_asm_ask_info_toc = protobuf.Message(M_ROLE_FAMILY_ASM_ASK_INFO_TOC)

