--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_family_asm_ref_tos_pb')

M_ROLE_FAMILY_ASM_REF_TOS = protobuf.Descriptor();
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD = protobuf.FieldDescriptor();

M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.name = "type"
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.full_name = ".m_role_family_asm_ref_tos.type"
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.number = 1
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.index = 0
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.label = 1
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.has_default_value = true
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.default_value = 0
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.type = 5
M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD.cpp_type = 1

M_ROLE_FAMILY_ASM_REF_TOS.name = "m_role_family_asm_ref_tos"
M_ROLE_FAMILY_ASM_REF_TOS.full_name = ".m_role_family_asm_ref_tos"
M_ROLE_FAMILY_ASM_REF_TOS.nested_types = {}
M_ROLE_FAMILY_ASM_REF_TOS.enum_types = {}
M_ROLE_FAMILY_ASM_REF_TOS.fields = {M_ROLE_FAMILY_ASM_REF_TOS_TYPE_FIELD}
M_ROLE_FAMILY_ASM_REF_TOS.is_extendable = false
M_ROLE_FAMILY_ASM_REF_TOS.extensions = {}

m_role_family_asm_ref_tos = protobuf.Message(M_ROLE_FAMILY_ASM_REF_TOS)

