--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_week_card_reward_tos_pb')

M_ROLE_WEEK_CARD_REWARD_TOS = protobuf.Descriptor();
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD = protobuf.FieldDescriptor();
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD = protobuf.FieldDescriptor();

M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.name = "id"
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.full_name = ".m_role_week_card_reward_tos.id"
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.number = 1
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.index = 0
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.label = 1
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.has_default_value = true
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.default_value = 0
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.type = 5
M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD.cpp_type = 1

M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.name = "day"
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.full_name = ".m_role_week_card_reward_tos.day"
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.number = 2
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.index = 1
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.label = 1
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.has_default_value = true
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.default_value = 0
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.type = 5
M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD.cpp_type = 1

M_ROLE_WEEK_CARD_REWARD_TOS.name = "m_role_week_card_reward_tos"
M_ROLE_WEEK_CARD_REWARD_TOS.full_name = ".m_role_week_card_reward_tos"
M_ROLE_WEEK_CARD_REWARD_TOS.nested_types = {}
M_ROLE_WEEK_CARD_REWARD_TOS.enum_types = {}
M_ROLE_WEEK_CARD_REWARD_TOS.fields = {M_ROLE_WEEK_CARD_REWARD_TOS_ID_FIELD, M_ROLE_WEEK_CARD_REWARD_TOS_DAY_FIELD}
M_ROLE_WEEK_CARD_REWARD_TOS.is_extendable = false
M_ROLE_WEEK_CARD_REWARD_TOS.extensions = {}

m_role_week_card_reward_tos = protobuf.Message(M_ROLE_WEEK_CARD_REWARD_TOS)

