--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_addict_tourist_end_toc_pb')

M_ROLE_ADDICT_TOURIST_END_TOC = protobuf.Descriptor();
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD = protobuf.FieldDescriptor();

M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.name = "min"
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.full_name = ".m_role_addict_tourist_end_toc.min"
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.number = 1
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.index = 0
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.label = 1
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.has_default_value = true
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.default_value = 0
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.type = 5
M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD.cpp_type = 1

M_ROLE_ADDICT_TOURIST_END_TOC.name = "m_role_addict_tourist_end_toc"
M_ROLE_ADDICT_TOURIST_END_TOC.full_name = ".m_role_addict_tourist_end_toc"
M_ROLE_ADDICT_TOURIST_END_TOC.nested_types = {}
M_ROLE_ADDICT_TOURIST_END_TOC.enum_types = {}
M_ROLE_ADDICT_TOURIST_END_TOC.fields = {M_ROLE_ADDICT_TOURIST_END_TOC_MIN_FIELD}
M_ROLE_ADDICT_TOURIST_END_TOC.is_extendable = false
M_ROLE_ADDICT_TOURIST_END_TOC.extensions = {}

m_role_addict_tourist_end_toc = protobuf.Message(M_ROLE_ADDICT_TOURIST_END_TOC)

