--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_fgb_rank_pb = require("Protol.p_fgb_rank_pb")
module('Protol.m_role_fgb_rank_i_toc_pb')

M_ROLE_FGB_RANK_I_TOC = protobuf.Descriptor();
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD = protobuf.FieldDescriptor();
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD = protobuf.FieldDescriptor();
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD = protobuf.FieldDescriptor();
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD = protobuf.FieldDescriptor();
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD = protobuf.FieldDescriptor();

M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.name = "inspire"
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.full_name = ".m_role_fgb_rank_i_toc.inspire"
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.number = 1
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.index = 0
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.label = 1
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.has_default_value = true
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.default_value = 0
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.type = 5
M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD.cpp_type = 1

M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.name = "all_inspire"
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.full_name = ".m_role_fgb_rank_i_toc.all_inspire"
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.number = 2
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.index = 1
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.label = 1
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.has_default_value = true
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.default_value = 0
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.type = 5
M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD.cpp_type = 1

M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.name = "type"
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.full_name = ".m_role_fgb_rank_i_toc.type"
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.number = 3
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.index = 2
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.label = 1
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.has_default_value = true
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.default_value = 0
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.type = 5
M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD.cpp_type = 1

M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.name = "self"
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.full_name = ".m_role_fgb_rank_i_toc.self"
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.number = 4
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.index = 3
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.label = 1
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.has_default_value = false
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.default_value = ""
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.type = 9
M_ROLE_FGB_RANK_I_TOC_SELF_FIELD.cpp_type = 9

M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.name = "list"
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.full_name = ".m_role_fgb_rank_i_toc.list"
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.number = 5
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.index = 4
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.label = 3
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.has_default_value = false
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.default_value = {}
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.message_type = p_fgb_rank_pb.P_FGB_RANK
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.type = 11
M_ROLE_FGB_RANK_I_TOC_LIST_FIELD.cpp_type = 10

M_ROLE_FGB_RANK_I_TOC.name = "m_role_fgb_rank_i_toc"
M_ROLE_FGB_RANK_I_TOC.full_name = ".m_role_fgb_rank_i_toc"
M_ROLE_FGB_RANK_I_TOC.nested_types = {}
M_ROLE_FGB_RANK_I_TOC.enum_types = {}
M_ROLE_FGB_RANK_I_TOC.fields = {M_ROLE_FGB_RANK_I_TOC_INSPIRE_FIELD, M_ROLE_FGB_RANK_I_TOC_ALL_INSPIRE_FIELD, M_ROLE_FGB_RANK_I_TOC_TYPE_FIELD, M_ROLE_FGB_RANK_I_TOC_SELF_FIELD, M_ROLE_FGB_RANK_I_TOC_LIST_FIELD}
M_ROLE_FGB_RANK_I_TOC.is_extendable = false
M_ROLE_FGB_RANK_I_TOC.extensions = {}

m_role_fgb_rank_i_toc = protobuf.Message(M_ROLE_FGB_RANK_I_TOC)

