--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_handbook_upgrade_tos_pb')

M_ROLE_HANDBOOK_UPGRADE_TOS = protobuf.Descriptor();
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD = protobuf.FieldDescriptor();

M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.name = "card_id"
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.full_name = ".m_role_handbook_upgrade_tos.card_id"
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.number = 1
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.index = 0
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.label = 1
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.has_default_value = true
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.default_value = 0
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.type = 5
M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD.cpp_type = 1

M_ROLE_HANDBOOK_UPGRADE_TOS.name = "m_role_handbook_upgrade_tos"
M_ROLE_HANDBOOK_UPGRADE_TOS.full_name = ".m_role_handbook_upgrade_tos"
M_ROLE_HANDBOOK_UPGRADE_TOS.nested_types = {}
M_ROLE_HANDBOOK_UPGRADE_TOS.enum_types = {}
M_ROLE_HANDBOOK_UPGRADE_TOS.fields = {M_ROLE_HANDBOOK_UPGRADE_TOS_CARD_ID_FIELD}
M_ROLE_HANDBOOK_UPGRADE_TOS.is_extendable = false
M_ROLE_HANDBOOK_UPGRADE_TOS.extensions = {}

m_role_handbook_upgrade_tos = protobuf.Message(M_ROLE_HANDBOOK_UPGRADE_TOS)

