--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_bg_act_pb = require("Protol.p_bg_act_pb")
local p_kvt_pb = require("Protol.p_kvt_pb")
local p_tta_pb = require("Protol.p_tta_pb")
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_role_bg_tta_toc_pb')

M_ROLE_BG_TTA_TOC = protobuf.Descriptor();
M_ROLE_BG_TTA_TOC_INFO_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_GOLD_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_RARE_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_NORMAL_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_RARE_I_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD = protobuf.FieldDescriptor();
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD = protobuf.FieldDescriptor();

M_ROLE_BG_TTA_TOC_INFO_FIELD.name = "info"
M_ROLE_BG_TTA_TOC_INFO_FIELD.full_name = ".m_role_bg_tta_toc.info"
M_ROLE_BG_TTA_TOC_INFO_FIELD.number = 1
M_ROLE_BG_TTA_TOC_INFO_FIELD.index = 0
M_ROLE_BG_TTA_TOC_INFO_FIELD.label = 1
M_ROLE_BG_TTA_TOC_INFO_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_INFO_FIELD.default_value = nil
M_ROLE_BG_TTA_TOC_INFO_FIELD.message_type = p_bg_act_pb.P_BG_ACT
M_ROLE_BG_TTA_TOC_INFO_FIELD.type = 11
M_ROLE_BG_TTA_TOC_INFO_FIELD.cpp_type = 10

M_ROLE_BG_TTA_TOC_GOLD_FIELD.name = "gold"
M_ROLE_BG_TTA_TOC_GOLD_FIELD.full_name = ".m_role_bg_tta_toc.gold"
M_ROLE_BG_TTA_TOC_GOLD_FIELD.number = 2
M_ROLE_BG_TTA_TOC_GOLD_FIELD.index = 1
M_ROLE_BG_TTA_TOC_GOLD_FIELD.label = 1
M_ROLE_BG_TTA_TOC_GOLD_FIELD.has_default_value = true
M_ROLE_BG_TTA_TOC_GOLD_FIELD.default_value = 0
M_ROLE_BG_TTA_TOC_GOLD_FIELD.type = 5
M_ROLE_BG_TTA_TOC_GOLD_FIELD.cpp_type = 1

M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.name = "price_region"
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.full_name = ".m_role_bg_tta_toc.price_region"
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.number = 3
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.index = 2
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.label = 3
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.message_type = p_kvt_pb.P_KVT
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.type = 11
M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD.cpp_type = 10

M_ROLE_BG_TTA_TOC_RARE_FIELD.name = "rare"
M_ROLE_BG_TTA_TOC_RARE_FIELD.full_name = ".m_role_bg_tta_toc.rare"
M_ROLE_BG_TTA_TOC_RARE_FIELD.number = 4
M_ROLE_BG_TTA_TOC_RARE_FIELD.index = 3
M_ROLE_BG_TTA_TOC_RARE_FIELD.label = 3
M_ROLE_BG_TTA_TOC_RARE_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_RARE_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_RARE_FIELD.message_type = p_tta_pb.P_TTA
M_ROLE_BG_TTA_TOC_RARE_FIELD.type = 11
M_ROLE_BG_TTA_TOC_RARE_FIELD.cpp_type = 10

M_ROLE_BG_TTA_TOC_NORMAL_FIELD.name = "normal"
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.full_name = ".m_role_bg_tta_toc.normal"
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.number = 5
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.index = 4
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.label = 3
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.message_type = p_tta_pb.P_TTA
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.type = 11
M_ROLE_BG_TTA_TOC_NORMAL_FIELD.cpp_type = 10

M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.name = "rare_choice"
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.full_name = ".m_role_bg_tta_toc.rare_choice"
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.number = 6
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.index = 5
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.label = 1
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.has_default_value = true
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.default_value = 0
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.type = 5
M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD.cpp_type = 1

M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.name = "normal_choice"
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.full_name = ".m_role_bg_tta_toc.normal_choice"
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.number = 7
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.index = 6
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.label = 3
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.type = 5
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD.cpp_type = 1

M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.name = "open_id"
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.full_name = ".m_role_bg_tta_toc.open_id"
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.number = 8
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.index = 7
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.label = 3
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.message_type = p_kv_pb.P_KV
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.type = 11
M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD.cpp_type = 10

M_ROLE_BG_TTA_TOC_RARE_I_FIELD.name = "rare_i"
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.full_name = ".m_role_bg_tta_toc.rare_i"
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.number = 9
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.index = 8
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.label = 3
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.message_type = p_tta_pb.P_TTA
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.type = 11
M_ROLE_BG_TTA_TOC_RARE_I_FIELD.cpp_type = 10

M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.name = "normal_i"
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.full_name = ".m_role_bg_tta_toc.normal_i"
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.number = 10
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.index = 9
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.label = 3
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.message_type = p_tta_pb.P_TTA
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.type = 11
M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD.cpp_type = 10

M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.name = "rare_choice_i"
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.full_name = ".m_role_bg_tta_toc.rare_choice_i"
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.number = 11
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.index = 10
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.label = 1
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.has_default_value = true
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.default_value = 0
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.type = 5
M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD.cpp_type = 1

M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.name = "normal_choice_i"
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.full_name = ".m_role_bg_tta_toc.normal_choice_i"
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.number = 12
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.index = 11
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.label = 3
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.type = 5
M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD.cpp_type = 1

M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.name = "open_id_i"
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.full_name = ".m_role_bg_tta_toc.open_id_i"
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.number = 13
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.index = 12
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.label = 3
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.has_default_value = false
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.default_value = {}
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.message_type = p_kv_pb.P_KV
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.type = 11
M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD.cpp_type = 10

M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.name = "open_layer"
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.full_name = ".m_role_bg_tta_toc.open_layer"
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.number = 14
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.index = 13
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.label = 1
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.has_default_value = true
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.default_value = 0
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.type = 5
M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD.cpp_type = 1

M_ROLE_BG_TTA_TOC.name = "m_role_bg_tta_toc"
M_ROLE_BG_TTA_TOC.full_name = ".m_role_bg_tta_toc"
M_ROLE_BG_TTA_TOC.nested_types = {}
M_ROLE_BG_TTA_TOC.enum_types = {}
M_ROLE_BG_TTA_TOC.fields = {M_ROLE_BG_TTA_TOC_INFO_FIELD, M_ROLE_BG_TTA_TOC_GOLD_FIELD, M_ROLE_BG_TTA_TOC_PRICE_REGION_FIELD, M_ROLE_BG_TTA_TOC_RARE_FIELD, M_ROLE_BG_TTA_TOC_NORMAL_FIELD, M_ROLE_BG_TTA_TOC_RARE_CHOICE_FIELD, M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_FIELD, M_ROLE_BG_TTA_TOC_OPEN_ID_FIELD, M_ROLE_BG_TTA_TOC_RARE_I_FIELD, M_ROLE_BG_TTA_TOC_NORMAL_I_FIELD, M_ROLE_BG_TTA_TOC_RARE_CHOICE_I_FIELD, M_ROLE_BG_TTA_TOC_NORMAL_CHOICE_I_FIELD, M_ROLE_BG_TTA_TOC_OPEN_ID_I_FIELD, M_ROLE_BG_TTA_TOC_OPEN_LAYER_FIELD}
M_ROLE_BG_TTA_TOC.is_extendable = false
M_ROLE_BG_TTA_TOC.extensions = {}

m_role_bg_tta_toc = protobuf.Message(M_ROLE_BG_TTA_TOC)

