--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_map_end_toc_pb')

M_ROLE_MAP_END_TOC = protobuf.Descriptor();
M_ROLE_MAP_END_TOC_MAP_ID_FIELD = protobuf.FieldDescriptor();
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD = protobuf.FieldDescriptor();

M_ROLE_MAP_END_TOC_MAP_ID_FIELD.name = "map_id"
M_ROLE_MAP_END_TOC_MAP_ID_FIELD.full_name = ".m_role_map_end_toc.map_id"
M_ROLE_MAP_END_TOC_MAP_ID_FIELD.number = 1
M_ROLE_MAP_END_TOC_MAP_ID_FIELD.index = 0
M_ROLE_MAP_END_TOC_MAP_ID_FIELD.label = 1
M_ROLE_MAP_END_TOC_MAP_ID_FIELD.has_default_value = true
M_ROLE_MAP_END_TOC_MAP_ID_FIELD.default_value = 0
M_ROLE_MAP_END_TOC_MAP_ID_FIELD.type = 5
M_ROLE_MAP_END_TOC_MAP_ID_FIELD.cpp_type = 1

M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.name = "count_down"
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.full_name = ".m_role_map_end_toc.count_down"
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.number = 2
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.index = 1
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.label = 1
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.has_default_value = true
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.default_value = 0
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.type = 5
M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD.cpp_type = 1

M_ROLE_MAP_END_TOC.name = "m_role_map_end_toc"
M_ROLE_MAP_END_TOC.full_name = ".m_role_map_end_toc"
M_ROLE_MAP_END_TOC.nested_types = {}
M_ROLE_MAP_END_TOC.enum_types = {}
M_ROLE_MAP_END_TOC.fields = {M_ROLE_MAP_END_TOC_MAP_ID_FIELD, M_ROLE_MAP_END_TOC_COUNT_DOWN_FIELD}
M_ROLE_MAP_END_TOC.is_extendable = false
M_ROLE_MAP_END_TOC.extensions = {}

m_role_map_end_toc = protobuf.Message(M_ROLE_MAP_END_TOC)

