--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_role_mining_plunder_tos_pb')

M_ROLE_MINING_PLUNDER_TOS = protobuf.Descriptor();
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD = protobuf.FieldDescriptor();

M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.name = "object_id"
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.full_name = ".m_role_mining_plunder_tos.object_id"
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.number = 1
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.index = 0
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.label = 1
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.has_default_value = true
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.default_value = 0
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.type = 3
M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD.cpp_type = 2

M_ROLE_MINING_PLUNDER_TOS.name = "m_role_mining_plunder_tos"
M_ROLE_MINING_PLUNDER_TOS.full_name = ".m_role_mining_plunder_tos"
M_ROLE_MINING_PLUNDER_TOS.nested_types = {}
M_ROLE_MINING_PLUNDER_TOS.enum_types = {}
M_ROLE_MINING_PLUNDER_TOS.fields = {M_ROLE_MINING_PLUNDER_TOS_OBJECT_ID_FIELD}
M_ROLE_MINING_PLUNDER_TOS.is_extendable = false
M_ROLE_MINING_PLUNDER_TOS.extensions = {}

m_role_mining_plunder_tos = protobuf.Message(M_ROLE_MINING_PLUNDER_TOS)

