--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_escort_pb = require("Protol.p_escort_pb")
module('Protol.m_role_escort_list_toc_pb')

M_ROLE_ESCORT_LIST_TOC = protobuf.Descriptor();
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD = protobuf.FieldDescriptor();

M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.name = "list"
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.full_name = ".m_role_escort_list_toc.list"
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.number = 1
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.index = 0
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.label = 3
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.has_default_value = false
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.default_value = {}
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.message_type = p_escort_pb.P_ESCORT
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.type = 11
M_ROLE_ESCORT_LIST_TOC_LIST_FIELD.cpp_type = 10

M_ROLE_ESCORT_LIST_TOC.name = "m_role_escort_list_toc"
M_ROLE_ESCORT_LIST_TOC.full_name = ".m_role_escort_list_toc"
M_ROLE_ESCORT_LIST_TOC.nested_types = {}
M_ROLE_ESCORT_LIST_TOC.enum_types = {}
M_ROLE_ESCORT_LIST_TOC.fields = {M_ROLE_ESCORT_LIST_TOC_LIST_FIELD}
M_ROLE_ESCORT_LIST_TOC.is_extendable = false
M_ROLE_ESCORT_LIST_TOC.extensions = {}

m_role_escort_list_toc = protobuf.Message(M_ROLE_ESCORT_LIST_TOC)

