--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_rune_exp_update_toc_pb')

M_RUNE_EXP_UPDATE_TOC = protobuf.Descriptor();
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD = protobuf.FieldDescriptor();

M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.name = "exp"
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.full_name = ".m_rune_exp_update_toc.exp"
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.number = 1
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.index = 0
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.label = 1
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.has_default_value = true
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.default_value = 0
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.type = 5
M_RUNE_EXP_UPDATE_TOC_EXP_FIELD.cpp_type = 1

M_RUNE_EXP_UPDATE_TOC.name = "m_rune_exp_update_toc"
M_RUNE_EXP_UPDATE_TOC.full_name = ".m_rune_exp_update_toc"
M_RUNE_EXP_UPDATE_TOC.nested_types = {}
M_RUNE_EXP_UPDATE_TOC.enum_types = {}
M_RUNE_EXP_UPDATE_TOC.fields = {M_RUNE_EXP_UPDATE_TOC_EXP_FIELD}
M_RUNE_EXP_UPDATE_TOC.is_extendable = false
M_RUNE_EXP_UPDATE_TOC.extensions = {}

m_rune_exp_update_toc = protobuf.Message(M_RUNE_EXP_UPDATE_TOC)

