--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_skill_seal_reset_tos_pb')

M_SKILL_SEAL_RESET_TOS = protobuf.Descriptor();
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD = protobuf.FieldDescriptor();

M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.name = "skill_id"
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.full_name = ".m_skill_seal_reset_tos.skill_id"
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.number = 1
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.index = 0
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.label = 1
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.has_default_value = true
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.default_value = 0
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.type = 5
M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD.cpp_type = 1

M_SKILL_SEAL_RESET_TOS.name = "m_skill_seal_reset_tos"
M_SKILL_SEAL_RESET_TOS.full_name = ".m_skill_seal_reset_tos"
M_SKILL_SEAL_RESET_TOS.nested_types = {}
M_SKILL_SEAL_RESET_TOS.enum_types = {}
M_SKILL_SEAL_RESET_TOS.fields = {M_SKILL_SEAL_RESET_TOS_SKILL_ID_FIELD}
M_SKILL_SEAL_RESET_TOS.is_extendable = false
M_SKILL_SEAL_RESET_TOS.extensions = {}

m_skill_seal_reset_tos = protobuf.Message(M_SKILL_SEAL_RESET_TOS)

