--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_solo_rank_pb = require("Protol.p_solo_rank_pb")
module('Protol.m_solo_rank_info_toc_pb')

M_SOLO_RANK_INFO_TOC = protobuf.Descriptor();
M_SOLO_RANK_INFO_TOC_RANKS_FIELD = protobuf.FieldDescriptor();
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD = protobuf.FieldDescriptor();

M_SOLO_RANK_INFO_TOC_RANKS_FIELD.name = "ranks"
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.full_name = ".m_solo_rank_info_toc.ranks"
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.number = 1
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.index = 0
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.label = 3
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.has_default_value = false
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.default_value = {}
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.message_type = p_solo_rank_pb.P_SOLO_RANK
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.type = 11
M_SOLO_RANK_INFO_TOC_RANKS_FIELD.cpp_type = 10

M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.name = "my_rank"
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.full_name = ".m_solo_rank_info_toc.my_rank"
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.number = 2
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.index = 1
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.label = 1
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.has_default_value = false
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.default_value = nil
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.message_type = p_solo_rank_pb.P_SOLO_RANK
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.type = 11
M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD.cpp_type = 10

M_SOLO_RANK_INFO_TOC.name = "m_solo_rank_info_toc"
M_SOLO_RANK_INFO_TOC.full_name = ".m_solo_rank_info_toc"
M_SOLO_RANK_INFO_TOC.nested_types = {}
M_SOLO_RANK_INFO_TOC.enum_types = {}
M_SOLO_RANK_INFO_TOC.fields = {M_SOLO_RANK_INFO_TOC_RANKS_FIELD, M_SOLO_RANK_INFO_TOC_MY_RANK_FIELD}
M_SOLO_RANK_INFO_TOC.is_extendable = false
M_SOLO_RANK_INFO_TOC.extensions = {}

m_solo_rank_info_toc = protobuf.Message(M_SOLO_RANK_INFO_TOC)

