--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_equip_pb = require("Protol.p_equip_pb")
module('Protol.m_stone_punch_toc_pb')

M_STONE_PUNCH_TOC = protobuf.Descriptor();
M_STONE_PUNCH_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_STONE_PUNCH_TOC_EQUIP_FIELD = protobuf.FieldDescriptor();

M_STONE_PUNCH_TOC_ERR_CODE_FIELD.name = "err_code"
M_STONE_PUNCH_TOC_ERR_CODE_FIELD.full_name = ".m_stone_punch_toc.err_code"
M_STONE_PUNCH_TOC_ERR_CODE_FIELD.number = 1
M_STONE_PUNCH_TOC_ERR_CODE_FIELD.index = 0
M_STONE_PUNCH_TOC_ERR_CODE_FIELD.label = 1
M_STONE_PUNCH_TOC_ERR_CODE_FIELD.has_default_value = true
M_STONE_PUNCH_TOC_ERR_CODE_FIELD.default_value = 0
M_STONE_PUNCH_TOC_ERR_CODE_FIELD.type = 5
M_STONE_PUNCH_TOC_ERR_CODE_FIELD.cpp_type = 1

M_STONE_PUNCH_TOC_EQUIP_FIELD.name = "equip"
M_STONE_PUNCH_TOC_EQUIP_FIELD.full_name = ".m_stone_punch_toc.equip"
M_STONE_PUNCH_TOC_EQUIP_FIELD.number = 2
M_STONE_PUNCH_TOC_EQUIP_FIELD.index = 1
M_STONE_PUNCH_TOC_EQUIP_FIELD.label = 1
M_STONE_PUNCH_TOC_EQUIP_FIELD.has_default_value = false
M_STONE_PUNCH_TOC_EQUIP_FIELD.default_value = nil
M_STONE_PUNCH_TOC_EQUIP_FIELD.message_type = p_equip_pb.P_EQUIP
M_STONE_PUNCH_TOC_EQUIP_FIELD.type = 11
M_STONE_PUNCH_TOC_EQUIP_FIELD.cpp_type = 10

M_STONE_PUNCH_TOC.name = "m_stone_punch_toc"
M_STONE_PUNCH_TOC.full_name = ".m_stone_punch_toc"
M_STONE_PUNCH_TOC.nested_types = {}
M_STONE_PUNCH_TOC.enum_types = {}
M_STONE_PUNCH_TOC.fields = {M_STONE_PUNCH_TOC_ERR_CODE_FIELD, M_STONE_PUNCH_TOC_EQUIP_FIELD}
M_STONE_PUNCH_TOC.is_extendable = false
M_STONE_PUNCH_TOC.extensions = {}

m_stone_punch_toc = protobuf.Message(M_STONE_PUNCH_TOC)

