--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_suit_upgrade_star_toc_pb')

M_SUIT_UPGRADE_STAR_TOC = protobuf.Descriptor();
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD = protobuf.FieldDescriptor();

M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.name = "err_code"
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.full_name = ".m_suit_upgrade_star_toc.err_code"
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.number = 1
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.index = 0
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.label = 1
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.has_default_value = true
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.default_value = 0
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.type = 5
M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD.cpp_type = 1

M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.name = "place_id"
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.full_name = ".m_suit_upgrade_star_toc.place_id"
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.number = 2
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.index = 1
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.label = 1
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.has_default_value = true
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.default_value = 0
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.type = 5
M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD.cpp_type = 1

M_SUIT_UPGRADE_STAR_TOC.name = "m_suit_upgrade_star_toc"
M_SUIT_UPGRADE_STAR_TOC.full_name = ".m_suit_upgrade_star_toc"
M_SUIT_UPGRADE_STAR_TOC.nested_types = {}
M_SUIT_UPGRADE_STAR_TOC.enum_types = {}
M_SUIT_UPGRADE_STAR_TOC.fields = {M_SUIT_UPGRADE_STAR_TOC_ERR_CODE_FIELD, M_SUIT_UPGRADE_STAR_TOC_PLACE_ID_FIELD}
M_SUIT_UPGRADE_STAR_TOC.is_extendable = false
M_SUIT_UPGRADE_STAR_TOC.extensions = {}

m_suit_upgrade_star_toc = protobuf.Message(M_SUIT_UPGRADE_STAR_TOC)

