--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_summit_invest_gold_buy_tos_pb')

M_SUMMIT_INVEST_GOLD_BUY_TOS = protobuf.Descriptor();
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD = protobuf.FieldDescriptor();

M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.name = "summit_invest_gold"
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.full_name = ".m_summit_invest_gold_buy_tos.summit_invest_gold"
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.number = 1
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.index = 0
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.label = 1
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.has_default_value = true
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.default_value = 0
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.type = 5
M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD.cpp_type = 1

M_SUMMIT_INVEST_GOLD_BUY_TOS.name = "m_summit_invest_gold_buy_tos"
M_SUMMIT_INVEST_GOLD_BUY_TOS.full_name = ".m_summit_invest_gold_buy_tos"
M_SUMMIT_INVEST_GOLD_BUY_TOS.nested_types = {}
M_SUMMIT_INVEST_GOLD_BUY_TOS.enum_types = {}
M_SUMMIT_INVEST_GOLD_BUY_TOS.fields = {M_SUMMIT_INVEST_GOLD_BUY_TOS_SUMMIT_INVEST_GOLD_FIELD}
M_SUMMIT_INVEST_GOLD_BUY_TOS.is_extendable = false
M_SUMMIT_INVEST_GOLD_BUY_TOS.extensions = {}

m_summit_invest_gold_buy_tos = protobuf.Message(M_SUMMIT_INVEST_GOLD_BUY_TOS)

