--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_summit_tower_update_toc_pb')

M_SUMMIT_TOWER_UPDATE_TOC = protobuf.Descriptor();
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD = protobuf.FieldDescriptor();

M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.name = "update"
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.full_name = ".m_summit_tower_update_toc.update"
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.number = 1
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.index = 0
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.label = 1
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.has_default_value = false
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.default_value = nil
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.message_type = p_kv_pb.P_KV
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.type = 11
M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD.cpp_type = 10

M_SUMMIT_TOWER_UPDATE_TOC.name = "m_summit_tower_update_toc"
M_SUMMIT_TOWER_UPDATE_TOC.full_name = ".m_summit_tower_update_toc"
M_SUMMIT_TOWER_UPDATE_TOC.nested_types = {}
M_SUMMIT_TOWER_UPDATE_TOC.enum_types = {}
M_SUMMIT_TOWER_UPDATE_TOC.fields = {M_SUMMIT_TOWER_UPDATE_TOC_UPDATE_FIELD}
M_SUMMIT_TOWER_UPDATE_TOC.is_extendable = false
M_SUMMIT_TOWER_UPDATE_TOC.extensions = {}

m_summit_tower_update_toc = protobuf.Message(M_SUMMIT_TOWER_UPDATE_TOC)

