--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_survey_state_toc_pb')

M_SURVEY_STATE_TOC = protobuf.Descriptor();
M_SURVEY_STATE_TOC_IS_OPEN_FIELD = protobuf.FieldDescriptor();

M_SURVEY_STATE_TOC_IS_OPEN_FIELD.name = "is_open"
M_SURVEY_STATE_TOC_IS_OPEN_FIELD.full_name = ".m_survey_state_toc.is_open"
M_SURVEY_STATE_TOC_IS_OPEN_FIELD.number = 1
M_SURVEY_STATE_TOC_IS_OPEN_FIELD.index = 0
M_SURVEY_STATE_TOC_IS_OPEN_FIELD.label = 1
M_SURVEY_STATE_TOC_IS_OPEN_FIELD.has_default_value = true
M_SURVEY_STATE_TOC_IS_OPEN_FIELD.default_value = true
M_SURVEY_STATE_TOC_IS_OPEN_FIELD.type = 8
M_SURVEY_STATE_TOC_IS_OPEN_FIELD.cpp_type = 7

M_SURVEY_STATE_TOC.name = "m_survey_state_toc"
M_SURVEY_STATE_TOC.full_name = ".m_survey_state_toc"
M_SURVEY_STATE_TOC.nested_types = {}
M_SURVEY_STATE_TOC.enum_types = {}
M_SURVEY_STATE_TOC.fields = {M_SURVEY_STATE_TOC_IS_OPEN_FIELD}
M_SURVEY_STATE_TOC.is_extendable = false
M_SURVEY_STATE_TOC.extensions = {}

m_survey_state_toc = protobuf.Message(M_SURVEY_STATE_TOC)

