--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_tab_skill_pb = require("Protol.p_tab_skill_pb")
module('Protol.m_talent_reset_toc_pb')

M_TALENT_RESET_TOC = protobuf.Descriptor();
M_TALENT_RESET_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD = protobuf.FieldDescriptor();
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD = protobuf.FieldDescriptor();

M_TALENT_RESET_TOC_ERR_CODE_FIELD.name = "err_code"
M_TALENT_RESET_TOC_ERR_CODE_FIELD.full_name = ".m_talent_reset_toc.err_code"
M_TALENT_RESET_TOC_ERR_CODE_FIELD.number = 1
M_TALENT_RESET_TOC_ERR_CODE_FIELD.index = 0
M_TALENT_RESET_TOC_ERR_CODE_FIELD.label = 1
M_TALENT_RESET_TOC_ERR_CODE_FIELD.has_default_value = true
M_TALENT_RESET_TOC_ERR_CODE_FIELD.default_value = 0
M_TALENT_RESET_TOC_ERR_CODE_FIELD.type = 5
M_TALENT_RESET_TOC_ERR_CODE_FIELD.cpp_type = 1

M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.name = "talent_points"
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.full_name = ".m_talent_reset_toc.talent_points"
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.number = 2
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.index = 1
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.label = 1
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.has_default_value = true
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.default_value = 0
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.type = 5
M_TALENT_RESET_TOC_TALENT_POINTS_FIELD.cpp_type = 1

M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.name = "tab_skills"
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.full_name = ".m_talent_reset_toc.tab_skills"
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.number = 3
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.index = 2
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.label = 1
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.has_default_value = false
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.default_value = nil
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.message_type = p_tab_skill_pb.P_TAB_SKILL
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.type = 11
M_TALENT_RESET_TOC_TAB_SKILLS_FIELD.cpp_type = 10

M_TALENT_RESET_TOC.name = "m_talent_reset_toc"
M_TALENT_RESET_TOC.full_name = ".m_talent_reset_toc"
M_TALENT_RESET_TOC.nested_types = {}
M_TALENT_RESET_TOC.enum_types = {}
M_TALENT_RESET_TOC.fields = {M_TALENT_RESET_TOC_ERR_CODE_FIELD, M_TALENT_RESET_TOC_TALENT_POINTS_FIELD, M_TALENT_RESET_TOC_TAB_SKILLS_FIELD}
M_TALENT_RESET_TOC.is_extendable = false
M_TALENT_RESET_TOC.extensions = {}

m_talent_reset_toc = protobuf.Message(M_TALENT_RESET_TOC)

