--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_team_pb = require("Protol.p_team_pb")
module('Protol.m_team_info_toc_pb')

M_TEAM_INFO_TOC = protobuf.Descriptor();
M_TEAM_INFO_TOC_TEAM_INFO_FIELD = protobuf.FieldDescriptor();

M_TEAM_INFO_TOC_TEAM_INFO_FIELD.name = "team_info"
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.full_name = ".m_team_info_toc.team_info"
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.number = 1
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.index = 0
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.label = 1
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.has_default_value = false
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.default_value = nil
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.message_type = p_team_pb.P_TEAM
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.type = 11
M_TEAM_INFO_TOC_TEAM_INFO_FIELD.cpp_type = 10

M_TEAM_INFO_TOC.name = "m_team_info_toc"
M_TEAM_INFO_TOC.full_name = ".m_team_info_toc"
M_TEAM_INFO_TOC.nested_types = {}
M_TEAM_INFO_TOC.enum_types = {}
M_TEAM_INFO_TOC.fields = {M_TEAM_INFO_TOC_TEAM_INFO_FIELD}
M_TEAM_INFO_TOC.is_extendable = false
M_TEAM_INFO_TOC.extensions = {}

m_team_info_toc = protobuf.Message(M_TEAM_INFO_TOC)

