--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_team_guide_match_tos_pb')

M_TEAM_GUIDE_MATCH_TOS = protobuf.Descriptor();

M_TEAM_GUIDE_MATCH_TOS.name = "m_team_guide_match_tos"
M_TEAM_GUIDE_MATCH_TOS.full_name = ".m_team_guide_match_tos"
M_TEAM_GUIDE_MATCH_TOS.nested_types = {}
M_TEAM_GUIDE_MATCH_TOS.enum_types = {}
M_TEAM_GUIDE_MATCH_TOS.fields = {}
M_TEAM_GUIDE_MATCH_TOS.is_extendable = false
M_TEAM_GUIDE_MATCH_TOS.extensions = {}

m_team_guide_match_tos = protobuf.Message(M_TEAM_GUIDE_MATCH_TOS)

