--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_team_create_tos_pb')

M_TEAM_CREATE_TOS = protobuf.Descriptor();

M_TEAM_CREATE_TOS.name = "m_team_create_tos"
M_TEAM_CREATE_TOS.full_name = ".m_team_create_tos"
M_TEAM_CREATE_TOS.nested_types = {}
M_TEAM_CREATE_TOS.enum_types = {}
M_TEAM_CREATE_TOS.fields = {}
M_TEAM_CREATE_TOS.is_extendable = false
M_TEAM_CREATE_TOS.extensions = {}

m_team_create_tos = protobuf.Message(M_TEAM_CREATE_TOS)

