--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_team_recruit_tos_pb')

M_TEAM_RECRUIT_TOS = protobuf.Descriptor();
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD = protobuf.FieldDescriptor();

M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.name = "sub_type"
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.full_name = ".m_team_recruit_tos.sub_type"
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.number = 1
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.index = 0
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.label = 1
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.has_default_value = true
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.default_value = 0
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.type = 5
M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD.cpp_type = 1

M_TEAM_RECRUIT_TOS.name = "m_team_recruit_tos"
M_TEAM_RECRUIT_TOS.full_name = ".m_team_recruit_tos"
M_TEAM_RECRUIT_TOS.nested_types = {}
M_TEAM_RECRUIT_TOS.enum_types = {}
M_TEAM_RECRUIT_TOS.fields = {M_TEAM_RECRUIT_TOS_SUB_TYPE_FIELD}
M_TEAM_RECRUIT_TOS.is_extendable = false
M_TEAM_RECRUIT_TOS.extensions = {}

m_team_recruit_tos = protobuf.Message(M_TEAM_RECRUIT_TOS)

