--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_throne_essence_toc_pb')

M_THRONE_ESSENCE_TOC = protobuf.Descriptor();
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD = protobuf.FieldDescriptor();

M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.name = "total_essence"
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.full_name = ".m_throne_essence_toc.total_essence"
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.number = 1
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.index = 0
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.label = 1
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.has_default_value = true
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.default_value = 0
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.type = 5
M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD.cpp_type = 1

M_THRONE_ESSENCE_TOC.name = "m_throne_essence_toc"
M_THRONE_ESSENCE_TOC.full_name = ".m_throne_essence_toc"
M_THRONE_ESSENCE_TOC.nested_types = {}
M_THRONE_ESSENCE_TOC.enum_types = {}
M_THRONE_ESSENCE_TOC.fields = {M_THRONE_ESSENCE_TOC_TOTAL_ESSENCE_FIELD}
M_THRONE_ESSENCE_TOC.is_extendable = false
M_THRONE_ESSENCE_TOC.extensions = {}

m_throne_essence_toc = protobuf.Message(M_THRONE_ESSENCE_TOC)

