--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_throne_surface_act_tos_pb')

M_THRONE_SURFACE_ACT_TOS = protobuf.Descriptor();
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD = protobuf.FieldDescriptor();

M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.name = "surface_id"
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.full_name = ".m_throne_surface_act_tos.surface_id"
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.number = 1
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.index = 0
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.label = 1
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.has_default_value = true
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.default_value = 0
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.type = 5
M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD.cpp_type = 1

M_THRONE_SURFACE_ACT_TOS.name = "m_throne_surface_act_tos"
M_THRONE_SURFACE_ACT_TOS.full_name = ".m_throne_surface_act_tos"
M_THRONE_SURFACE_ACT_TOS.nested_types = {}
M_THRONE_SURFACE_ACT_TOS.enum_types = {}
M_THRONE_SURFACE_ACT_TOS.fields = {M_THRONE_SURFACE_ACT_TOS_SURFACE_ID_FIELD}
M_THRONE_SURFACE_ACT_TOS.is_extendable = false
M_THRONE_SURFACE_ACT_TOS.extensions = {}

m_throne_surface_act_tos = protobuf.Message(M_THRONE_SURFACE_ACT_TOS)

