--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.m_title_info_toc_pb')

M_TITLE_INFO_TOC = protobuf.Descriptor();
M_TITLE_INFO_TOC_CUR_TITLE_FIELD = protobuf.FieldDescriptor();
M_TITLE_INFO_TOC_TITLES_FIELD = protobuf.FieldDescriptor();

M_TITLE_INFO_TOC_CUR_TITLE_FIELD.name = "cur_title"
M_TITLE_INFO_TOC_CUR_TITLE_FIELD.full_name = ".m_title_info_toc.cur_title"
M_TITLE_INFO_TOC_CUR_TITLE_FIELD.number = 1
M_TITLE_INFO_TOC_CUR_TITLE_FIELD.index = 0
M_TITLE_INFO_TOC_CUR_TITLE_FIELD.label = 1
M_TITLE_INFO_TOC_CUR_TITLE_FIELD.has_default_value = true
M_TITLE_INFO_TOC_CUR_TITLE_FIELD.default_value = 0
M_TITLE_INFO_TOC_CUR_TITLE_FIELD.type = 5
M_TITLE_INFO_TOC_CUR_TITLE_FIELD.cpp_type = 1

M_TITLE_INFO_TOC_TITLES_FIELD.name = "titles"
M_TITLE_INFO_TOC_TITLES_FIELD.full_name = ".m_title_info_toc.titles"
M_TITLE_INFO_TOC_TITLES_FIELD.number = 2
M_TITLE_INFO_TOC_TITLES_FIELD.index = 1
M_TITLE_INFO_TOC_TITLES_FIELD.label = 3
M_TITLE_INFO_TOC_TITLES_FIELD.has_default_value = false
M_TITLE_INFO_TOC_TITLES_FIELD.default_value = {}
M_TITLE_INFO_TOC_TITLES_FIELD.message_type = p_kv_pb.P_KV
M_TITLE_INFO_TOC_TITLES_FIELD.type = 11
M_TITLE_INFO_TOC_TITLES_FIELD.cpp_type = 10

M_TITLE_INFO_TOC.name = "m_title_info_toc"
M_TITLE_INFO_TOC.full_name = ".m_title_info_toc"
M_TITLE_INFO_TOC.nested_types = {}
M_TITLE_INFO_TOC.enum_types = {}
M_TITLE_INFO_TOC.fields = {M_TITLE_INFO_TOC_CUR_TITLE_FIELD, M_TITLE_INFO_TOC_TITLES_FIELD}
M_TITLE_INFO_TOC.is_extendable = false
M_TITLE_INFO_TOC.extensions = {}

m_title_info_toc = protobuf.Message(M_TITLE_INFO_TOC)

