--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_universe_floor_info_tos_pb')

M_UNIVERSE_FLOOR_INFO_TOS = protobuf.Descriptor();
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD = protobuf.FieldDescriptor();

M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.name = "copy_id"
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.full_name = ".m_universe_floor_info_tos.copy_id"
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.number = 1
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.index = 0
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.label = 1
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.has_default_value = true
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.default_value = 0
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.type = 5
M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD.cpp_type = 1

M_UNIVERSE_FLOOR_INFO_TOS.name = "m_universe_floor_info_tos"
M_UNIVERSE_FLOOR_INFO_TOS.full_name = ".m_universe_floor_info_tos"
M_UNIVERSE_FLOOR_INFO_TOS.nested_types = {}
M_UNIVERSE_FLOOR_INFO_TOS.enum_types = {}
M_UNIVERSE_FLOOR_INFO_TOS.fields = {M_UNIVERSE_FLOOR_INFO_TOS_COPY_ID_FIELD}
M_UNIVERSE_FLOOR_INFO_TOS.is_extendable = false
M_UNIVERSE_FLOOR_INFO_TOS.extensions = {}

m_universe_floor_info_tos = protobuf.Message(M_UNIVERSE_FLOOR_INFO_TOS)

