--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_universe_rank_pb = require("Protol.p_universe_rank_pb")
local p_universe_best_three_pb = require("Protol.p_universe_best_three_pb")
module('Protol.m_universe_rank_toc_pb')

M_UNIVERSE_RANK_TOC = protobuf.Descriptor();
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD = protobuf.FieldDescriptor();
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD = protobuf.FieldDescriptor();

M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.name = "universe_ranks"
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.full_name = ".m_universe_rank_toc.universe_ranks"
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.number = 1
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.index = 0
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.label = 3
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.has_default_value = false
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.default_value = {}
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.message_type = p_universe_rank_pb.P_UNIVERSE_RANK
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.type = 11
M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD.cpp_type = 10

M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.name = "best_three"
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.full_name = ".m_universe_rank_toc.best_three"
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.number = 2
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.index = 1
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.label = 3
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.has_default_value = false
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.default_value = {}
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.message_type = p_universe_best_three_pb.P_UNIVERSE_BEST_THREE
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.type = 11
M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD.cpp_type = 10

M_UNIVERSE_RANK_TOC.name = "m_universe_rank_toc"
M_UNIVERSE_RANK_TOC.full_name = ".m_universe_rank_toc"
M_UNIVERSE_RANK_TOC.nested_types = {}
M_UNIVERSE_RANK_TOC.enum_types = {}
M_UNIVERSE_RANK_TOC.fields = {M_UNIVERSE_RANK_TOC_UNIVERSE_RANKS_FIELD, M_UNIVERSE_RANK_TOC_BEST_THREE_FIELD}
M_UNIVERSE_RANK_TOC.is_extendable = false
M_UNIVERSE_RANK_TOC.extensions = {}

m_universe_rank_toc = protobuf.Message(M_UNIVERSE_RANK_TOC)

