--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_vip_info_toc_pb')

M_VIP_INFO_TOC = protobuf.Descriptor();
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD = protobuf.FieldDescriptor();
M_VIP_INFO_TOC_LEVEL_FIELD = protobuf.FieldDescriptor();
M_VIP_INFO_TOC_EXP_FIELD = protobuf.FieldDescriptor();
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD = protobuf.FieldDescriptor();
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD = protobuf.FieldDescriptor();
M_VIP_INFO_TOC_GIFT_LIST_FIELD = protobuf.FieldDescriptor();
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD = protobuf.FieldDescriptor();
M_VIP_INFO_TOC_IS_REMIND_FIELD = protobuf.FieldDescriptor();
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD = protobuf.FieldDescriptor();

M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.name = "expire_time"
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.full_name = ".m_vip_info_toc.expire_time"
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.number = 1
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.index = 0
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.label = 1
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.has_default_value = true
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.default_value = 0
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.type = 5
M_VIP_INFO_TOC_EXPIRE_TIME_FIELD.cpp_type = 1

M_VIP_INFO_TOC_LEVEL_FIELD.name = "level"
M_VIP_INFO_TOC_LEVEL_FIELD.full_name = ".m_vip_info_toc.level"
M_VIP_INFO_TOC_LEVEL_FIELD.number = 2
M_VIP_INFO_TOC_LEVEL_FIELD.index = 1
M_VIP_INFO_TOC_LEVEL_FIELD.label = 1
M_VIP_INFO_TOC_LEVEL_FIELD.has_default_value = true
M_VIP_INFO_TOC_LEVEL_FIELD.default_value = 0
M_VIP_INFO_TOC_LEVEL_FIELD.type = 5
M_VIP_INFO_TOC_LEVEL_FIELD.cpp_type = 1

M_VIP_INFO_TOC_EXP_FIELD.name = "exp"
M_VIP_INFO_TOC_EXP_FIELD.full_name = ".m_vip_info_toc.exp"
M_VIP_INFO_TOC_EXP_FIELD.number = 3
M_VIP_INFO_TOC_EXP_FIELD.index = 2
M_VIP_INFO_TOC_EXP_FIELD.label = 1
M_VIP_INFO_TOC_EXP_FIELD.has_default_value = true
M_VIP_INFO_TOC_EXP_FIELD.default_value = 0
M_VIP_INFO_TOC_EXP_FIELD.type = 5
M_VIP_INFO_TOC_EXP_FIELD.cpp_type = 1

M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.name = "first_buy_list"
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.full_name = ".m_vip_info_toc.first_buy_list"
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.number = 4
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.index = 3
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.label = 3
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.has_default_value = false
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.default_value = {}
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.type = 5
M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD.cpp_type = 1

M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.name = "day_gift_status"
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.full_name = ".m_vip_info_toc.day_gift_status"
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.number = 5
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.index = 4
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.label = 1
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.has_default_value = true
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.default_value = true
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.type = 8
M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD.cpp_type = 7

M_VIP_INFO_TOC_GIFT_LIST_FIELD.name = "gift_list"
M_VIP_INFO_TOC_GIFT_LIST_FIELD.full_name = ".m_vip_info_toc.gift_list"
M_VIP_INFO_TOC_GIFT_LIST_FIELD.number = 6
M_VIP_INFO_TOC_GIFT_LIST_FIELD.index = 5
M_VIP_INFO_TOC_GIFT_LIST_FIELD.label = 3
M_VIP_INFO_TOC_GIFT_LIST_FIELD.has_default_value = false
M_VIP_INFO_TOC_GIFT_LIST_FIELD.default_value = {}
M_VIP_INFO_TOC_GIFT_LIST_FIELD.type = 5
M_VIP_INFO_TOC_GIFT_LIST_FIELD.cpp_type = 1

M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.name = "is_vip_experience"
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.full_name = ".m_vip_info_toc.is_vip_experience"
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.number = 7
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.index = 6
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.label = 1
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.has_default_value = true
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.default_value = true
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.type = 8
M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD.cpp_type = 7

M_VIP_INFO_TOC_IS_REMIND_FIELD.name = "is_remind"
M_VIP_INFO_TOC_IS_REMIND_FIELD.full_name = ".m_vip_info_toc.is_remind"
M_VIP_INFO_TOC_IS_REMIND_FIELD.number = 8
M_VIP_INFO_TOC_IS_REMIND_FIELD.index = 7
M_VIP_INFO_TOC_IS_REMIND_FIELD.label = 1
M_VIP_INFO_TOC_IS_REMIND_FIELD.has_default_value = true
M_VIP_INFO_TOC_IS_REMIND_FIELD.default_value = true
M_VIP_INFO_TOC_IS_REMIND_FIELD.type = 8
M_VIP_INFO_TOC_IS_REMIND_FIELD.cpp_type = 7

M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.name = "v4_remind_time"
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.full_name = ".m_vip_info_toc.v4_remind_time"
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.number = 9
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.index = 8
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.label = 1
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.has_default_value = true
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.default_value = 0
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.type = 5
M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD.cpp_type = 1

M_VIP_INFO_TOC.name = "m_vip_info_toc"
M_VIP_INFO_TOC.full_name = ".m_vip_info_toc"
M_VIP_INFO_TOC.nested_types = {}
M_VIP_INFO_TOC.enum_types = {}
M_VIP_INFO_TOC.fields = {M_VIP_INFO_TOC_EXPIRE_TIME_FIELD, M_VIP_INFO_TOC_LEVEL_FIELD, M_VIP_INFO_TOC_EXP_FIELD, M_VIP_INFO_TOC_FIRST_BUY_LIST_FIELD, M_VIP_INFO_TOC_DAY_GIFT_STATUS_FIELD, M_VIP_INFO_TOC_GIFT_LIST_FIELD, M_VIP_INFO_TOC_IS_VIP_EXPERIENCE_FIELD, M_VIP_INFO_TOC_IS_REMIND_FIELD, M_VIP_INFO_TOC_V4_REMIND_TIME_FIELD}
M_VIP_INFO_TOC.is_extendable = false
M_VIP_INFO_TOC.extensions = {}

m_vip_info_toc = protobuf.Message(M_VIP_INFO_TOC)

