--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_vip_invest_reward_tos_pb')

M_VIP_INVEST_REWARD_TOS = protobuf.Descriptor();

M_VIP_INVEST_REWARD_TOS.name = "m_vip_invest_reward_tos"
M_VIP_INVEST_REWARD_TOS.full_name = ".m_vip_invest_reward_tos"
M_VIP_INVEST_REWARD_TOS.nested_types = {}
M_VIP_INVEST_REWARD_TOS.enum_types = {}
M_VIP_INVEST_REWARD_TOS.fields = {}
M_VIP_INVEST_REWARD_TOS.is_extendable = false
M_VIP_INVEST_REWARD_TOS.extensions = {}

m_vip_invest_reward_tos = protobuf.Message(M_VIP_INVEST_REWARD_TOS)

