--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_war_god_decompose_tos_pb')

M_WAR_GOD_DECOMPOSE_TOS = protobuf.Descriptor();
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD = protobuf.FieldDescriptor();

M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.name = "piece_ids"
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.full_name = ".m_war_god_decompose_tos.piece_ids"
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.number = 1
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.index = 0
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.label = 3
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.has_default_value = false
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.default_value = {}
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.type = 5
M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD.cpp_type = 1

M_WAR_GOD_DECOMPOSE_TOS.name = "m_war_god_decompose_tos"
M_WAR_GOD_DECOMPOSE_TOS.full_name = ".m_war_god_decompose_tos"
M_WAR_GOD_DECOMPOSE_TOS.nested_types = {}
M_WAR_GOD_DECOMPOSE_TOS.enum_types = {}
M_WAR_GOD_DECOMPOSE_TOS.fields = {M_WAR_GOD_DECOMPOSE_TOS_PIECE_IDS_FIELD}
M_WAR_GOD_DECOMPOSE_TOS.is_extendable = false
M_WAR_GOD_DECOMPOSE_TOS.extensions = {}

m_war_god_decompose_tos = protobuf.Message(M_WAR_GOD_DECOMPOSE_TOS)

