--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_war_spirit_equip_del_toc_pb')

M_WAR_SPIRIT_EQUIP_DEL_TOC = protobuf.Descriptor();
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD = protobuf.FieldDescriptor();

M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.name = "del_list"
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.full_name = ".m_war_spirit_equip_del_toc.del_list"
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.number = 1
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.index = 0
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.label = 3
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.has_default_value = false
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.default_value = {}
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.type = 3
M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD.cpp_type = 2

M_WAR_SPIRIT_EQUIP_DEL_TOC.name = "m_war_spirit_equip_del_toc"
M_WAR_SPIRIT_EQUIP_DEL_TOC.full_name = ".m_war_spirit_equip_del_toc"
M_WAR_SPIRIT_EQUIP_DEL_TOC.nested_types = {}
M_WAR_SPIRIT_EQUIP_DEL_TOC.enum_types = {}
M_WAR_SPIRIT_EQUIP_DEL_TOC.fields = {M_WAR_SPIRIT_EQUIP_DEL_TOC_DEL_LIST_FIELD}
M_WAR_SPIRIT_EQUIP_DEL_TOC.is_extendable = false
M_WAR_SPIRIT_EQUIP_DEL_TOC.extensions = {}

m_war_spirit_equip_del_toc = protobuf.Message(M_WAR_SPIRIT_EQUIP_DEL_TOC)

