--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_war_spirit_change_tos_pb')

M_WAR_SPIRIT_CHANGE_TOS = protobuf.Descriptor();
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD = protobuf.FieldDescriptor();

M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.name = "id"
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.full_name = ".m_war_spirit_change_tos.id"
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.number = 1
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.index = 0
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.label = 1
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.has_default_value = true
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.default_value = 0
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.type = 5
M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD.cpp_type = 1

M_WAR_SPIRIT_CHANGE_TOS.name = "m_war_spirit_change_tos"
M_WAR_SPIRIT_CHANGE_TOS.full_name = ".m_war_spirit_change_tos"
M_WAR_SPIRIT_CHANGE_TOS.nested_types = {}
M_WAR_SPIRIT_CHANGE_TOS.enum_types = {}
M_WAR_SPIRIT_CHANGE_TOS.fields = {M_WAR_SPIRIT_CHANGE_TOS_ID_FIELD}
M_WAR_SPIRIT_CHANGE_TOS.is_extendable = false
M_WAR_SPIRIT_CHANGE_TOS.extensions = {}

m_war_spirit_change_tos = protobuf.Message(M_WAR_SPIRIT_CHANGE_TOS)

