--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_war_spirit_equip_decompose_tos_pb')

M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS = protobuf.Descriptor();
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD = protobuf.FieldDescriptor();

M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.name = "equip_id"
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.full_name = ".m_war_spirit_equip_decompose_tos.equip_id"
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.number = 1
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.index = 0
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.label = 3
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.has_default_value = false
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.default_value = {}
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.type = 3
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD.cpp_type = 2

M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS.name = "m_war_spirit_equip_decompose_tos"
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS.full_name = ".m_war_spirit_equip_decompose_tos"
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS.nested_types = {}
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS.enum_types = {}
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS.fields = {M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS_EQUIP_ID_FIELD}
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS.is_extendable = false
M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS.extensions = {}

m_war_spirit_equip_decompose_tos = protobuf.Message(M_WAR_SPIRIT_EQUIP_DECOMPOSE_TOS)

