--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_world_boss_care_notice_toc_pb')

M_WORLD_BOSS_CARE_NOTICE_TOC = protobuf.Descriptor();
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD = protobuf.FieldDescriptor();
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD = protobuf.FieldDescriptor();

M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.name = "boss_type_id"
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.full_name = ".m_world_boss_care_notice_toc.boss_type_id"
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.number = 1
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.index = 0
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.label = 1
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.has_default_value = true
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.default_value = 0
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.type = 5
M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD.cpp_type = 1

M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.name = "type"
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.full_name = ".m_world_boss_care_notice_toc.type"
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.number = 2
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.index = 1
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.label = 1
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.has_default_value = true
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.default_value = 0
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.type = 5
M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD.cpp_type = 1

M_WORLD_BOSS_CARE_NOTICE_TOC.name = "m_world_boss_care_notice_toc"
M_WORLD_BOSS_CARE_NOTICE_TOC.full_name = ".m_world_boss_care_notice_toc"
M_WORLD_BOSS_CARE_NOTICE_TOC.nested_types = {}
M_WORLD_BOSS_CARE_NOTICE_TOC.enum_types = {}
M_WORLD_BOSS_CARE_NOTICE_TOC.fields = {M_WORLD_BOSS_CARE_NOTICE_TOC_BOSS_TYPE_ID_FIELD, M_WORLD_BOSS_CARE_NOTICE_TOC_TYPE_FIELD}
M_WORLD_BOSS_CARE_NOTICE_TOC.is_extendable = false
M_WORLD_BOSS_CARE_NOTICE_TOC.extensions = {}

m_world_boss_care_notice_toc = protobuf.Message(M_WORLD_BOSS_CARE_NOTICE_TOC)

