--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_world_boss_seek_help_toc_pb')

M_WORLD_BOSS_SEEK_HELP_TOC = protobuf.Descriptor();
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();

M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.name = "err_code"
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.full_name = ".m_world_boss_seek_help_toc.err_code"
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.number = 1
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.index = 0
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.label = 1
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.has_default_value = true
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.default_value = 0
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.type = 5
M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD.cpp_type = 1

M_WORLD_BOSS_SEEK_HELP_TOC.name = "m_world_boss_seek_help_toc"
M_WORLD_BOSS_SEEK_HELP_TOC.full_name = ".m_world_boss_seek_help_toc"
M_WORLD_BOSS_SEEK_HELP_TOC.nested_types = {}
M_WORLD_BOSS_SEEK_HELP_TOC.enum_types = {}
M_WORLD_BOSS_SEEK_HELP_TOC.fields = {M_WORLD_BOSS_SEEK_HELP_TOC_ERR_CODE_FIELD}
M_WORLD_BOSS_SEEK_HELP_TOC.is_extendable = false
M_WORLD_BOSS_SEEK_HELP_TOC.extensions = {}

m_world_boss_seek_help_toc = protobuf.Message(M_WORLD_BOSS_SEEK_HELP_TOC)

