--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_world_boss_buy_times_tos_pb')

M_WORLD_BOSS_BUY_TIMES_TOS = protobuf.Descriptor();

M_WORLD_BOSS_BUY_TIMES_TOS.name = "m_world_boss_buy_times_tos"
M_WORLD_BOSS_BUY_TIMES_TOS.full_name = ".m_world_boss_buy_times_tos"
M_WORLD_BOSS_BUY_TIMES_TOS.nested_types = {}
M_WORLD_BOSS_BUY_TIMES_TOS.enum_types = {}
M_WORLD_BOSS_BUY_TIMES_TOS.fields = {}
M_WORLD_BOSS_BUY_TIMES_TOS.is_extendable = false
M_WORLD_BOSS_BUY_TIMES_TOS.extensions = {}

m_world_boss_buy_times_tos = protobuf.Message(M_WORLD_BOSS_BUY_TIMES_TOS)

