--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_world_boss_kill_tos_pb')

M_WORLD_BOSS_KILL_TOS = protobuf.Descriptor();
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD = protobuf.FieldDescriptor();

M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.name = "type_id"
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.full_name = ".m_world_boss_kill_tos.type_id"
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.number = 1
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.index = 0
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.label = 1
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.has_default_value = true
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.default_value = 0
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.type = 5
M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD.cpp_type = 1

M_WORLD_BOSS_KILL_TOS.name = "m_world_boss_kill_tos"
M_WORLD_BOSS_KILL_TOS.full_name = ".m_world_boss_kill_tos"
M_WORLD_BOSS_KILL_TOS.nested_types = {}
M_WORLD_BOSS_KILL_TOS.enum_types = {}
M_WORLD_BOSS_KILL_TOS.fields = {M_WORLD_BOSS_KILL_TOS_TYPE_ID_FIELD}
M_WORLD_BOSS_KILL_TOS.is_extendable = false
M_WORLD_BOSS_KILL_TOS.extensions = {}

m_world_boss_kill_tos = protobuf.Message(M_WORLD_BOSS_KILL_TOS)

