--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_world_boss_info_tos_pb')

M_WORLD_BOSS_INFO_TOS = protobuf.Descriptor();
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD = protobuf.FieldDescriptor();
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD = protobuf.FieldDescriptor();

M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.name = "type"
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.full_name = ".m_world_boss_info_tos.type"
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.number = 1
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.index = 0
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.label = 1
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.has_default_value = true
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.default_value = 0
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.type = 5
M_WORLD_BOSS_INFO_TOS_TYPE_FIELD.cpp_type = 1

M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.name = "floor"
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.full_name = ".m_world_boss_info_tos.floor"
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.number = 2
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.index = 1
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.label = 1
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.has_default_value = true
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.default_value = 0
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.type = 5
M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD.cpp_type = 1

M_WORLD_BOSS_INFO_TOS.name = "m_world_boss_info_tos"
M_WORLD_BOSS_INFO_TOS.full_name = ".m_world_boss_info_tos"
M_WORLD_BOSS_INFO_TOS.nested_types = {}
M_WORLD_BOSS_INFO_TOS.enum_types = {}
M_WORLD_BOSS_INFO_TOS.fields = {M_WORLD_BOSS_INFO_TOS_TYPE_FIELD, M_WORLD_BOSS_INFO_TOS_FLOOR_FIELD}
M_WORLD_BOSS_INFO_TOS.is_extendable = false
M_WORLD_BOSS_INFO_TOS.extensions = {}

m_world_boss_info_tos = protobuf.Message(M_WORLD_BOSS_INFO_TOS)

