--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.m_world_boss_quit_time_toc_pb')

M_WORLD_BOSS_QUIT_TIME_TOC = protobuf.Descriptor();
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD = protobuf.FieldDescriptor();

M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.name = "quit_time"
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.full_name = ".m_world_boss_quit_time_toc.quit_time"
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.number = 1
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.index = 0
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.label = 1
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.has_default_value = true
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.default_value = 0
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.type = 5
M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD.cpp_type = 1

M_WORLD_BOSS_QUIT_TIME_TOC.name = "m_world_boss_quit_time_toc"
M_WORLD_BOSS_QUIT_TIME_TOC.full_name = ".m_world_boss_quit_time_toc"
M_WORLD_BOSS_QUIT_TIME_TOC.nested_types = {}
M_WORLD_BOSS_QUIT_TIME_TOC.enum_types = {}
M_WORLD_BOSS_QUIT_TIME_TOC.fields = {M_WORLD_BOSS_QUIT_TIME_TOC_QUIT_TIME_FIELD}
M_WORLD_BOSS_QUIT_TIME_TOC.is_extendable = false
M_WORLD_BOSS_QUIT_TIME_TOC.extensions = {}

m_world_boss_quit_time_toc = protobuf.Message(M_WORLD_BOSS_QUIT_TIME_TOC)

