--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_world_boss_log_pb = require("Protol.p_world_boss_log_pb")
module('Protol.m_world_boss_log_toc_pb')

M_WORLD_BOSS_LOG_TOC = protobuf.Descriptor();
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD = protobuf.FieldDescriptor();
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD = protobuf.FieldDescriptor();

M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.name = "log_list"
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.full_name = ".m_world_boss_log_toc.log_list"
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.number = 1
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.index = 0
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.label = 3
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.has_default_value = false
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.default_value = {}
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.message_type = p_world_boss_log_pb.P_WORLD_BOSS_LOG
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.type = 11
M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD.cpp_type = 10

M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.name = "normal_log_list"
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.full_name = ".m_world_boss_log_toc.normal_log_list"
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.number = 2
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.index = 1
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.label = 3
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.has_default_value = false
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.default_value = {}
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.message_type = p_world_boss_log_pb.P_WORLD_BOSS_LOG
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.type = 11
M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD.cpp_type = 10

M_WORLD_BOSS_LOG_TOC.name = "m_world_boss_log_toc"
M_WORLD_BOSS_LOG_TOC.full_name = ".m_world_boss_log_toc"
M_WORLD_BOSS_LOG_TOC.nested_types = {}
M_WORLD_BOSS_LOG_TOC.enum_types = {}
M_WORLD_BOSS_LOG_TOC.fields = {M_WORLD_BOSS_LOG_TOC_LOG_LIST_FIELD, M_WORLD_BOSS_LOG_TOC_NORMAL_LOG_LIST_FIELD}
M_WORLD_BOSS_LOG_TOC.is_extendable = false
M_WORLD_BOSS_LOG_TOC.extensions = {}

m_world_boss_log_toc = protobuf.Message(M_WORLD_BOSS_LOG_TOC)

