--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.mod_role_act_it_cease_toc_pb')

MOD_ROLE_ACT_IT_CEASE_TOC = protobuf.Descriptor();
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();

MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.name = "err_code"
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.full_name = ".mod_role_act_it_cease_toc.err_code"
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.number = 1
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.index = 0
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.label = 1
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.has_default_value = true
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.default_value = 0
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.type = 5
MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD.cpp_type = 1

MOD_ROLE_ACT_IT_CEASE_TOC.name = "mod_role_act_it_cease_toc"
MOD_ROLE_ACT_IT_CEASE_TOC.full_name = ".mod_role_act_it_cease_toc"
MOD_ROLE_ACT_IT_CEASE_TOC.nested_types = {}
MOD_ROLE_ACT_IT_CEASE_TOC.enum_types = {}
MOD_ROLE_ACT_IT_CEASE_TOC.fields = {MOD_ROLE_ACT_IT_CEASE_TOC_ERR_CODE_FIELD}
MOD_ROLE_ACT_IT_CEASE_TOC.is_extendable = false
MOD_ROLE_ACT_IT_CEASE_TOC.extensions = {}

mod_role_act_it_cease_toc = protobuf.Message(MOD_ROLE_ACT_IT_CEASE_TOC)

