--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.mod_role_act_it_info_toc_pb')

MOD_ROLE_ACT_IT_INFO_TOC = protobuf.Descriptor();
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD = protobuf.FieldDescriptor();
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD = protobuf.FieldDescriptor();
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD = protobuf.FieldDescriptor();

MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.name = "err_code"
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.full_name = ".mod_role_act_it_info_toc.err_code"
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.number = 1
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.index = 0
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.label = 1
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.has_default_value = true
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.default_value = 0
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.type = 5
MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD.cpp_type = 1

MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.name = "id"
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.full_name = ".mod_role_act_it_info_toc.id"
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.number = 2
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.index = 1
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.label = 1
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.has_default_value = true
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.default_value = 0
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.type = 5
MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD.cpp_type = 1

MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.name = "luck"
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.full_name = ".mod_role_act_it_info_toc.luck"
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.number = 3
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.index = 2
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.label = 1
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.has_default_value = true
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.default_value = 0
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.type = 5
MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD.cpp_type = 1

MOD_ROLE_ACT_IT_INFO_TOC.name = "mod_role_act_it_info_toc"
MOD_ROLE_ACT_IT_INFO_TOC.full_name = ".mod_role_act_it_info_toc"
MOD_ROLE_ACT_IT_INFO_TOC.nested_types = {}
MOD_ROLE_ACT_IT_INFO_TOC.enum_types = {}
MOD_ROLE_ACT_IT_INFO_TOC.fields = {MOD_ROLE_ACT_IT_INFO_TOC_ERR_CODE_FIELD, MOD_ROLE_ACT_IT_INFO_TOC_ID_FIELD, MOD_ROLE_ACT_IT_INFO_TOC_LUCK_FIELD}
MOD_ROLE_ACT_IT_INFO_TOC.is_extendable = false
MOD_ROLE_ACT_IT_INFO_TOC.extensions = {}

mod_role_act_it_info_toc = protobuf.Message(MOD_ROLE_ACT_IT_INFO_TOC)

