--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_item_i_pb = require("Protol.p_item_i_pb")
module('Protol.p_bg_act_entry_pb')

P_BG_ACT_ENTRY = protobuf.Descriptor();
P_BG_ACT_ENTRY_SORT_FIELD = protobuf.FieldDescriptor();
P_BG_ACT_ENTRY_ITEMS_FIELD = protobuf.FieldDescriptor();
P_BG_ACT_ENTRY_TITLE_FIELD = protobuf.FieldDescriptor();
P_BG_ACT_ENTRY_STATUS_FIELD = protobuf.FieldDescriptor();
P_BG_ACT_ENTRY_SCHEDULE_FIELD = protobuf.FieldDescriptor();
P_BG_ACT_ENTRY_TARGET_FIELD = protobuf.FieldDescriptor();
P_BG_ACT_ENTRY_NUM_FIELD = protobuf.FieldDescriptor();

P_BG_ACT_ENTRY_SORT_FIELD.name = "sort"
P_BG_ACT_ENTRY_SORT_FIELD.full_name = ".p_bg_act_entry.sort"
P_BG_ACT_ENTRY_SORT_FIELD.number = 1
P_BG_ACT_ENTRY_SORT_FIELD.index = 0
P_BG_ACT_ENTRY_SORT_FIELD.label = 1
P_BG_ACT_ENTRY_SORT_FIELD.has_default_value = true
P_BG_ACT_ENTRY_SORT_FIELD.default_value = 0
P_BG_ACT_ENTRY_SORT_FIELD.type = 5
P_BG_ACT_ENTRY_SORT_FIELD.cpp_type = 1

P_BG_ACT_ENTRY_ITEMS_FIELD.name = "items"
P_BG_ACT_ENTRY_ITEMS_FIELD.full_name = ".p_bg_act_entry.items"
P_BG_ACT_ENTRY_ITEMS_FIELD.number = 2
P_BG_ACT_ENTRY_ITEMS_FIELD.index = 1
P_BG_ACT_ENTRY_ITEMS_FIELD.label = 3
P_BG_ACT_ENTRY_ITEMS_FIELD.has_default_value = false
P_BG_ACT_ENTRY_ITEMS_FIELD.default_value = {}
P_BG_ACT_ENTRY_ITEMS_FIELD.message_type = p_item_i_pb.P_ITEM_I
P_BG_ACT_ENTRY_ITEMS_FIELD.type = 11
P_BG_ACT_ENTRY_ITEMS_FIELD.cpp_type = 10

P_BG_ACT_ENTRY_TITLE_FIELD.name = "title"
P_BG_ACT_ENTRY_TITLE_FIELD.full_name = ".p_bg_act_entry.title"
P_BG_ACT_ENTRY_TITLE_FIELD.number = 3
P_BG_ACT_ENTRY_TITLE_FIELD.index = 2
P_BG_ACT_ENTRY_TITLE_FIELD.label = 1
P_BG_ACT_ENTRY_TITLE_FIELD.has_default_value = false
P_BG_ACT_ENTRY_TITLE_FIELD.default_value = ""
P_BG_ACT_ENTRY_TITLE_FIELD.type = 9
P_BG_ACT_ENTRY_TITLE_FIELD.cpp_type = 9

P_BG_ACT_ENTRY_STATUS_FIELD.name = "status"
P_BG_ACT_ENTRY_STATUS_FIELD.full_name = ".p_bg_act_entry.status"
P_BG_ACT_ENTRY_STATUS_FIELD.number = 4
P_BG_ACT_ENTRY_STATUS_FIELD.index = 3
P_BG_ACT_ENTRY_STATUS_FIELD.label = 1
P_BG_ACT_ENTRY_STATUS_FIELD.has_default_value = true
P_BG_ACT_ENTRY_STATUS_FIELD.default_value = 0
P_BG_ACT_ENTRY_STATUS_FIELD.type = 5
P_BG_ACT_ENTRY_STATUS_FIELD.cpp_type = 1

P_BG_ACT_ENTRY_SCHEDULE_FIELD.name = "schedule"
P_BG_ACT_ENTRY_SCHEDULE_FIELD.full_name = ".p_bg_act_entry.schedule"
P_BG_ACT_ENTRY_SCHEDULE_FIELD.number = 5
P_BG_ACT_ENTRY_SCHEDULE_FIELD.index = 4
P_BG_ACT_ENTRY_SCHEDULE_FIELD.label = 1
P_BG_ACT_ENTRY_SCHEDULE_FIELD.has_default_value = true
P_BG_ACT_ENTRY_SCHEDULE_FIELD.default_value = 0
P_BG_ACT_ENTRY_SCHEDULE_FIELD.type = 5
P_BG_ACT_ENTRY_SCHEDULE_FIELD.cpp_type = 1

P_BG_ACT_ENTRY_TARGET_FIELD.name = "target"
P_BG_ACT_ENTRY_TARGET_FIELD.full_name = ".p_bg_act_entry.target"
P_BG_ACT_ENTRY_TARGET_FIELD.number = 6
P_BG_ACT_ENTRY_TARGET_FIELD.index = 5
P_BG_ACT_ENTRY_TARGET_FIELD.label = 1
P_BG_ACT_ENTRY_TARGET_FIELD.has_default_value = true
P_BG_ACT_ENTRY_TARGET_FIELD.default_value = 0
P_BG_ACT_ENTRY_TARGET_FIELD.type = 5
P_BG_ACT_ENTRY_TARGET_FIELD.cpp_type = 1

P_BG_ACT_ENTRY_NUM_FIELD.name = "num"
P_BG_ACT_ENTRY_NUM_FIELD.full_name = ".p_bg_act_entry.num"
P_BG_ACT_ENTRY_NUM_FIELD.number = 7
P_BG_ACT_ENTRY_NUM_FIELD.index = 6
P_BG_ACT_ENTRY_NUM_FIELD.label = 1
P_BG_ACT_ENTRY_NUM_FIELD.has_default_value = true
P_BG_ACT_ENTRY_NUM_FIELD.default_value = 0
P_BG_ACT_ENTRY_NUM_FIELD.type = 5
P_BG_ACT_ENTRY_NUM_FIELD.cpp_type = 1

P_BG_ACT_ENTRY.name = "p_bg_act_entry"
P_BG_ACT_ENTRY.full_name = ".p_bg_act_entry"
P_BG_ACT_ENTRY.nested_types = {}
P_BG_ACT_ENTRY.enum_types = {}
P_BG_ACT_ENTRY.fields = {P_BG_ACT_ENTRY_SORT_FIELD, P_BG_ACT_ENTRY_ITEMS_FIELD, P_BG_ACT_ENTRY_TITLE_FIELD, P_BG_ACT_ENTRY_STATUS_FIELD, P_BG_ACT_ENTRY_SCHEDULE_FIELD, P_BG_ACT_ENTRY_TARGET_FIELD, P_BG_ACT_ENTRY_NUM_FIELD}
P_BG_ACT_ENTRY.is_extendable = false
P_BG_ACT_ENTRY.extensions = {}

p_bg_act_entry = protobuf.Message(P_BG_ACT_ENTRY)

