--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.p_copy_cheer_pb')

P_COPY_CHEER = protobuf.Descriptor();
P_COPY_CHEER_ID_FIELD = protobuf.FieldDescriptor();
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD = protobuf.FieldDescriptor();
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD = protobuf.FieldDescriptor();

P_COPY_CHEER_ID_FIELD.name = "id"
P_COPY_CHEER_ID_FIELD.full_name = ".p_copy_cheer.id"
P_COPY_CHEER_ID_FIELD.number = 1
P_COPY_CHEER_ID_FIELD.index = 0
P_COPY_CHEER_ID_FIELD.label = 1
P_COPY_CHEER_ID_FIELD.has_default_value = true
P_COPY_CHEER_ID_FIELD.default_value = 0
P_COPY_CHEER_ID_FIELD.type = 5
P_COPY_CHEER_ID_FIELD.cpp_type = 1

P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.name = "silver_cheer_times"
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.full_name = ".p_copy_cheer.silver_cheer_times"
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.number = 2
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.index = 1
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.label = 1
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.has_default_value = true
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.default_value = 0
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.type = 5
P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD.cpp_type = 1

P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.name = "all_cheer_times"
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.full_name = ".p_copy_cheer.all_cheer_times"
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.number = 3
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.index = 2
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.label = 1
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.has_default_value = true
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.default_value = 0
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.type = 5
P_COPY_CHEER_ALL_CHEER_TIMES_FIELD.cpp_type = 1

P_COPY_CHEER.name = "p_copy_cheer"
P_COPY_CHEER.full_name = ".p_copy_cheer"
P_COPY_CHEER.nested_types = {}
P_COPY_CHEER.enum_types = {}
P_COPY_CHEER.fields = {P_COPY_CHEER_ID_FIELD, P_COPY_CHEER_SILVER_CHEER_TIMES_FIELD, P_COPY_CHEER_ALL_CHEER_TIMES_FIELD}
P_COPY_CHEER.is_extendable = false
P_COPY_CHEER.extensions = {}

p_copy_cheer = protobuf.Message(P_COPY_CHEER)

