--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.p_egg_pb')

P_EGG = protobuf.Descriptor();
P_EGG_ID_FIELD = protobuf.FieldDescriptor();
P_EGG_EGG_ID_FIELD = protobuf.FieldDescriptor();
P_EGG_EGG_TYPE_FIELD = protobuf.FieldDescriptor();
P_EGG_TYPE_ID_FIELD = protobuf.FieldDescriptor();
P_EGG_NUM_FIELD = protobuf.FieldDescriptor();
P_EGG_IS_BIND_FIELD = protobuf.FieldDescriptor();

P_EGG_ID_FIELD.name = "id"
P_EGG_ID_FIELD.full_name = ".p_egg.id"
P_EGG_ID_FIELD.number = 1
P_EGG_ID_FIELD.index = 0
P_EGG_ID_FIELD.label = 1
P_EGG_ID_FIELD.has_default_value = true
P_EGG_ID_FIELD.default_value = 0
P_EGG_ID_FIELD.type = 5
P_EGG_ID_FIELD.cpp_type = 1

P_EGG_EGG_ID_FIELD.name = "egg_id"
P_EGG_EGG_ID_FIELD.full_name = ".p_egg.egg_id"
P_EGG_EGG_ID_FIELD.number = 2
P_EGG_EGG_ID_FIELD.index = 1
P_EGG_EGG_ID_FIELD.label = 1
P_EGG_EGG_ID_FIELD.has_default_value = true
P_EGG_EGG_ID_FIELD.default_value = 0
P_EGG_EGG_ID_FIELD.type = 5
P_EGG_EGG_ID_FIELD.cpp_type = 1

P_EGG_EGG_TYPE_FIELD.name = "egg_type"
P_EGG_EGG_TYPE_FIELD.full_name = ".p_egg.egg_type"
P_EGG_EGG_TYPE_FIELD.number = 3
P_EGG_EGG_TYPE_FIELD.index = 2
P_EGG_EGG_TYPE_FIELD.label = 1
P_EGG_EGG_TYPE_FIELD.has_default_value = true
P_EGG_EGG_TYPE_FIELD.default_value = 0
P_EGG_EGG_TYPE_FIELD.type = 5
P_EGG_EGG_TYPE_FIELD.cpp_type = 1

P_EGG_TYPE_ID_FIELD.name = "type_id"
P_EGG_TYPE_ID_FIELD.full_name = ".p_egg.type_id"
P_EGG_TYPE_ID_FIELD.number = 4
P_EGG_TYPE_ID_FIELD.index = 3
P_EGG_TYPE_ID_FIELD.label = 1
P_EGG_TYPE_ID_FIELD.has_default_value = true
P_EGG_TYPE_ID_FIELD.default_value = 0
P_EGG_TYPE_ID_FIELD.type = 5
P_EGG_TYPE_ID_FIELD.cpp_type = 1

P_EGG_NUM_FIELD.name = "num"
P_EGG_NUM_FIELD.full_name = ".p_egg.num"
P_EGG_NUM_FIELD.number = 5
P_EGG_NUM_FIELD.index = 4
P_EGG_NUM_FIELD.label = 1
P_EGG_NUM_FIELD.has_default_value = true
P_EGG_NUM_FIELD.default_value = 0
P_EGG_NUM_FIELD.type = 5
P_EGG_NUM_FIELD.cpp_type = 1

P_EGG_IS_BIND_FIELD.name = "is_bind"
P_EGG_IS_BIND_FIELD.full_name = ".p_egg.is_bind"
P_EGG_IS_BIND_FIELD.number = 6
P_EGG_IS_BIND_FIELD.index = 5
P_EGG_IS_BIND_FIELD.label = 1
P_EGG_IS_BIND_FIELD.has_default_value = true
P_EGG_IS_BIND_FIELD.default_value = 0
P_EGG_IS_BIND_FIELD.type = 5
P_EGG_IS_BIND_FIELD.cpp_type = 1

P_EGG.name = "p_egg"
P_EGG.full_name = ".p_egg"
P_EGG.nested_types = {}
P_EGG.enum_types = {}
P_EGG.fields = {P_EGG_ID_FIELD, P_EGG_EGG_ID_FIELD, P_EGG_EGG_TYPE_FIELD, P_EGG_TYPE_ID_FIELD, P_EGG_NUM_FIELD, P_EGG_IS_BIND_FIELD}
P_EGG.is_extendable = false
P_EGG.extensions = {}

p_egg = protobuf.Message(P_EGG)

