--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_equip_concise_pb = require("Protol.p_equip_concise_pb")
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.p_equip_pb')

P_EQUIP = protobuf.Descriptor();
P_EQUIP_EQUIP_ID_FIELD = protobuf.FieldDescriptor();
P_EQUIP_REFINE_LEVEL_FIELD = protobuf.FieldDescriptor();
P_EQUIP_MASTERY_FIELD = protobuf.FieldDescriptor();
P_EQUIP_SUIT_LEVEL_FIELD = protobuf.FieldDescriptor();
P_EQUIP_STONE_LIST_FIELD = protobuf.FieldDescriptor();
P_EQUIP_EXCELLENT_LIST_FIELD = protobuf.FieldDescriptor();
P_EQUIP_BIND_FIELD = protobuf.FieldDescriptor();
P_EQUIP_CONCISE_NUM_FIELD = protobuf.FieldDescriptor();
P_EQUIP_CONCISE_LIST_FIELD = protobuf.FieldDescriptor();
P_EQUIP_FORGE_SOUL_FIELD = protobuf.FieldDescriptor();
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD = protobuf.FieldDescriptor();
P_EQUIP_STONE_HONINGS_FIELD = protobuf.FieldDescriptor();
P_EQUIP_SEAL_LIST_FIELD = protobuf.FieldDescriptor();

P_EQUIP_EQUIP_ID_FIELD.name = "equip_id"
P_EQUIP_EQUIP_ID_FIELD.full_name = ".p_equip.equip_id"
P_EQUIP_EQUIP_ID_FIELD.number = 1
P_EQUIP_EQUIP_ID_FIELD.index = 0
P_EQUIP_EQUIP_ID_FIELD.label = 1
P_EQUIP_EQUIP_ID_FIELD.has_default_value = true
P_EQUIP_EQUIP_ID_FIELD.default_value = 0
P_EQUIP_EQUIP_ID_FIELD.type = 5
P_EQUIP_EQUIP_ID_FIELD.cpp_type = 1

P_EQUIP_REFINE_LEVEL_FIELD.name = "refine_level"
P_EQUIP_REFINE_LEVEL_FIELD.full_name = ".p_equip.refine_level"
P_EQUIP_REFINE_LEVEL_FIELD.number = 2
P_EQUIP_REFINE_LEVEL_FIELD.index = 1
P_EQUIP_REFINE_LEVEL_FIELD.label = 1
P_EQUIP_REFINE_LEVEL_FIELD.has_default_value = true
P_EQUIP_REFINE_LEVEL_FIELD.default_value = 0
P_EQUIP_REFINE_LEVEL_FIELD.type = 5
P_EQUIP_REFINE_LEVEL_FIELD.cpp_type = 1

P_EQUIP_MASTERY_FIELD.name = "mastery"
P_EQUIP_MASTERY_FIELD.full_name = ".p_equip.mastery"
P_EQUIP_MASTERY_FIELD.number = 3
P_EQUIP_MASTERY_FIELD.index = 2
P_EQUIP_MASTERY_FIELD.label = 1
P_EQUIP_MASTERY_FIELD.has_default_value = true
P_EQUIP_MASTERY_FIELD.default_value = 0
P_EQUIP_MASTERY_FIELD.type = 5
P_EQUIP_MASTERY_FIELD.cpp_type = 1

P_EQUIP_SUIT_LEVEL_FIELD.name = "suit_level"
P_EQUIP_SUIT_LEVEL_FIELD.full_name = ".p_equip.suit_level"
P_EQUIP_SUIT_LEVEL_FIELD.number = 4
P_EQUIP_SUIT_LEVEL_FIELD.index = 3
P_EQUIP_SUIT_LEVEL_FIELD.label = 1
P_EQUIP_SUIT_LEVEL_FIELD.has_default_value = true
P_EQUIP_SUIT_LEVEL_FIELD.default_value = 0
P_EQUIP_SUIT_LEVEL_FIELD.type = 5
P_EQUIP_SUIT_LEVEL_FIELD.cpp_type = 1

P_EQUIP_STONE_LIST_FIELD.name = "stone_list"
P_EQUIP_STONE_LIST_FIELD.full_name = ".p_equip.stone_list"
P_EQUIP_STONE_LIST_FIELD.number = 5
P_EQUIP_STONE_LIST_FIELD.index = 4
P_EQUIP_STONE_LIST_FIELD.label = 3
P_EQUIP_STONE_LIST_FIELD.has_default_value = false
P_EQUIP_STONE_LIST_FIELD.default_value = {}
P_EQUIP_STONE_LIST_FIELD.message_type = p_kv_pb.P_KV
P_EQUIP_STONE_LIST_FIELD.type = 11
P_EQUIP_STONE_LIST_FIELD.cpp_type = 10

P_EQUIP_EXCELLENT_LIST_FIELD.name = "excellent_list"
P_EQUIP_EXCELLENT_LIST_FIELD.full_name = ".p_equip.excellent_list"
P_EQUIP_EXCELLENT_LIST_FIELD.number = 6
P_EQUIP_EXCELLENT_LIST_FIELD.index = 5
P_EQUIP_EXCELLENT_LIST_FIELD.label = 3
P_EQUIP_EXCELLENT_LIST_FIELD.has_default_value = false
P_EQUIP_EXCELLENT_LIST_FIELD.default_value = {}
P_EQUIP_EXCELLENT_LIST_FIELD.message_type = p_kv_pb.P_KV
P_EQUIP_EXCELLENT_LIST_FIELD.type = 11
P_EQUIP_EXCELLENT_LIST_FIELD.cpp_type = 10

P_EQUIP_BIND_FIELD.name = "bind"
P_EQUIP_BIND_FIELD.full_name = ".p_equip.bind"
P_EQUIP_BIND_FIELD.number = 7
P_EQUIP_BIND_FIELD.index = 6
P_EQUIP_BIND_FIELD.label = 1
P_EQUIP_BIND_FIELD.has_default_value = true
P_EQUIP_BIND_FIELD.default_value = true
P_EQUIP_BIND_FIELD.type = 8
P_EQUIP_BIND_FIELD.cpp_type = 7

P_EQUIP_CONCISE_NUM_FIELD.name = "concise_num"
P_EQUIP_CONCISE_NUM_FIELD.full_name = ".p_equip.concise_num"
P_EQUIP_CONCISE_NUM_FIELD.number = 8
P_EQUIP_CONCISE_NUM_FIELD.index = 7
P_EQUIP_CONCISE_NUM_FIELD.label = 1
P_EQUIP_CONCISE_NUM_FIELD.has_default_value = true
P_EQUIP_CONCISE_NUM_FIELD.default_value = 0
P_EQUIP_CONCISE_NUM_FIELD.type = 5
P_EQUIP_CONCISE_NUM_FIELD.cpp_type = 1

P_EQUIP_CONCISE_LIST_FIELD.name = "concise_list"
P_EQUIP_CONCISE_LIST_FIELD.full_name = ".p_equip.concise_list"
P_EQUIP_CONCISE_LIST_FIELD.number = 9
P_EQUIP_CONCISE_LIST_FIELD.index = 8
P_EQUIP_CONCISE_LIST_FIELD.label = 3
P_EQUIP_CONCISE_LIST_FIELD.has_default_value = false
P_EQUIP_CONCISE_LIST_FIELD.default_value = {}
P_EQUIP_CONCISE_LIST_FIELD.message_type = p_equip_concise_pb.P_EQUIP_CONCISE
P_EQUIP_CONCISE_LIST_FIELD.type = 11
P_EQUIP_CONCISE_LIST_FIELD.cpp_type = 10

P_EQUIP_FORGE_SOUL_FIELD.name = "forge_soul"
P_EQUIP_FORGE_SOUL_FIELD.full_name = ".p_equip.forge_soul"
P_EQUIP_FORGE_SOUL_FIELD.number = 10
P_EQUIP_FORGE_SOUL_FIELD.index = 9
P_EQUIP_FORGE_SOUL_FIELD.label = 1
P_EQUIP_FORGE_SOUL_FIELD.has_default_value = true
P_EQUIP_FORGE_SOUL_FIELD.default_value = 0
P_EQUIP_FORGE_SOUL_FIELD.type = 5
P_EQUIP_FORGE_SOUL_FIELD.cpp_type = 1

P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.name = "forge_soul_cultivate"
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.full_name = ".p_equip.forge_soul_cultivate"
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.number = 11
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.index = 10
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.label = 1
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.has_default_value = true
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.default_value = 0
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.type = 5
P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD.cpp_type = 1

P_EQUIP_STONE_HONINGS_FIELD.name = "stone_honings"
P_EQUIP_STONE_HONINGS_FIELD.full_name = ".p_equip.stone_honings"
P_EQUIP_STONE_HONINGS_FIELD.number = 12
P_EQUIP_STONE_HONINGS_FIELD.index = 11
P_EQUIP_STONE_HONINGS_FIELD.label = 3
P_EQUIP_STONE_HONINGS_FIELD.has_default_value = false
P_EQUIP_STONE_HONINGS_FIELD.default_value = {}
P_EQUIP_STONE_HONINGS_FIELD.message_type = p_kv_pb.P_KV
P_EQUIP_STONE_HONINGS_FIELD.type = 11
P_EQUIP_STONE_HONINGS_FIELD.cpp_type = 10

P_EQUIP_SEAL_LIST_FIELD.name = "seal_list"
P_EQUIP_SEAL_LIST_FIELD.full_name = ".p_equip.seal_list"
P_EQUIP_SEAL_LIST_FIELD.number = 13
P_EQUIP_SEAL_LIST_FIELD.index = 12
P_EQUIP_SEAL_LIST_FIELD.label = 3
P_EQUIP_SEAL_LIST_FIELD.has_default_value = false
P_EQUIP_SEAL_LIST_FIELD.default_value = {}
P_EQUIP_SEAL_LIST_FIELD.message_type = p_kv_pb.P_KV
P_EQUIP_SEAL_LIST_FIELD.type = 11
P_EQUIP_SEAL_LIST_FIELD.cpp_type = 10

P_EQUIP.name = "p_equip"
P_EQUIP.full_name = ".p_equip"
P_EQUIP.nested_types = {}
P_EQUIP.enum_types = {}
P_EQUIP.fields = {P_EQUIP_EQUIP_ID_FIELD, P_EQUIP_REFINE_LEVEL_FIELD, P_EQUIP_MASTERY_FIELD, P_EQUIP_SUIT_LEVEL_FIELD, P_EQUIP_STONE_LIST_FIELD, P_EQUIP_EXCELLENT_LIST_FIELD, P_EQUIP_BIND_FIELD, P_EQUIP_CONCISE_NUM_FIELD, P_EQUIP_CONCISE_LIST_FIELD, P_EQUIP_FORGE_SOUL_FIELD, P_EQUIP_FORGE_SOUL_CULTIVATE_FIELD, P_EQUIP_STONE_HONINGS_FIELD, P_EQUIP_SEAL_LIST_FIELD}
P_EQUIP.is_extendable = false
P_EQUIP.extensions = {}

p_equip = protobuf.Message(P_EQUIP)

