--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.p_ks_pb')

P_KS = protobuf.Descriptor();
P_KS_ID_FIELD = protobuf.FieldDescriptor();
P_KS_STR_FIELD = protobuf.FieldDescriptor();

P_KS_ID_FIELD.name = "id"
P_KS_ID_FIELD.full_name = ".p_ks.id"
P_KS_ID_FIELD.number = 1
P_KS_ID_FIELD.index = 0
P_KS_ID_FIELD.label = 1
P_KS_ID_FIELD.has_default_value = true
P_KS_ID_FIELD.default_value = 0
P_KS_ID_FIELD.type = 5
P_KS_ID_FIELD.cpp_type = 1

P_KS_STR_FIELD.name = "str"
P_KS_STR_FIELD.full_name = ".p_ks.str"
P_KS_STR_FIELD.number = 2
P_KS_STR_FIELD.index = 1
P_KS_STR_FIELD.label = 1
P_KS_STR_FIELD.has_default_value = false
P_KS_STR_FIELD.default_value = ""
P_KS_STR_FIELD.type = 9
P_KS_STR_FIELD.cpp_type = 9

P_KS.name = "p_ks"
P_KS.full_name = ".p_ks"
P_KS.nested_types = {}
P_KS.enum_types = {}
P_KS.fields = {P_KS_ID_FIELD, P_KS_STR_FIELD}
P_KS.is_extendable = false
P_KS.extensions = {}

p_ks = protobuf.Message(P_KS)

