--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.p_marry_wish_pb')

P_MARRY_WISH = protobuf.Descriptor();
P_MARRY_WISH_WISH_TIME_FIELD = protobuf.FieldDescriptor();
P_MARRY_WISH_ROLE_ID_FIELD = protobuf.FieldDescriptor();
P_MARRY_WISH_ROLE_NAME_FIELD = protobuf.FieldDescriptor();
P_MARRY_WISH_TO_ROLE_ID_FIELD = protobuf.FieldDescriptor();
P_MARRY_WISH_TO_ROLE_NAME_FIELD = protobuf.FieldDescriptor();
P_MARRY_WISH_INDEX_ID_FIELD = protobuf.FieldDescriptor();

P_MARRY_WISH_WISH_TIME_FIELD.name = "wish_time"
P_MARRY_WISH_WISH_TIME_FIELD.full_name = ".p_marry_wish.wish_time"
P_MARRY_WISH_WISH_TIME_FIELD.number = 1
P_MARRY_WISH_WISH_TIME_FIELD.index = 0
P_MARRY_WISH_WISH_TIME_FIELD.label = 1
P_MARRY_WISH_WISH_TIME_FIELD.has_default_value = true
P_MARRY_WISH_WISH_TIME_FIELD.default_value = 0
P_MARRY_WISH_WISH_TIME_FIELD.type = 5
P_MARRY_WISH_WISH_TIME_FIELD.cpp_type = 1

P_MARRY_WISH_ROLE_ID_FIELD.name = "role_id"
P_MARRY_WISH_ROLE_ID_FIELD.full_name = ".p_marry_wish.role_id"
P_MARRY_WISH_ROLE_ID_FIELD.number = 2
P_MARRY_WISH_ROLE_ID_FIELD.index = 1
P_MARRY_WISH_ROLE_ID_FIELD.label = 1
P_MARRY_WISH_ROLE_ID_FIELD.has_default_value = true
P_MARRY_WISH_ROLE_ID_FIELD.default_value = 0
P_MARRY_WISH_ROLE_ID_FIELD.type = 3
P_MARRY_WISH_ROLE_ID_FIELD.cpp_type = 2

P_MARRY_WISH_ROLE_NAME_FIELD.name = "role_name"
P_MARRY_WISH_ROLE_NAME_FIELD.full_name = ".p_marry_wish.role_name"
P_MARRY_WISH_ROLE_NAME_FIELD.number = 3
P_MARRY_WISH_ROLE_NAME_FIELD.index = 2
P_MARRY_WISH_ROLE_NAME_FIELD.label = 1
P_MARRY_WISH_ROLE_NAME_FIELD.has_default_value = false
P_MARRY_WISH_ROLE_NAME_FIELD.default_value = ""
P_MARRY_WISH_ROLE_NAME_FIELD.type = 9
P_MARRY_WISH_ROLE_NAME_FIELD.cpp_type = 9

P_MARRY_WISH_TO_ROLE_ID_FIELD.name = "to_role_id"
P_MARRY_WISH_TO_ROLE_ID_FIELD.full_name = ".p_marry_wish.to_role_id"
P_MARRY_WISH_TO_ROLE_ID_FIELD.number = 4
P_MARRY_WISH_TO_ROLE_ID_FIELD.index = 3
P_MARRY_WISH_TO_ROLE_ID_FIELD.label = 1
P_MARRY_WISH_TO_ROLE_ID_FIELD.has_default_value = true
P_MARRY_WISH_TO_ROLE_ID_FIELD.default_value = 0
P_MARRY_WISH_TO_ROLE_ID_FIELD.type = 3
P_MARRY_WISH_TO_ROLE_ID_FIELD.cpp_type = 2

P_MARRY_WISH_TO_ROLE_NAME_FIELD.name = "to_role_name"
P_MARRY_WISH_TO_ROLE_NAME_FIELD.full_name = ".p_marry_wish.to_role_name"
P_MARRY_WISH_TO_ROLE_NAME_FIELD.number = 5
P_MARRY_WISH_TO_ROLE_NAME_FIELD.index = 4
P_MARRY_WISH_TO_ROLE_NAME_FIELD.label = 1
P_MARRY_WISH_TO_ROLE_NAME_FIELD.has_default_value = false
P_MARRY_WISH_TO_ROLE_NAME_FIELD.default_value = ""
P_MARRY_WISH_TO_ROLE_NAME_FIELD.type = 9
P_MARRY_WISH_TO_ROLE_NAME_FIELD.cpp_type = 9

P_MARRY_WISH_INDEX_ID_FIELD.name = "index_id"
P_MARRY_WISH_INDEX_ID_FIELD.full_name = ".p_marry_wish.index_id"
P_MARRY_WISH_INDEX_ID_FIELD.number = 6
P_MARRY_WISH_INDEX_ID_FIELD.index = 5
P_MARRY_WISH_INDEX_ID_FIELD.label = 1
P_MARRY_WISH_INDEX_ID_FIELD.has_default_value = true
P_MARRY_WISH_INDEX_ID_FIELD.default_value = 0
P_MARRY_WISH_INDEX_ID_FIELD.type = 5
P_MARRY_WISH_INDEX_ID_FIELD.cpp_type = 1

P_MARRY_WISH.name = "p_marry_wish"
P_MARRY_WISH.full_name = ".p_marry_wish"
P_MARRY_WISH.nested_types = {}
P_MARRY_WISH.enum_types = {}
P_MARRY_WISH.fields = {P_MARRY_WISH_WISH_TIME_FIELD, P_MARRY_WISH_ROLE_ID_FIELD, P_MARRY_WISH_ROLE_NAME_FIELD, P_MARRY_WISH_TO_ROLE_ID_FIELD, P_MARRY_WISH_TO_ROLE_NAME_FIELD, P_MARRY_WISH_INDEX_ID_FIELD}
P_MARRY_WISH.is_extendable = false
P_MARRY_WISH.extensions = {}

p_marry_wish = protobuf.Message(P_MARRY_WISH)

