--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_kv_pb = require("Protol.p_kv_pb")
module('Protol.p_market_log_pb')

P_MARKET_LOG = protobuf.Descriptor();
P_MARKET_LOG_ID_FIELD = protobuf.FieldDescriptor();
P_MARKET_LOG_TYPE_ID_FIELD = protobuf.FieldDescriptor();
P_MARKET_LOG_NUM_FIELD = protobuf.FieldDescriptor();
P_MARKET_LOG_EXCELLENT_LIST_FIELD = protobuf.FieldDescriptor();
P_MARKET_LOG_UNIT_PRICE_FIELD = protobuf.FieldDescriptor();
P_MARKET_LOG_TOTAL_PRICE_FIELD = protobuf.FieldDescriptor();
P_MARKET_LOG_TIME_FIELD = protobuf.FieldDescriptor();
P_MARKET_LOG_LOG_TYPE_FIELD = protobuf.FieldDescriptor();
P_MARKET_LOG_TAX_FIELD = protobuf.FieldDescriptor();

P_MARKET_LOG_ID_FIELD.name = "id"
P_MARKET_LOG_ID_FIELD.full_name = ".p_market_log.id"
P_MARKET_LOG_ID_FIELD.number = 1
P_MARKET_LOG_ID_FIELD.index = 0
P_MARKET_LOG_ID_FIELD.label = 1
P_MARKET_LOG_ID_FIELD.has_default_value = true
P_MARKET_LOG_ID_FIELD.default_value = 0
P_MARKET_LOG_ID_FIELD.type = 5
P_MARKET_LOG_ID_FIELD.cpp_type = 1

P_MARKET_LOG_TYPE_ID_FIELD.name = "type_id"
P_MARKET_LOG_TYPE_ID_FIELD.full_name = ".p_market_log.type_id"
P_MARKET_LOG_TYPE_ID_FIELD.number = 2
P_MARKET_LOG_TYPE_ID_FIELD.index = 1
P_MARKET_LOG_TYPE_ID_FIELD.label = 1
P_MARKET_LOG_TYPE_ID_FIELD.has_default_value = true
P_MARKET_LOG_TYPE_ID_FIELD.default_value = 0
P_MARKET_LOG_TYPE_ID_FIELD.type = 5
P_MARKET_LOG_TYPE_ID_FIELD.cpp_type = 1

P_MARKET_LOG_NUM_FIELD.name = "num"
P_MARKET_LOG_NUM_FIELD.full_name = ".p_market_log.num"
P_MARKET_LOG_NUM_FIELD.number = 3
P_MARKET_LOG_NUM_FIELD.index = 2
P_MARKET_LOG_NUM_FIELD.label = 1
P_MARKET_LOG_NUM_FIELD.has_default_value = true
P_MARKET_LOG_NUM_FIELD.default_value = 0
P_MARKET_LOG_NUM_FIELD.type = 5
P_MARKET_LOG_NUM_FIELD.cpp_type = 1

P_MARKET_LOG_EXCELLENT_LIST_FIELD.name = "excellent_list"
P_MARKET_LOG_EXCELLENT_LIST_FIELD.full_name = ".p_market_log.excellent_list"
P_MARKET_LOG_EXCELLENT_LIST_FIELD.number = 4
P_MARKET_LOG_EXCELLENT_LIST_FIELD.index = 3
P_MARKET_LOG_EXCELLENT_LIST_FIELD.label = 3
P_MARKET_LOG_EXCELLENT_LIST_FIELD.has_default_value = false
P_MARKET_LOG_EXCELLENT_LIST_FIELD.default_value = {}
P_MARKET_LOG_EXCELLENT_LIST_FIELD.message_type = p_kv_pb.P_KV
P_MARKET_LOG_EXCELLENT_LIST_FIELD.type = 11
P_MARKET_LOG_EXCELLENT_LIST_FIELD.cpp_type = 10

P_MARKET_LOG_UNIT_PRICE_FIELD.name = "unit_price"
P_MARKET_LOG_UNIT_PRICE_FIELD.full_name = ".p_market_log.unit_price"
P_MARKET_LOG_UNIT_PRICE_FIELD.number = 5
P_MARKET_LOG_UNIT_PRICE_FIELD.index = 4
P_MARKET_LOG_UNIT_PRICE_FIELD.label = 1
P_MARKET_LOG_UNIT_PRICE_FIELD.has_default_value = true
P_MARKET_LOG_UNIT_PRICE_FIELD.default_value = 0
P_MARKET_LOG_UNIT_PRICE_FIELD.type = 5
P_MARKET_LOG_UNIT_PRICE_FIELD.cpp_type = 1

P_MARKET_LOG_TOTAL_PRICE_FIELD.name = "total_price"
P_MARKET_LOG_TOTAL_PRICE_FIELD.full_name = ".p_market_log.total_price"
P_MARKET_LOG_TOTAL_PRICE_FIELD.number = 6
P_MARKET_LOG_TOTAL_PRICE_FIELD.index = 5
P_MARKET_LOG_TOTAL_PRICE_FIELD.label = 1
P_MARKET_LOG_TOTAL_PRICE_FIELD.has_default_value = true
P_MARKET_LOG_TOTAL_PRICE_FIELD.default_value = 0
P_MARKET_LOG_TOTAL_PRICE_FIELD.type = 5
P_MARKET_LOG_TOTAL_PRICE_FIELD.cpp_type = 1

P_MARKET_LOG_TIME_FIELD.name = "time"
P_MARKET_LOG_TIME_FIELD.full_name = ".p_market_log.time"
P_MARKET_LOG_TIME_FIELD.number = 7
P_MARKET_LOG_TIME_FIELD.index = 6
P_MARKET_LOG_TIME_FIELD.label = 1
P_MARKET_LOG_TIME_FIELD.has_default_value = true
P_MARKET_LOG_TIME_FIELD.default_value = 0
P_MARKET_LOG_TIME_FIELD.type = 5
P_MARKET_LOG_TIME_FIELD.cpp_type = 1

P_MARKET_LOG_LOG_TYPE_FIELD.name = "log_type"
P_MARKET_LOG_LOG_TYPE_FIELD.full_name = ".p_market_log.log_type"
P_MARKET_LOG_LOG_TYPE_FIELD.number = 8
P_MARKET_LOG_LOG_TYPE_FIELD.index = 7
P_MARKET_LOG_LOG_TYPE_FIELD.label = 1
P_MARKET_LOG_LOG_TYPE_FIELD.has_default_value = true
P_MARKET_LOG_LOG_TYPE_FIELD.default_value = 0
P_MARKET_LOG_LOG_TYPE_FIELD.type = 5
P_MARKET_LOG_LOG_TYPE_FIELD.cpp_type = 1

P_MARKET_LOG_TAX_FIELD.name = "tax"
P_MARKET_LOG_TAX_FIELD.full_name = ".p_market_log.tax"
P_MARKET_LOG_TAX_FIELD.number = 9
P_MARKET_LOG_TAX_FIELD.index = 8
P_MARKET_LOG_TAX_FIELD.label = 1
P_MARKET_LOG_TAX_FIELD.has_default_value = true
P_MARKET_LOG_TAX_FIELD.default_value = 0
P_MARKET_LOG_TAX_FIELD.type = 5
P_MARKET_LOG_TAX_FIELD.cpp_type = 1

P_MARKET_LOG.name = "p_market_log"
P_MARKET_LOG.full_name = ".p_market_log"
P_MARKET_LOG.nested_types = {}
P_MARKET_LOG.enum_types = {}
P_MARKET_LOG.fields = {P_MARKET_LOG_ID_FIELD, P_MARKET_LOG_TYPE_ID_FIELD, P_MARKET_LOG_NUM_FIELD, P_MARKET_LOG_EXCELLENT_LIST_FIELD, P_MARKET_LOG_UNIT_PRICE_FIELD, P_MARKET_LOG_TOTAL_PRICE_FIELD, P_MARKET_LOG_TIME_FIELD, P_MARKET_LOG_LOG_TYPE_FIELD, P_MARKET_LOG_TAX_FIELD}
P_MARKET_LOG.is_extendable = false
P_MARKET_LOG.extensions = {}

p_market_log = protobuf.Message(P_MARKET_LOG)

