--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.p_pray_log_pb')

P_PRAY_LOG = protobuf.Descriptor();
P_PRAY_LOG_ROLE_NAME_FIELD = protobuf.FieldDescriptor();
P_PRAY_LOG_REWARD_TYPE_FIELD = protobuf.FieldDescriptor();
P_PRAY_LOG_TYPE_ID_LIST_FIELD = protobuf.FieldDescriptor();

P_PRAY_LOG_ROLE_NAME_FIELD.name = "role_name"
P_PRAY_LOG_ROLE_NAME_FIELD.full_name = ".p_pray_log.role_name"
P_PRAY_LOG_ROLE_NAME_FIELD.number = 1
P_PRAY_LOG_ROLE_NAME_FIELD.index = 0
P_PRAY_LOG_ROLE_NAME_FIELD.label = 1
P_PRAY_LOG_ROLE_NAME_FIELD.has_default_value = false
P_PRAY_LOG_ROLE_NAME_FIELD.default_value = ""
P_PRAY_LOG_ROLE_NAME_FIELD.type = 9
P_PRAY_LOG_ROLE_NAME_FIELD.cpp_type = 9

P_PRAY_LOG_REWARD_TYPE_FIELD.name = "reward_type"
P_PRAY_LOG_REWARD_TYPE_FIELD.full_name = ".p_pray_log.reward_type"
P_PRAY_LOG_REWARD_TYPE_FIELD.number = 2
P_PRAY_LOG_REWARD_TYPE_FIELD.index = 1
P_PRAY_LOG_REWARD_TYPE_FIELD.label = 1
P_PRAY_LOG_REWARD_TYPE_FIELD.has_default_value = true
P_PRAY_LOG_REWARD_TYPE_FIELD.default_value = 0
P_PRAY_LOG_REWARD_TYPE_FIELD.type = 5
P_PRAY_LOG_REWARD_TYPE_FIELD.cpp_type = 1

P_PRAY_LOG_TYPE_ID_LIST_FIELD.name = "type_id_list"
P_PRAY_LOG_TYPE_ID_LIST_FIELD.full_name = ".p_pray_log.type_id_list"
P_PRAY_LOG_TYPE_ID_LIST_FIELD.number = 3
P_PRAY_LOG_TYPE_ID_LIST_FIELD.index = 2
P_PRAY_LOG_TYPE_ID_LIST_FIELD.label = 3
P_PRAY_LOG_TYPE_ID_LIST_FIELD.has_default_value = false
P_PRAY_LOG_TYPE_ID_LIST_FIELD.default_value = {}
P_PRAY_LOG_TYPE_ID_LIST_FIELD.type = 5
P_PRAY_LOG_TYPE_ID_LIST_FIELD.cpp_type = 1

P_PRAY_LOG.name = "p_pray_log"
P_PRAY_LOG.full_name = ".p_pray_log"
P_PRAY_LOG.nested_types = {}
P_PRAY_LOG.enum_types = {}
P_PRAY_LOG.fields = {P_PRAY_LOG_ROLE_NAME_FIELD, P_PRAY_LOG_REWARD_TYPE_FIELD, P_PRAY_LOG_TYPE_ID_LIST_FIELD}
P_PRAY_LOG.is_extendable = false
P_PRAY_LOG.extensions = {}

p_pray_log = protobuf.Message(P_PRAY_LOG)

