--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_dkv_pb = require("Protol.p_dkv_pb")
local p_ks_pb = require("Protol.p_ks_pb")
module('Protol.p_rank_pb')

P_RANK = protobuf.Descriptor();
P_RANK_RANK_FIELD = protobuf.FieldDescriptor();
P_RANK_ROLE_ID_FIELD = protobuf.FieldDescriptor();
P_RANK_ROLE_NAME_FIELD = protobuf.FieldDescriptor();
P_RANK_ROLE_LEVEL_FIELD = protobuf.FieldDescriptor();
P_RANK_VIP_LEVEL_FIELD = protobuf.FieldDescriptor();
P_RANK_CATEGORY_FIELD = protobuf.FieldDescriptor();
P_RANK_CONFINE_FIELD = protobuf.FieldDescriptor();
P_RANK_RELIVE_LEVEL_FIELD = protobuf.FieldDescriptor();
P_RANK_KV_LIST_FIELD = protobuf.FieldDescriptor();
P_RANK_KS_LIST_FIELD = protobuf.FieldDescriptor();

P_RANK_RANK_FIELD.name = "rank"
P_RANK_RANK_FIELD.full_name = ".p_rank.rank"
P_RANK_RANK_FIELD.number = 1
P_RANK_RANK_FIELD.index = 0
P_RANK_RANK_FIELD.label = 1
P_RANK_RANK_FIELD.has_default_value = true
P_RANK_RANK_FIELD.default_value = 0
P_RANK_RANK_FIELD.type = 5
P_RANK_RANK_FIELD.cpp_type = 1

P_RANK_ROLE_ID_FIELD.name = "role_id"
P_RANK_ROLE_ID_FIELD.full_name = ".p_rank.role_id"
P_RANK_ROLE_ID_FIELD.number = 2
P_RANK_ROLE_ID_FIELD.index = 1
P_RANK_ROLE_ID_FIELD.label = 1
P_RANK_ROLE_ID_FIELD.has_default_value = true
P_RANK_ROLE_ID_FIELD.default_value = 0
P_RANK_ROLE_ID_FIELD.type = 3
P_RANK_ROLE_ID_FIELD.cpp_type = 2

P_RANK_ROLE_NAME_FIELD.name = "role_name"
P_RANK_ROLE_NAME_FIELD.full_name = ".p_rank.role_name"
P_RANK_ROLE_NAME_FIELD.number = 3
P_RANK_ROLE_NAME_FIELD.index = 2
P_RANK_ROLE_NAME_FIELD.label = 1
P_RANK_ROLE_NAME_FIELD.has_default_value = false
P_RANK_ROLE_NAME_FIELD.default_value = ""
P_RANK_ROLE_NAME_FIELD.type = 9
P_RANK_ROLE_NAME_FIELD.cpp_type = 9

P_RANK_ROLE_LEVEL_FIELD.name = "role_level"
P_RANK_ROLE_LEVEL_FIELD.full_name = ".p_rank.role_level"
P_RANK_ROLE_LEVEL_FIELD.number = 4
P_RANK_ROLE_LEVEL_FIELD.index = 3
P_RANK_ROLE_LEVEL_FIELD.label = 1
P_RANK_ROLE_LEVEL_FIELD.has_default_value = true
P_RANK_ROLE_LEVEL_FIELD.default_value = 0
P_RANK_ROLE_LEVEL_FIELD.type = 5
P_RANK_ROLE_LEVEL_FIELD.cpp_type = 1

P_RANK_VIP_LEVEL_FIELD.name = "vip_level"
P_RANK_VIP_LEVEL_FIELD.full_name = ".p_rank.vip_level"
P_RANK_VIP_LEVEL_FIELD.number = 5
P_RANK_VIP_LEVEL_FIELD.index = 4
P_RANK_VIP_LEVEL_FIELD.label = 1
P_RANK_VIP_LEVEL_FIELD.has_default_value = true
P_RANK_VIP_LEVEL_FIELD.default_value = 0
P_RANK_VIP_LEVEL_FIELD.type = 5
P_RANK_VIP_LEVEL_FIELD.cpp_type = 1

P_RANK_CATEGORY_FIELD.name = "category"
P_RANK_CATEGORY_FIELD.full_name = ".p_rank.category"
P_RANK_CATEGORY_FIELD.number = 6
P_RANK_CATEGORY_FIELD.index = 5
P_RANK_CATEGORY_FIELD.label = 1
P_RANK_CATEGORY_FIELD.has_default_value = true
P_RANK_CATEGORY_FIELD.default_value = 0
P_RANK_CATEGORY_FIELD.type = 5
P_RANK_CATEGORY_FIELD.cpp_type = 1

P_RANK_CONFINE_FIELD.name = "confine"
P_RANK_CONFINE_FIELD.full_name = ".p_rank.confine"
P_RANK_CONFINE_FIELD.number = 7
P_RANK_CONFINE_FIELD.index = 6
P_RANK_CONFINE_FIELD.label = 1
P_RANK_CONFINE_FIELD.has_default_value = true
P_RANK_CONFINE_FIELD.default_value = 0
P_RANK_CONFINE_FIELD.type = 5
P_RANK_CONFINE_FIELD.cpp_type = 1

P_RANK_RELIVE_LEVEL_FIELD.name = "relive_level"
P_RANK_RELIVE_LEVEL_FIELD.full_name = ".p_rank.relive_level"
P_RANK_RELIVE_LEVEL_FIELD.number = 8
P_RANK_RELIVE_LEVEL_FIELD.index = 7
P_RANK_RELIVE_LEVEL_FIELD.label = 1
P_RANK_RELIVE_LEVEL_FIELD.has_default_value = true
P_RANK_RELIVE_LEVEL_FIELD.default_value = 0
P_RANK_RELIVE_LEVEL_FIELD.type = 5
P_RANK_RELIVE_LEVEL_FIELD.cpp_type = 1

P_RANK_KV_LIST_FIELD.name = "kv_list"
P_RANK_KV_LIST_FIELD.full_name = ".p_rank.kv_list"
P_RANK_KV_LIST_FIELD.number = 9
P_RANK_KV_LIST_FIELD.index = 8
P_RANK_KV_LIST_FIELD.label = 3
P_RANK_KV_LIST_FIELD.has_default_value = false
P_RANK_KV_LIST_FIELD.default_value = {}
P_RANK_KV_LIST_FIELD.message_type = p_dkv_pb.P_DKV
P_RANK_KV_LIST_FIELD.type = 11
P_RANK_KV_LIST_FIELD.cpp_type = 10

P_RANK_KS_LIST_FIELD.name = "ks_list"
P_RANK_KS_LIST_FIELD.full_name = ".p_rank.ks_list"
P_RANK_KS_LIST_FIELD.number = 10
P_RANK_KS_LIST_FIELD.index = 9
P_RANK_KS_LIST_FIELD.label = 3
P_RANK_KS_LIST_FIELD.has_default_value = false
P_RANK_KS_LIST_FIELD.default_value = {}
P_RANK_KS_LIST_FIELD.message_type = p_ks_pb.P_KS
P_RANK_KS_LIST_FIELD.type = 11
P_RANK_KS_LIST_FIELD.cpp_type = 10

P_RANK.name = "p_rank"
P_RANK.full_name = ".p_rank"
P_RANK.nested_types = {}
P_RANK.enum_types = {}
P_RANK.fields = {P_RANK_RANK_FIELD, P_RANK_ROLE_ID_FIELD, P_RANK_ROLE_NAME_FIELD, P_RANK_ROLE_LEVEL_FIELD, P_RANK_VIP_LEVEL_FIELD, P_RANK_CATEGORY_FIELD, P_RANK_CONFINE_FIELD, P_RANK_RELIVE_LEVEL_FIELD, P_RANK_KV_LIST_FIELD, P_RANK_KS_LIST_FIELD}
P_RANK.is_extendable = false
P_RANK.extensions = {}

p_rank = protobuf.Message(P_RANK)

