--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local p_red_packet_content_pb = require("Protol.p_red_packet_content_pb")
module('Protol.p_red_packet_pb')

P_RED_PACKET = protobuf.Descriptor();
P_RED_PACKET_ID_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_ICON_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_SENDER_NAME_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_CONTENT_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_TIME_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_AMOUNT_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_PIECE_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_BIND_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_SENT_NUM_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_PACKET_LIST_FIELD = protobuf.FieldDescriptor();
P_RED_PACKET_ROLE_LIST_FIELD = protobuf.FieldDescriptor();

P_RED_PACKET_ID_FIELD.name = "id"
P_RED_PACKET_ID_FIELD.full_name = ".p_red_packet.id"
P_RED_PACKET_ID_FIELD.number = 1
P_RED_PACKET_ID_FIELD.index = 0
P_RED_PACKET_ID_FIELD.label = 1
P_RED_PACKET_ID_FIELD.has_default_value = true
P_RED_PACKET_ID_FIELD.default_value = 0
P_RED_PACKET_ID_FIELD.type = 3
P_RED_PACKET_ID_FIELD.cpp_type = 2

P_RED_PACKET_ICON_FIELD.name = "icon"
P_RED_PACKET_ICON_FIELD.full_name = ".p_red_packet.icon"
P_RED_PACKET_ICON_FIELD.number = 2
P_RED_PACKET_ICON_FIELD.index = 1
P_RED_PACKET_ICON_FIELD.label = 1
P_RED_PACKET_ICON_FIELD.has_default_value = true
P_RED_PACKET_ICON_FIELD.default_value = 0
P_RED_PACKET_ICON_FIELD.type = 5
P_RED_PACKET_ICON_FIELD.cpp_type = 1

P_RED_PACKET_SENDER_NAME_FIELD.name = "sender_name"
P_RED_PACKET_SENDER_NAME_FIELD.full_name = ".p_red_packet.sender_name"
P_RED_PACKET_SENDER_NAME_FIELD.number = 3
P_RED_PACKET_SENDER_NAME_FIELD.index = 2
P_RED_PACKET_SENDER_NAME_FIELD.label = 1
P_RED_PACKET_SENDER_NAME_FIELD.has_default_value = false
P_RED_PACKET_SENDER_NAME_FIELD.default_value = ""
P_RED_PACKET_SENDER_NAME_FIELD.type = 9
P_RED_PACKET_SENDER_NAME_FIELD.cpp_type = 9

P_RED_PACKET_CONTENT_FIELD.name = "content"
P_RED_PACKET_CONTENT_FIELD.full_name = ".p_red_packet.content"
P_RED_PACKET_CONTENT_FIELD.number = 4
P_RED_PACKET_CONTENT_FIELD.index = 3
P_RED_PACKET_CONTENT_FIELD.label = 1
P_RED_PACKET_CONTENT_FIELD.has_default_value = false
P_RED_PACKET_CONTENT_FIELD.default_value = ""
P_RED_PACKET_CONTENT_FIELD.type = 9
P_RED_PACKET_CONTENT_FIELD.cpp_type = 9

P_RED_PACKET_TIME_FIELD.name = "time"
P_RED_PACKET_TIME_FIELD.full_name = ".p_red_packet.time"
P_RED_PACKET_TIME_FIELD.number = 5
P_RED_PACKET_TIME_FIELD.index = 4
P_RED_PACKET_TIME_FIELD.label = 1
P_RED_PACKET_TIME_FIELD.has_default_value = true
P_RED_PACKET_TIME_FIELD.default_value = 0
P_RED_PACKET_TIME_FIELD.type = 5
P_RED_PACKET_TIME_FIELD.cpp_type = 1

P_RED_PACKET_AMOUNT_FIELD.name = "amount"
P_RED_PACKET_AMOUNT_FIELD.full_name = ".p_red_packet.amount"
P_RED_PACKET_AMOUNT_FIELD.number = 6
P_RED_PACKET_AMOUNT_FIELD.index = 5
P_RED_PACKET_AMOUNT_FIELD.label = 1
P_RED_PACKET_AMOUNT_FIELD.has_default_value = true
P_RED_PACKET_AMOUNT_FIELD.default_value = 0
P_RED_PACKET_AMOUNT_FIELD.type = 5
P_RED_PACKET_AMOUNT_FIELD.cpp_type = 1

P_RED_PACKET_PIECE_FIELD.name = "piece"
P_RED_PACKET_PIECE_FIELD.full_name = ".p_red_packet.piece"
P_RED_PACKET_PIECE_FIELD.number = 7
P_RED_PACKET_PIECE_FIELD.index = 6
P_RED_PACKET_PIECE_FIELD.label = 1
P_RED_PACKET_PIECE_FIELD.has_default_value = true
P_RED_PACKET_PIECE_FIELD.default_value = 0
P_RED_PACKET_PIECE_FIELD.type = 5
P_RED_PACKET_PIECE_FIELD.cpp_type = 1

P_RED_PACKET_BIND_FIELD.name = "bind"
P_RED_PACKET_BIND_FIELD.full_name = ".p_red_packet.bind"
P_RED_PACKET_BIND_FIELD.number = 8
P_RED_PACKET_BIND_FIELD.index = 7
P_RED_PACKET_BIND_FIELD.label = 1
P_RED_PACKET_BIND_FIELD.has_default_value = true
P_RED_PACKET_BIND_FIELD.default_value = 0
P_RED_PACKET_BIND_FIELD.type = 5
P_RED_PACKET_BIND_FIELD.cpp_type = 1

P_RED_PACKET_SENT_NUM_FIELD.name = "sent_num"
P_RED_PACKET_SENT_NUM_FIELD.full_name = ".p_red_packet.sent_num"
P_RED_PACKET_SENT_NUM_FIELD.number = 9
P_RED_PACKET_SENT_NUM_FIELD.index = 8
P_RED_PACKET_SENT_NUM_FIELD.label = 1
P_RED_PACKET_SENT_NUM_FIELD.has_default_value = true
P_RED_PACKET_SENT_NUM_FIELD.default_value = 0
P_RED_PACKET_SENT_NUM_FIELD.type = 5
P_RED_PACKET_SENT_NUM_FIELD.cpp_type = 1

P_RED_PACKET_PACKET_LIST_FIELD.name = "packet_list"
P_RED_PACKET_PACKET_LIST_FIELD.full_name = ".p_red_packet.packet_list"
P_RED_PACKET_PACKET_LIST_FIELD.number = 10
P_RED_PACKET_PACKET_LIST_FIELD.index = 9
P_RED_PACKET_PACKET_LIST_FIELD.label = 3
P_RED_PACKET_PACKET_LIST_FIELD.has_default_value = false
P_RED_PACKET_PACKET_LIST_FIELD.default_value = {}
P_RED_PACKET_PACKET_LIST_FIELD.message_type = p_red_packet_content_pb.P_RED_PACKET_CONTENT
P_RED_PACKET_PACKET_LIST_FIELD.type = 11
P_RED_PACKET_PACKET_LIST_FIELD.cpp_type = 10

P_RED_PACKET_ROLE_LIST_FIELD.name = "role_list"
P_RED_PACKET_ROLE_LIST_FIELD.full_name = ".p_red_packet.role_list"
P_RED_PACKET_ROLE_LIST_FIELD.number = 11
P_RED_PACKET_ROLE_LIST_FIELD.index = 10
P_RED_PACKET_ROLE_LIST_FIELD.label = 3
P_RED_PACKET_ROLE_LIST_FIELD.has_default_value = false
P_RED_PACKET_ROLE_LIST_FIELD.default_value = {}
P_RED_PACKET_ROLE_LIST_FIELD.type = 3
P_RED_PACKET_ROLE_LIST_FIELD.cpp_type = 2

P_RED_PACKET.name = "p_red_packet"
P_RED_PACKET.full_name = ".p_red_packet"
P_RED_PACKET.nested_types = {}
P_RED_PACKET.enum_types = {}
P_RED_PACKET.fields = {P_RED_PACKET_ID_FIELD, P_RED_PACKET_ICON_FIELD, P_RED_PACKET_SENDER_NAME_FIELD, P_RED_PACKET_CONTENT_FIELD, P_RED_PACKET_TIME_FIELD, P_RED_PACKET_AMOUNT_FIELD, P_RED_PACKET_PIECE_FIELD, P_RED_PACKET_BIND_FIELD, P_RED_PACKET_SENT_NUM_FIELD, P_RED_PACKET_PACKET_LIST_FIELD, P_RED_PACKET_ROLE_LIST_FIELD}
P_RED_PACKET.is_extendable = false
P_RED_PACKET.extensions = {}

p_red_packet = protobuf.Message(P_RED_PACKET)

