--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.p_war_god_equip_pb')

P_WAR_GOD_EQUIP = protobuf.Descriptor();
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD = protobuf.FieldDescriptor();
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD = protobuf.FieldDescriptor();
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD = protobuf.FieldDescriptor();

P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.name = "equip_id"
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.full_name = ".p_war_god_equip.equip_id"
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.number = 1
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.index = 0
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.label = 1
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.has_default_value = true
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.default_value = 0
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.type = 5
P_WAR_GOD_EQUIP_EQUIP_ID_FIELD.cpp_type = 1

P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.name = "refine_level"
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.full_name = ".p_war_god_equip.refine_level"
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.number = 2
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.index = 1
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.label = 1
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.has_default_value = true
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.default_value = 0
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.type = 5
P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD.cpp_type = 1

P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.name = "refine_exp"
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.full_name = ".p_war_god_equip.refine_exp"
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.number = 3
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.index = 2
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.label = 1
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.has_default_value = true
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.default_value = 0
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.type = 5
P_WAR_GOD_EQUIP_REFINE_EXP_FIELD.cpp_type = 1

P_WAR_GOD_EQUIP.name = "p_war_god_equip"
P_WAR_GOD_EQUIP.full_name = ".p_war_god_equip"
P_WAR_GOD_EQUIP.nested_types = {}
P_WAR_GOD_EQUIP.enum_types = {}
P_WAR_GOD_EQUIP.fields = {P_WAR_GOD_EQUIP_EQUIP_ID_FIELD, P_WAR_GOD_EQUIP_REFINE_LEVEL_FIELD, P_WAR_GOD_EQUIP_REFINE_EXP_FIELD}
P_WAR_GOD_EQUIP.is_extendable = false
P_WAR_GOD_EQUIP.extensions = {}

p_war_god_equip = protobuf.Message(P_WAR_GOD_EQUIP)

