--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.p_week_card_pb')

P_WEEK_CARD = protobuf.Descriptor();
P_WEEK_CARD_ID_FIELD = protobuf.FieldDescriptor();
P_WEEK_CARD_OPEN_TIME_FIELD = protobuf.FieldDescriptor();
P_WEEK_CARD_END_TIME_FIELD = protobuf.FieldDescriptor();
P_WEEK_CARD_REWARD_FIELD = protobuf.FieldDescriptor();

P_WEEK_CARD_ID_FIELD.name = "id"
P_WEEK_CARD_ID_FIELD.full_name = ".p_week_card.id"
P_WEEK_CARD_ID_FIELD.number = 1
P_WEEK_CARD_ID_FIELD.index = 0
P_WEEK_CARD_ID_FIELD.label = 1
P_WEEK_CARD_ID_FIELD.has_default_value = true
P_WEEK_CARD_ID_FIELD.default_value = 0
P_WEEK_CARD_ID_FIELD.type = 5
P_WEEK_CARD_ID_FIELD.cpp_type = 1

P_WEEK_CARD_OPEN_TIME_FIELD.name = "open_time"
P_WEEK_CARD_OPEN_TIME_FIELD.full_name = ".p_week_card.open_time"
P_WEEK_CARD_OPEN_TIME_FIELD.number = 2
P_WEEK_CARD_OPEN_TIME_FIELD.index = 1
P_WEEK_CARD_OPEN_TIME_FIELD.label = 1
P_WEEK_CARD_OPEN_TIME_FIELD.has_default_value = true
P_WEEK_CARD_OPEN_TIME_FIELD.default_value = 0
P_WEEK_CARD_OPEN_TIME_FIELD.type = 5
P_WEEK_CARD_OPEN_TIME_FIELD.cpp_type = 1

P_WEEK_CARD_END_TIME_FIELD.name = "end_time"
P_WEEK_CARD_END_TIME_FIELD.full_name = ".p_week_card.end_time"
P_WEEK_CARD_END_TIME_FIELD.number = 3
P_WEEK_CARD_END_TIME_FIELD.index = 2
P_WEEK_CARD_END_TIME_FIELD.label = 1
P_WEEK_CARD_END_TIME_FIELD.has_default_value = true
P_WEEK_CARD_END_TIME_FIELD.default_value = 0
P_WEEK_CARD_END_TIME_FIELD.type = 5
P_WEEK_CARD_END_TIME_FIELD.cpp_type = 1

P_WEEK_CARD_REWARD_FIELD.name = "reward"
P_WEEK_CARD_REWARD_FIELD.full_name = ".p_week_card.reward"
P_WEEK_CARD_REWARD_FIELD.number = 4
P_WEEK_CARD_REWARD_FIELD.index = 3
P_WEEK_CARD_REWARD_FIELD.label = 3
P_WEEK_CARD_REWARD_FIELD.has_default_value = false
P_WEEK_CARD_REWARD_FIELD.default_value = {}
P_WEEK_CARD_REWARD_FIELD.type = 5
P_WEEK_CARD_REWARD_FIELD.cpp_type = 1

P_WEEK_CARD.name = "p_week_card"
P_WEEK_CARD.full_name = ".p_week_card"
P_WEEK_CARD.nested_types = {}
P_WEEK_CARD.enum_types = {}
P_WEEK_CARD.fields = {P_WEEK_CARD_ID_FIELD, P_WEEK_CARD_OPEN_TIME_FIELD, P_WEEK_CARD_END_TIME_FIELD, P_WEEK_CARD_REWARD_FIELD}
P_WEEK_CARD.is_extendable = false
P_WEEK_CARD.extensions = {}

p_week_card = protobuf.Message(P_WEEK_CARD)

