// Generated by the Table Description Language compiler.  DO NOT EDIT!
// source: role_pro.prot

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


public class RolePro : Table.Binary, Table.IKey
{
	UInt32       m_id;
	Table.String m_pro_name;
	
	public const UInt32 Version = 493378320;
	
	public UInt64 Key()
	{
		return m_id;
	}
	
	public UInt32 id
	{
		get { return m_id; }
	}
	
	public string proName
	{
		get { return m_pro_name; }
	}
	
	public override int Load(byte[] buffer, int index)
	{
		Table.Loader loader = new Table.Loader(ref buffer, index);
		loader.Load(ref m_id).Load(ref m_pro_name);
		return loader.Size;
	}
}

// source: S 角色属性字段.xls, sheet: Sheet1
public sealed class RoleProManager : Table.Manager<RolePro>
{
	private static readonly RoleProManager ms_instance = new RoleProManager();
	
	private RoleProManager()
	{
	}
	
	public static RoleProManager instance
	{
		get { return ms_instance; }
	}
	
	public string source
	{
		get { return "role_pro.tbl"; }
	}
	
	public bool Load(string path)
	{
		Register();
		return Load(path, source, RolePro.Version);
	}
	
	public RolePro Find(UInt32 key)
	{
		return FindInternal(key);
	}
	
	#region new helper
	public static object NewRolePro()
	{
		return new RolePro();
	}
	
	private static void Register()
	{
		Table.NewHelper.Clear();
		Table.NewHelper.Register(typeof(RolePro), NewRolePro);
	}
	#endregion
}

